src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Provider Affiliation</relationshipLabel>
        <relationshipName>Programs_Offered</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Provider_Affiliation</fullName>
        <active>true</active>
        <label>Provider Affiliation</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Provider User</fullName>
                </value>
                <value>
                    <fullName>Provider Team</fullName>
                </value>
                <value>
                    <fullName>Provider Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/FeatureFlagConfig__mdt.object
<CustomObject>
    <fields>
        <fullName>isEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>FeatureFlagConfig</label>
    <pluralLabel>FeatureFlagConfigs</pluralLabel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>It is used to capture the information of all the Programs offered by UHC. </description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complex Care</fullName>
    </customValue>
    <customValue>
        <fullName>Rare Conditions</fullName>
    </customValue>
    <customValue>
        <fullName>Diagnostic Odyssey</fullName>
    </customValue>
    <masterLabel>Program</masterLabel>
</GlobalValueSet>

src/classes/CACHSIDmemSupport_Test.cls
@isTest
public class CACHSIDmemSupport_Test {
    @isTest
    public static void HSIDmemUrls() {
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider_Affiliation').getRecordTypeId();
        List<Account> accList = new List<Account>();
        Account ac = new Account();
        ac.Member_ID__c = '453543543';
        ac.Policy_ID__c = '0070145';
        ac.Name =   'SampleTEstFLAcc1';
        ac.RecordTypeId = recordTypeId;
        accList.add(ac);
        
        Account ac1 = new Account();
        ac1.Member_ID__c = '453543542';
        ac1.Policy_ID__c = '0070142';
        ac1.Name =   'SampleTEstFLAcc2';
        ac1.RecordTypeId = recordTypeId;
        accList.add(ac1);
        
        Account ac3 = new Account();
        ac3.Member_ID__c = '453543543';
        ac3.Policy_ID__c = '0070145';
        ac3.Name =   'SampleTEstFLAcc3';
        ac3.RecordTypeId = recordTypeId;
        accList.add(ac3);
        insert accList;
        
        Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Individual').getRecordTypeId();
        
        Account pa =new account();
        pa.firstName = 'paLastSample1'; 
        pa.lastName = 'paFirstSample1'; 
        pa.RecordTypeId = personAccRecordTypeId;
        insert pa;
        
        Account pa1 =new account(); 
        pa1.firstName = 'paLastSample2'; 
        pa1.lastName = 'paFirstSample2'; 
        pa1.RecordTypeId = personAccRecordTypeId;
        insert pa1;
        
        account pa2 = [select id,personcontactid from account where id =: pa.id];
        Profile p = [SELECT Id FROM Profile WHERE Name='Care Advisor Connect Community User']; 
        User u;
        system.runAs(new user(Id = userinfo.getUserId())){
            u = new User(Alias = 'standt', Email='standarduser@testorg.com.acet', 
                         EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                         LocaleSidKey='en_US', ProfileId = p.Id, 
                         TimeZoneSidKey='America/Los_Angeles', UserName='standarduser45454@testorg.com');
            u.ContactId = pa2.personcontactid;
            insert u;      
        }
        
        AccountContactRelation acr = new AccountContactRelation();
        acr.ContactId = pa2.personcontactid;            
        acr.Accountid = accList[0].id;
        acr.Relationship__c = 'Child/Other';
        insert acr;
        List<program__c> programList=new List<program__c>();
        Program__c pgm = new Program__c();
        pgm.Program__c = 'Complex Care';
        programList.add(pgm);
        insert programList;
        system.debug('Userdetails--'+acr);
        System.runAs(u){
            CACHSIDmemSupport.HSIDmemUrls();
        }
    }
    @isTest
    public static void getCustMetaData(){
        FeatureFlagConfig__mdt fetConf = [select Id,MasterLabel,isEnabled__c from FeatureFlagConfig__mdt where MasterLabel = 'OpenHSIDurls'];
        CACHSIDmemSupport.getCustMetaData();
    }
}