src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Overview__c.object
<CustomObject>
    <description>Family information for MEP.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account the Family Information is related to.</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Overview</relationshipLabel>
        <relationshipName>Family_Overview</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designation_Changed_Date__c</fullName>
        <description>Shows the designation changed date for a family for FEC Graduation purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Designation Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <label>Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Active_Date__c</fullName>
        <description>Shows the last active date for a family for FEC Graduation purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if the group has an Onshore Restriction.  If Yes then only Onshore agents can view the records.  If No then onshore and offshore agents can view the records</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Overview</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Overview</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Family_Story_Guide__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Story Guides</relationshipLabel>
        <relationshipName>Family_Story_Guides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_Modified_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Offered</fullName>
                </value>
                <value>
                    <fullName>Offered</fullName>
                </value>
                <value>
                    <fullName>Declined (Not Interested)</fullName>
                </value>
                <value>
                    <fullName>Declined (Busy, Try Again)</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Partially Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Story Guide</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Story Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Story Guide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Agent_Type__c</fullName>
        <description>Designates where user&apos;s location of either onshore or offshore.  Use for Onshore Restriction cases.</description>
        <label>Agent Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Onshore</fullName>
                    <default>true</default>
                    <label>Onshore</label>
                </value>
                <value>
                    <fullName>Offshore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Access__c</fullName>
        <description>Designates if user can view UHG restricted cases.</description>
        <label>UHG Access</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ACETFamilyGuideCreationController.cls
public without sharing class ACETFamilyGuideCreationController {
    
    @AuraEnabled
    public static void createFSG(string selectVal,Id accountId,Id fsgRecordId){
        //system.debug('ACETFamilyGuideCreationController----createFSG');
        //system.debug('ACETFamilyGuideCreationController----accountId');
        Family_Story_Guide__c famGuide = new Family_Story_Guide__c();
        famGuide.Id = fsgRecordId;
        if(selectVal == 'No'){
            famGuide.Status__c	= 'Declined (Not Interested)';
        }
        else if(selectVal == 'Later'){
            famGuide.Status__c	= 'Declined (Busy, Try Again)';
        }
        famGuide.Status_Modified_Date__c	= system.today();
        famGuide.Expiration_Date__c	= system.today().addMonths(6);
        famGuide.Account__c = accountId;
        Update famGuide;
        
        //famGuide.Expiration_Date__c	= '';   	
    }
    
    @AuraEnabled
    public static Family_Story_Guide__c getFsgRecord(Id accountId){
        Family_Story_Guide__c fsgRecord = new Family_Story_Guide__c(); 
        if(accountId  != null){
            List<Family_Story_Guide__c> fsgRec = [SELECT ID,Status__c,Status_Modified_Date__c,Expiration_Date__c FROM Family_Story_Guide__c Where account__c =: accountId ];
            if(fsgRec.size()>0){
                fsgRecord = fsgRec[0] ;
            }
            
        }
        return fsgRecord ;
        
    }
    @AuraEnabled
    public static boolean getUhgOnshoreRestriction(String accountId){
        Boolean userAccess = true;
       // Boolean uhgPolicy ;
        if(accountId != null){
            List<Account> accRec = [SELECT id,Name,Policy_ID__c,Onshore_Restriction__c FROM Account where Id=:accountId];
            if(accRec != null && ! accRec.isempty()){
            User usr = [SELECT ID,UHG_Access__c,Agent_Type__c FROM USER Where ID=: UserInfo.getUserId()];
            //uhgPolicy = ACETUtility.checkUHGPolicy(accRec[0].Policy_ID__c);
            List<Family_Overview__c> fmOverview = new List<Family_Overview__c>();
            fmOverview = [SELECT UHG_Restriction__c,Onshore_Restriction__c FROM Family_Overview__c WHERE Account__c =:accountId ];
            if(fmOverview == null || fmOverview.isempty()){
                 Family_Overview__c famover = new Family_Overview__c(); 
                 famover.Name = accRec[0].Name+' Family Overview';
                 famover.Account__c = accRec[0].id;
                 famover.Exception__c = 'No';
                 famover.Designation_Changed_Date__c = Date.today();
                 famover.Last_Active_Date__c  = Date.today();
                 boolean insertFO = true;
                 if( ACETUtility.checkUHGPolicy(accRec[0].Policy_ID__c) ){
                     famover.UHG_Restriction__c	 = 'Yes';
                     if(usr.UHG_Access__c != 'Yes'){
                         userAccess = false;
                         list<user> lstUnasignUser = [select id,name,email from user where name = 'Unassigned'];
                         if(lstUnasignUser != null && ! lstUnasignUser.isEmpty())
                             famover.OwnerId = lstUnasignUser[0].id ;
                         else
                              insertFO = false;
                         
                     }
                 }
                 else{
                     famover.UHG_Restriction__c	 = 'No';
                 }
                 if(insertFO){
                    famover.Onshore_Restriction__c = accRec[0].Onshore_Restriction__c;
                    if(accRec[0].Onshore_Restriction__c == 'Yes'){
                        if(usr.Agent_Type__c != 'Onshore'){
                            userAccess = false;
                            list<user> lstUnasignUser = [select id,name,email from user where name = 'Unassigned'];
                            if(lstUnasignUser != null && ! lstUnasignUser.isEmpty())
                                famover.OwnerId = lstUnasignUser[0].id ;
                            else
                                insertFO = false;
                        }
                    }
                }
                fmOverview.add(famover);
                if(insertFO)
                   insert fmOverview;
            }
            else {
                if((fmOverview[0].UHG_Restriction__c == 'Yes' && usr.UHG_Access__c != 'Yes' ) || (fmOverview[0].Onshore_Restriction__c == 'Yes' && usr.Agent_Type__c != 'Onshore')){
                    userAccess = false;
                }
            }
        }
        }
        system.debug('******* user access'+userAccess);
        return userAccess;
    }
    @AuraEnabled
    public static String getUserProfile(){
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        System.debug('profileName=='+profileName);
        return profileName;
    }
    
}