src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Alternate_Id__c</fullName>
        <description>This field stores the alternate member Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Alternate ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/FeatureFlagConfig__mdt.object
<CustomObject>
    <fields>
        <fullName>isEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isEnabled</label>
        <type>Checkbox</type>
    </fields>
    <label>FeatureFlagConfig</label>
    <pluralLabel>FeatureFlagConfigs</pluralLabel>
</CustomObject>

src/classes/CACHSIDmemSupport.cls
public class CACHSIDmemSupport {
    
    @AuraEnabled
    public static Boolean HSIDmemUrls() {
            User u = [select Id , AccountId, profile.name from User where Id = :UserInfo.getUserId()];             
            Account acc = [Select ID, PersonContactID    from Account where ID= :u.AccountId];            
            List<AccountContactRelation> lsacr = [ SELECT Member_ID__c, account.alternate_id__c  FROM AccountContactRelation WHERE  ContactID  = :acc.PersonContactID];			
			Boolean isMember = false;
			if (!lsacr.isEmpty() && lsacr.size() > 0) {
                for(AccountContactRelation acr : lsacr) {
                    if (acr.Member_ID__c != null) {
                        isMember = true;
                    }                
                   
                }
            }
			return isMember;
    }
    
    @AuraEnabled
    public static Boolean getCustMetaData(){
        FeatureFlagConfig__mdt fetConf = [select Id,MasterLabel,isEnabled__c from FeatureFlagConfig__mdt where MasterLabel = 'OpenHSIDurls'];
        return fetConf.isEnabled__c;
    }

}