src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETConsumerAccountsControllerTest.cls
@isTest(seealldata=true)
private class ACETConsumerAccountsControllerTest{
    private static testMethod void unitTestMethodForProvider(){
        user memberAgent;
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        System.runAs(thisUser){
            setTestData('Provider');
            memberAgent = TestDataFactory.getUser('ACET Provider'); 
        }
        System.runAs(memberAgent){
            ACETConsumerAccountsController acetCA = new ACETConsumerAccountsController();
            acetCA.getTopics();
            acetCA.getAccountTypes();
            acetCA.getCancelReasons();
            acetCA.endCall();
            acetCA.renderCancelCaseSection();
        }
    }
    private static testMethod void unitTestMethodForMember(){
        user memberAgent;
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        System.runAs(thisUser){
            setTestData('Member');
            memberAgent = TestDataFactory.getUser('ACET Member'); 
        }
        System.runAs(memberAgent){
            ACETConsumerAccountsController acetCA = new ACETConsumerAccountsController();
            acetCA.getTopics();
            acetCA.getAccountTypes();
            acetCA.getCancelReasons();
            acetCA.endCall();
            acetCA.renderCancelCaseSection();
        }
    }  
    private static testMethod void unitTestMethodForResearch(){
        user memberAgent;
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        System.runAs(thisUser){
            ApexPages.currentPage().getParameters().put('SRK','1234');
            setTestData('Research User');
            memberAgent = TestDataFactory.getUser('Research User');
        }
        System.runAs(memberAgent){
            ACETConsumerAccountsController acetCA = new ACETConsumerAccountsController();
            acetCA.getTopics();
            acetCA.getAccountTypes();
            acetCA.getCancelReasons();
            acetCA.endCall();
            acetCA.renderCancelCaseSection();
        }
    }  
    private static testMethod void unitTestMethodTestCases(){
        user memberAgent;
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        System.runAs(thisUser){
            setTestData('Member');
            memberAgent = TestDataFactory.getUser('ACET Member'); 
        }
        System.runAs(memberAgent){
            ACETConsumerAccountsController acetCA = new ACETConsumerAccountsController();
            acetCA.getTopics();
            acetCA.getAccountTypes();
            acetCA.getCancelReasons();
            acetCA.endCall();
            acetCA.renderCancelCaseSection();
        }
    }    
    private static void setTestData(String flow){
        
        RecordType newRecord = [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
        
        Account accountTest = new Account();
        accountTest.FirstName = 'Test';
        accountTest.LastName = 'Contact';
        accountTest.EID__c = 'PIN';
        accountTest.EID__pc = 'PIN';
        accountTest.RecordTypeId = newRecord.Id;
        insert accountTest;
        
        Account acc = [SELECT Id,personcontactid from Account where Id=:accountTest.Id];
        Contact con = [SELECT Id,LastName,FirstName,EID__c,AccountId from Contact where Id=:acc.personcontactid];
        if(flow == 'Provider'){
            Interaction__c inte = TestDataFactory.createInteraction();
            ApexPages.currentPage().getParameters().put('InteractionId',inte.id);
        }
        ApexPages.currentPage().getParameters().put('contactId',con.id);
        ApexPages.currentPage().getParameters().put('additionalInfo',TestDataFactory.createACETHighlightsPanelAdditionalInfo());    
    } 
}