src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Family_Story__c</fullName>
        <description>Use this space to share the family’s story, in the parent’s words. This allows advisors who are not assigned to the family to quickly get up to speed on the background of the family.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Background</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Associations_RichText__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Associations</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Overview__c.object
<CustomObject>
    <description>Family information for MEP.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account the Family Information is related to.</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Overview</relationshipLabel>
        <relationshipName>Family_Overview</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if the group has an Onshore Restriction.  If Yes then only Onshore agents can view the records.  If No then onshore and offshore agents can view the records</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Associations_RichText__c</fullName>
        <description>Consolidated list of program associations for all family members.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Associations</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Overview</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Overview</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SNIFamStatusControllerTest.cls
@isTest
public class SNIFamStatusControllerTest {

 @isTest static void SNIFamStatusControllerMethod() {
     account accFam = new account();
     string recTypeId = [select id from recordtype where name= 'Family'].id;
     accFam.recordtypeid = recTypeId;
     accFam.Name = 'FamilymemberTest11';
     insert accFam;
     boolean b = SNIFamStatusController.getAtccountDtl(accFam.id);
     boolean b1 = SNIFamStatusController.getAccountProgramAssociation(accFam.id);
     accFam.Family_Story__c = 'sample Family story';
     accFam.Program_Associations_RichText__c = 'sample Program Associations';
     update accFam;
     boolean b2 = SNIFamStatusController.getAtccountDtl(accFam.id);
     boolean b3 = SNIFamStatusController.getAccountProgramAssociation(accFam.id);
   //  select Onshore_Restriction__c,UHG_Restriction__c from Family_Overview__c where Account__c =: accId
     Family_Overview__c famOverV = new Family_Overview__c();
     famOverV.Onshore_Restriction__c = 'Yes';
     famOverV.UHG_Restriction__c = 'Yes';
     famOverV.Account__c = accFam.id;
     insert famOverV;
     boolean b4 = SNIFamStatusController.getRestrictionData(accFam.id); 
	 string tt = SNIFamStatusController.getAccountFamilyOverview(accFam.id);  //added by ravi

 }       
}