src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Designation__c</fullName>
        <description>Indicates whether this family will receive personalized support from you or another advisor going forward.</description>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>3rd Party/Sibling</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Researcher Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EHub_Update_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Update eligibility hub api. Based on this value, system calls service.</description>
        <label>Eligibility Hub Update Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Family_Needs__c</fullName>
        <description>Auto populated based on whether there are any open opportunities for any family member. This allows you to know which families you have open actions for, this should be updated when a family is determined to be inactive.</description>
        <label>Family Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <description>Tells if family has any open cases/opportunities.</description>
        <label>Family Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Overview__c.object
<CustomObject>
    <description>Family information for MEP.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account the Family Information is related to.</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Overview</relationshipLabel>
        <relationshipName>Family_Overview</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designation_Changed_Date__c</fullName>
        <description>Shows the designation changed date for a family for FEC Graduation purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Designation Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <description>How the family was added into MEP.</description>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Attempted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Worked</fullName>
                </value>
                <value>
                    <fullName>3rd Party/Sibling</fullName>
                    <isActive>false</isActive>
                    <label>3rd Party/Sibling</label>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                    <isActive>false</isActive>
                    <label>Opt Out</label>
                </value>
                <value>
                    <fullName>Researcher Added</fullName>
                    <isActive>false</isActive>
                    <label>Researcher Added</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EHub_Update_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created to track Updation on Eligibility Hub for Designation API</description>
        <label>Eligibility Hub Update Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Family_Needs__c</fullName>
        <description>The level of support (High, Moderate, Low) a family needs from SNI.</description>
        <label>Family Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <description>Indicates if family has any open cases.  Active &gt; open cases, Inactive = 0 open cases.</description>
        <label>Family Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Overview</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Overview</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/fo_validations__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Is_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Automation</label>
        <type>Checkbox</type>
    </fields>
    <label>fo_validations</label>
</CustomObject>

src/objects/Member_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Members Information</relationshipLabel>
        <relationshipName>Members_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EHub_Update_Check__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used in Update eligibility hub api. Based on this value, system calls service.</description>
        <label>Eligibility Hub Update Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of records</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Member Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ACETFamilyOverviewTriggerHelper.cls
public class ACETFamilyOverviewTriggerHelper {
    
    public static void beforeUpdate(Map<Id,Family_Overview__c> newmap,Map<Id,Family_Overview__c> oldMap){
        List<Id> familyAccId = new List<Id>();
        List<Id> personAccLst = new List<Id>();
        List<Account> familyActUpdate = new List<Account>();
        for(Family_Overview__c fo: newmap.values()){
             familyAccId.add(fo.Account__c);
            //Code Added for US2582440 -Start
            if(oldMap.get(fo.id).Designation__c!=fo.Designation__c){
                if(!Auth.CommunitiesUtil.isGuestUser()){
                fo.EHub_Update_Check__c=true;
                }
                RecursiveTriggerHandler.restrictOwnerChange=false;//Code added - US2556794
                fo.Designation_Changed_Date__c = Date.today();
            }//Code Addded for US2582440 -End
            //US3236600-Part 1-Start
            if(oldMap.get(fo.Id).Family_Needs__c != fo.Family_Needs__c || oldMap.get(fo.Id).Family_Status__c != fo.Family_Status__c){
                Account a = new Account();
                a.Id = fo.Account__c;
                    if(oldMap.get(fo.Id).Family_Needs__c != fo.Family_Needs__c){
                        a.Family_Needs__c = fo.Family_Needs__c;
                    }
                    if(oldMap.get(fo.Id).Family_Status__c != fo.Family_Status__c){
                        a.Family_Status__c = fo.Family_Status__c;
                    }
                familyActUpdate.add(a);
            }//US3236600-Part 1- End
        }
        //US3034530: SNI-Enhancement to Tasks to Update on Member Information
        /*Person Account for Member Information*/
        for(AccountContactRelation curAccConRel : [Select accountId,contactid,contact.accountId,account.UHG_Restriction__c from AccountContactRelation where accountId IN :familyAccId]){
            personAccLst.add(curAccConRel.contact.accountId);
        }
        /**Member Information of each Account**/
        List<Member_Information__c> memInfoLst =[Select Id from Member_Information__c where account__c in :personAccLst];
        List<task> activityList = [SELECT Id FROM Task where whatId in :memInfoLst AND Status != 'Completed' AND IsRecurrence != True];
        // End US3034530: SNI-Enhancement to Tasks to Update on Member Information	
        for(Family_Overview__c fo: newmap.values()){
            if(oldMap.get(fo.id).Designation__c == 'Assigned' && fo.Designation__c == 'Removed' && (fo.Family_Status__c == 'Active' || activityList.size()>0))
            {
                fo.adderror('Before you can choose this designation, Close all open Case(s), Support Request(s) and Task(s)');
            }
        }
        //US3236600-Part 2-Start
        if(familyActUpdate.size()>0){
            update familyActUpdate;
        }//US3236600-Part 2-End
    }
    
    public static void afterUpdate(Map<Id,Family_Overview__c> newmap,Map<Id,Family_Overview__c> oldMap){
        
        set<string> accIds = new set<string>();
        set<string> AssignedAccIds = new set<string>();
        for(Family_Overview__c fo: newmap.values()){
            if(oldmap.get(fo.id).Designation__c == 'Assigned' && fo.Designation__c == 'Removed' && fo.Family_Status__c == 'Inactive' ){
               accIds.add(fo.Account__c);
            }else{
                if((oldMap.get(fo.id).Designation__c!=fo.Designation__c) && (fo.Designation__c == 'Attempted' || fo.Designation__c == 'Worked')){
                    accIds.add(fo.Account__c);
                }else{
                    if((oldMap.get(fo.id).Designation__c!=fo.Designation__c) && fo.Designation__c == 'Assigned'){
                        AssignedAccIds.add(fo.Account__c);
                    }
                }
            }
        }
        if(accIds.size()>0){
            user u = [select id from user where name = 'Unassigned'];
            list<account> lstAc = new list<account>();
            for(account acc: [select id,ownerid from account where id IN : accIds]){
                acc.ownerid = u.id;
                lstAc.add(acc);
            }
            if(! lstAc.isEmpty()){
                update lstAc;
            }
        }
        Fo_validations__c famOverviewOverride = fo_validations__c.getOrgDefaults();
        if(AssignedAccIds.size()>0 && famOverviewOverride != null && famOverviewOverride.Is_Automation__c != true && !Auth.CommunitiesUtil.isGuestUser()){
            list<account> AccoList = new list<account>();
            for(account ac:[select id, ownerid from account where id in:AssignedAccIds]){
                ac.OwnerId = UserInfo.getUserId();
                AccoList.add(ac);
            }
            if(! AccoList.isEmpty()){
                update AccoList;
            }
        }
    }

}