src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Family_ID__c</fullName>
        <description>System generated family ID.</description>
        <displayFormat>F-{000000}</displayFormat>
        <label>Family ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Provider Affiliation</relationshipLabel>
        <relationshipName>Programs_Offered</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Provider User</fullName>
                </value>
                <value>
                    <fullName>Provider Team</fullName>
                </value>
                <value>
                    <fullName>Provider Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>It is used to capture the information of all the Programs offered by UHC. </description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Care_Team_Member__c.object
<CustomObject>
    <description>This Object is created for SNI Family Link Portal to save the care team members</description>
    <fields>
        <fullName>SNI_FL_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the family account related to care team member</description>
        <label>Family</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>SNI_FL_CareTeam_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field holds the person Account related to the care team member</description>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Care Team(Member)</relationshipLabel>
        <relationshipName>SNI_FL_CareTeam_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Status__c</fullName>
        <description>This hold the status of the care team member</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SNI FL Care Team Member</label>
    <nameField>
        <displayFormat>CT - {00000}</displayFormat>
        <label>CareTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Members_ROI__c.object
<CustomObject>
    <description>Release of information - visibility of data to family link</description>
    <fields>
        <fullName>SNI_FL_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Members ROIs</relationshipLabel>
        <relationshipName>Members_ROIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Id</label>
        <referenceTo>SNI_FL_Care_Team_Member__c</referenceTo>
        <relationshipLabel>Members ROIs</relationshipLabel>
        <relationshipName>Members_ROIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_ROI_Signed_With__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorized Member</label>
        <referenceTo>SNI_FL_Care_Team_Member__c</referenceTo>
        <relationshipLabel>Members ROIs (ROI Signed With)</relationshipLabel>
        <relationshipName>Members_ROIs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Members ROI</label>
    <nameField>
        <displayFormat>ROI-{0000}</displayFormat>
        <label>Members ROI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members ROIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Message__c.object
<CustomObject>
    <description>When a new Direct Message is initiated following data will be stored in the object 

1.FeedID (DirectMessag Feed ID)
2.Account ID (Family account ID)
3.Marked (Initially this will be false, This is using to show the red flag)</description>
    <fields>
        <fullName>Family_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Record ID of the family Account the Direct Message is linked</description>
        <label>Family ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages</relationshipLabel>
        <relationshipName>SNI_FL_Messages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feed_Id__c</fullName>
        <description>Record ID of the DirectMessageFeed object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Feed Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use to display red flag visible and hidden  in the messaging list UI</description>
        <label>Marked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages (Member)</relationshipLabel>
        <relationshipName>RTMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages (Program)</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SNI FL Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SNI FL Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SNI FL Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Message_Status__c.object
<CustomObject>
    <description>Stores information regarding whether user click the message or not. This object will store

1. Lookup to (SNI FL Message)
2. Lookup to Agent Object
3. IsRead ( To check whether user read or not)</description>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores related agent ID</description>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SNI_FL_Message_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link between SNI_FL_Message object</description>
        <label>SNI FL Message</label>
        <referenceTo>SNI_FL_Message__c</referenceTo>
        <relationshipLabel>SNI FL Message Statuses</relationshipLabel>
        <relationshipName>SNI_FL_Message_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SNI FL Message Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SNI FL  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SNI FL Message Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complex Care</fullName>
    </customValue>
    <customValue>
        <fullName>Rare Conditions</fullName>
    </customValue>
    <customValue>
        <fullName>Diagnostic Odyssey</fullName>
    </customValue>
    <masterLabel>Program</masterLabel>
</GlobalValueSet>

src/classes/SNI_FL_DirectMessageObjectQueryTest.cls
@IsTest(SeeAllData=true)
public class SNI_FL_DirectMessageObjectQueryTest {
    @isTest
    static void testCaseCommentNotification (){
        Id coRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Case Overview').getRecordTypeId();
        Id ecmRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('ECM').getRecordTypeId();
        Id familyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family').getRecordTypeId();
        Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        
        User u = [Select id from User where Profile.Name = 'System Administrator' and isActive = true and Id !=:userinfo.getUserId() limit 1];
        String userId = u.id;
        DirectMessageMember dsm=[SELECT DirectMessageId,MemberId FROM DirectMessageMember limit 1];
        
        system.runAs(u){
            
            Account ac = new Account();
            ac.Member_ID__c = '453543145';
            ac.Policy_ID__c = '0070145';
            ac.Name =   'Member1 Bourne Family';
            ac.RecordTypeId = familyRecordTypeId;
            ac.OwnerId=dsm.MemberId;
            insert ac;
            
            String accId = ac.id;
            
            Contact con= new Contact();
            con.firstname = 'test';
            con.lastname = 'test';
            con.AccountId = ac.id;
            insert con;
            
            Profile portal = [SELECT Id FROM Profile WHERE Name = 'Care Advisor Connect Provider User' LIMIT 1];  
            
            
            user u1 = new User( email='directmsgagent1@optum.acet.com',
                               profileid = portal.id, 
                               UserName='directmsgagent1@optum.acet.com', 
                               Alias = 'dtmsg1',
                               TimeZoneSidKey='America/New_York',
                               EmailEncodingKey='ISO-8859-1',
                               LocaleSidKey='en_US', 
                               LanguageLocaleKey='en_US',
                               ContactId=con.Id,
                               FirstName = 'Test Fname',
                               LastName = 'Test Lname');
            // insert u1;
            
            Account pa =new account();
            pa.PersonBirthdate = date.valueOf(ACETUtility.formatDateFutureDate('6/17/1979'));
            pa.firstName = 'Member1'; 
            pa.lastName = 'Bourne'; 
            pa.RecordTypeId = personAccRecordTypeId;
            pa.Policy_ID__c = '123456';
            insert pa;
            
            Account personAcc = [Select PersonContactId From Account Where Id = :pa.Id];
            AccountContactRelation acr = new AccountContactRelation();
            acr.ContactId = personAcc.PersonContactId;            
            acr.Accountid = ac.id;
            acr.Relationship__c = 'Child/Other';
            insert acr;
            
            SNI_FL_Care_Team_Member__c careTeamRecord1 = new SNI_FL_Care_Team_Member__c();
            careTeamRecord1.SNI_FL_Family__c = ac.id;
            careTeamRecord1.SNI_FL_Member__c = pa.id;
            careTeamRecord1.SNI_FL_Status__c    = 'Registered';
            insert careTeamRecord1;
            
            SNI_FL_Members_ROI__c memberROI1 = new SNI_FL_Members_ROI__c();
            memberROI1.SNI_FL_Member__c = careTeamRecord1.id;
            memberROI1.SNI_FL_ROI_Signed_With__c =careTeamRecord1.id;
            memberROI1.SNI_FL_Status__c = 'Active';
            memberROI1.SNI_FL_Account__c = pa.id;
            insert memberROI1;
            
            Case ecmCas = TestDataFactory.createCases(1)[0];
            ecmCas.RecordTypeId =ecmRecordTypeID;
            ecmCas.Topic__c = 'Appeals - Post Service';
            ecmCas.Type__c = 'Family Advisor';
            ecmCas.Subject_Group_ID__c = '123456';
            ecmCas.Case_Type__c = 'Opportunity';
            ecmCas.Status = 'Open';
            ecmCas.AccountId = pa.Id;
            ecmCas.Community__c = true;
            Insert ecmCas;
            
            List<CaseComment> caseComLst=new List<CaseComment>();
            CaseComment tComment = new CaseComment();
            tComment.CommentBody = 'Some Comment';
            tComment.ParentId = ecmCas.Id;
            tComment.IsPublished = true;
            insert tComment;
            caseComLst.add(tComment);
            
            List<SNI_FL_Message__c> FLmsgLst = new List<SNI_FL_Message__c>();
            SNI_FL_Message__c FLmsg = new SNI_FL_Message__c();
            FLmsg.Member_Id__c = ac.id;
            FLmsg.Program__c = String.ValueOf(ac.id);
            FLmsg.Feed_Id__c = '1234';
            FLmsg.Marked__c=true;
            FLmsg.Family_ID__c=ac.id;
            insert FLmsg;
            FLmsgLst.add(FLmsg);
            String flmsgId = FLmsg.id;
            
            SNI_FL_Message_Status__c msgSts = new SNI_FL_Message_Status__c();
            msgSts.SNI_FL_Message__c = FLmsg.id;
            msgSts.Agent__c = u.id;
            insert msgSts;
            
            
            
            
            
            DirectMessageFeed dsf= [select id,CreatedById,ParentId from DirectMessageFeed Limit 1];
            //insert dsf;
            FLmsg.Feed_Id__c=dsf.id;
            update FLmsg;
            
            Test.startTest();
            SNI_FLDirectMessageObjectQuery.insertCaseCommentNotification(caseComLst);
            SNI_FLDirectMessageObjectQuery.getUserProfilePermissionSet();
            SNI_FL_DirectMessageObjectQuery.retrieveDirectMessageList(true,ac.id,'test',1,1,true,true,False,'test',true,true);
            SNI_FL_DirectMessageObjectQuery.getDirectMessageIdFromFeed(FLmsgLst);
            SNI_FL_DirectMessageObjectQuery.getlstOfMessagesForFamilyAccount(ac.id,u.id,true);
            SNI_FL_DirectMessageObjectQuery.getlstOfMessagesForFamilyAccount(ac.id,u.id,false);
            SNI_FL_DirectMessageObjectQuery.getDirectMessagesId(false,accId,userId,true,false,true,'empty',true);
            SNI_FL_DirectMessageObjectQuery.getDirectMessagesId(false,accId,userId,true,true,true,'1234',true);
            SNI_FL_DirectMessageObjectQuery.getDirectMessagesId(false,accId,userId,true,false,true,flmsgId,true);
            SNI_FL_DirectMessageObjectQuery.getSuperAdminMessagesForFamilyMember(accId,userId,true,true,true);
            SNI_FL_DirectMessageObjectQuery.getSuperAdminMessagesForFamilyMember(accId,userId,false,true,true);
            SNI_FL_DirectMessageObjectQuery.getAllRelatedToMembers('test');
            SNI_FL_DirectMessageObjectQuery.markAsUnread('1234');
            SNI_FL_DirectMessageObjectQuery.advisorAffliationList();
            SNI_FL_DirectMessageObjectQuery.getDirectMessageIdForAgents(dsm.MemberId,true);
            SNI_FL_DirectMessageObjectQuery.getMapOfDirectMessageIDswithMembers(new list<id>{userId});
            SNI_FL_DirectMessageObjectQuery.getSortedDirstMsgList(userId,new list<DirectMessageFeed>{dsf},Null,True,True);
            SNI_FL_DirectMessageObjectQuery.getUserdetails(new list<DirectMessageFeed>{dsf});
            SNI_FL_DirectMessageObjectQuery.sortReadMsgListAndReturn(new list<DirectMessageFeed>{dsf},new list<DirectMessageFeed>{dsf});
            //SNI_FL_DirectMessageObjectQuery.getMemberIdOfProvider(pa.Id);
            try{
                SNI_FL_DirectMessageObjectQuery.getProviderFLMessagesRecord(Null,FLmsg,new list<SNI_FL_Message_Status__c>{msgSts});
            }catch (exception e){}
            Test.stopTest();
        }
    }
    @isTest
    static void testCaseCommentNotificationNegative (){
        Id coRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Case Overview').getRecordTypeId();
        Id ecmRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('ECM').getRecordTypeId();
        Id familyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family').getRecordTypeId();
        Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        
        User u = [Select id from User where Profile.Name = 'System Administrator' and isActive = true and Id !=:userinfo.getUserId() limit 1];
        system.runAs(u){
            Account ac = new Account();
            ac.Member_ID__c = '453543145';
            ac.Policy_ID__c = '0070145';
            ac.Name =   'Member1 Bourne Family';
            ac.RecordTypeId = familyRecordTypeId;
            insert ac;
            
            Contact con= new Contact();
            con.firstname = 'test';
            con.lastname = 'test';
            con.AccountId = ac.id;
            insert con;
            
            Account pa =new account();
            pa.PersonBirthdate = date.valueOf(ACETUtility.formatDateFutureDate('6/17/1979'));
            pa.firstName = 'Member1'; 
            pa.lastName = 'Bourne'; 
            pa.RecordTypeId = personAccRecordTypeId;
            pa.Policy_ID__c = '123456';
            insert pa;
            
            Account personAcc = [Select PersonContactId From Account Where Id = :pa.Id];
            AccountContactRelation acr = new AccountContactRelation();
            acr.ContactId = personAcc.PersonContactId;            
            acr.Accountid = ac.id;
            acr.Relationship__c = 'Child/Other';
            insert acr;
            
            
            Case ecmCas = TestDataFactory.createCases(1)[0];
            ecmCas.RecordTypeId =ecmRecordTypeID;
            ecmCas.Topic__c = 'Appeals - Post Service';
            ecmCas.Type__c = 'Family Advisor';
            ecmCas.Subject_Group_ID__c = '123456';
            ecmCas.Case_Type__c = 'Opportunity';
            ecmCas.Status = 'Open';
            ecmCas.AccountId = pa.Id;
            ecmCas.Community__c = true;
            Insert ecmCas;
            
            List<CaseComment> caseComLst=new List<CaseComment>();
            CaseComment tComment = new CaseComment();
            tComment.CommentBody = 'Some Comment';
            tComment.ParentId = ecmCas.Id;
            tComment.IsPublished = true;
            insert tComment;
            caseComLst.add(tComment);
            Test.startTest();
            SNI_FLDirectMessageObjectQuery.insertCaseCommentNotification(caseComLst);
            Test.stopTest();
        }
    }
    @isTest
    static void getCommentsFeedTest(){
        List<Account> lstFamilyAccount = SNI_FL_DirectMessageTestDataFactory.createAccountRecordsTestData('Family',1);
        lstFamilyAccount[0].Ownerid=Userinfo.getuserid();
        update lstFamilyAccount;
        
        List<SNI_FL_Message__c> FLmsgLst = new List<SNI_FL_Message__c>();
        SNI_FL_Message__c FLmsg = new SNI_FL_Message__c();
        FLmsg.Member_Id__c = lstFamilyAccount[0].id;
        FLmsg.Program__c = String.ValueOf(lstFamilyAccount[0].id);
        FLmsg.Feed_Id__c = '1234';
        insert FLmsg;
        
        SNI_FL_Message_Status__c msgSts = new SNI_FL_Message_Status__c();
        msgSts.SNI_FL_Message__c = FLmsg.id;
        msgSts.Agent__c = userinfo.getUserId();
        insert msgSts;
        
        //FLmsgLst.add(FLmsg);
        map<id,SNI_FL_Message__c> msg2= new map<id,SNI_FL_Message__c>();
        msg2.put(FLmsg.id,FLmsg);
        List<ID> ids = new List<ID>();
        profile p=[select Id from profile where Name='System Administrator'];
        DirectMessageFeed dsf=[select id from DirectMessageFeed limit 1];
        User u1;
        system.runAs(new user(Id = userinfo.getUserId())){
            u1 = new User( email='directmsgagent1@optum.acet.com',
                          profileid = p.id, 
                          UserName='directmsgagent1@optum.acet.com', 
                          Alias = 'dtmsg1',
                          TimeZoneSidKey='America/New_York',
                          EmailEncodingKey='ISO-8859-1',
                          LocaleSidKey='en_US', 
                          LanguageLocaleKey='en_US',
                          FirstName = 'Test Fname',
                          LastName = 'Test Lname');
            insert u1;
        }
        ids.add(u1.Id);
        SNI_FL_DirectMessageTestDataFactory.createDirectMessagesTestData(1,ids);
        List<DirectMessageFeed> lstDirectMsgFeed = [SELECT ID FROM DirectMessageFeed WHERE ParentId IN (SELECT ID FROM DirectMessage WHERE Subject LIKE 'DirectMsg_ACDC_Test') LIMIT 1];
        SNI_FLDirectMessageObjectQuery.getCommentsForFeed(lstDirectMsgFeed);
        SNI_FL_DirectMessageObjectQuery.SNI_FLMessage msgWrapper1 = new SNI_FL_DirectMessageObjectQuery.SNI_FLMessage('1234',true,true,'3458','pname',false,'mem123');
        SNI_FL_DirectMessageObjectQuery.SNI_FLMessage msgWrapper2 = new SNI_FL_DirectMessageObjectQuery.SNI_FLMessage(userinfo.getUserId(),'7829','fname',true,false,true,'mem123');
        SNI_FL_DirectMessageObjectQuery.RecordsData recordWrapper = new SNI_FL_DirectMessageObjectQuery.RecordsData('label','value');
        Date myDate = Date.newInstance( 2020, 10, 30 );
        Time myTime = Time.newInstance( 3, 3, 3, 0 );
        DateTime objDT = DateTime.newInstance( myDate, myTime );
        SNI_FL_DirectMessageObjectQuery.SNI_FLUserDetails usr = new SNI_FL_DirectMessageObjectQuery.SNI_FLUserDetails('fname','lname',userinfo.getUserId(),'System Administrator');
        User usr1 = new User(Id= userinfo.getUserId());
        SNI_FL_DirectMessageObjectQuery.SNI_FLDirectMessageFeed feedWrapper = new SNI_FL_DirectMessageObjectQuery.SNI_FLDirectMessageFeed(objDT,objDT,'body','1234',usr);
        SNI_FL_DirectMessageObjectQuery.SNI_FLDirectMessageWrapper dmWrapper = new SNI_FL_DirectMessageObjectQuery.SNI_FLDirectMessageWrapper(new list<SNI_FL_DirectMessageObjectQuery.SNI_FLUserDetails>{usr},'body',Null,Null,1,1,1,1,1);
        SNI_FL_DirectMessageObjectQuery.getDirectMessageIdForFamilyLink(new list<Id>{userinfo.getUserId()},true,'1231','3212',usr1);
        
        List<Id> lstUsers = new List<Id>();
        lstUsers.add(userinfo.getUserId());
        lstUsers.add(u1.Id);
        system.debug('lstUsers+ '+lstUsers);
        try{
            SNI_FL_DirectMessageObjectQuery.createFLMessageWrapper(msg2,dsf);
        }catch (exception e){}
        
        SNI_FL_DirectMessageTestDataFactory.createDirectMessagesTestData(1,lstUsers);
        
    }
}