src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <description>US2153934 - This check box is used for FamilyLink to send the email notifications to the users based on this indicator.</description>
        <label>Email Notification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Population__c</fullName>
        <label>Population</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Population</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Provider Affiliation</relationshipLabel>
        <relationshipName>Programs_Offered</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider User</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Provider User</fullName>
                </value>
                <value>
                    <fullName>Provider Team</fullName>
                </value>
                <value>
                    <fullName>Provider Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Member_Affiliation__c.object
<CustomObject>
    <description>Junction between program and member</description>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Affiliations</relationshipLabel>
        <relationshipName>Member_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Population__c</fullName>
        <label>Population</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Population</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Member Affiliations</relationshipLabel>
        <relationshipName>Member_Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Affiliation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Affiliation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Affiliation</relationshipLabel>
        <relationshipName>Provider_Affiliation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Group</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2)</booleanFilter>
            <filterItems>
                <field>Account.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Provider Group</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Affiliations (Provider Group)</relationshipLabel>
        <relationshipName>Provider_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Member Affiliation</relationshipLabel>
        <relationshipName>Provider</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Affiliation</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Member Affiliation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Affiliations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>It is used to capture the information of all the Programs offered by UHC. </description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Provider__c.object
<CustomObject>
    <description>Providers listed on transaction</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Provider</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Population.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Pediatric</fullName>
    </customValue>
    <customValue>
        <fullName>Adult/ Pediatric</fullName>
    </customValue>
    <masterLabel>Population</masterLabel>
</GlobalValueSet>

src/globalValueSets/Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complex Care</fullName>
    </customValue>
    <customValue>
        <fullName>Rare Conditions</fullName>
    </customValue>
    <customValue>
        <fullName>Diagnostic Odyssey</fullName>
    </customValue>
    <masterLabel>Program</masterLabel>
</GlobalValueSet>

src/classes/MemberAffiliationHandlerTest.cls
@isTest
public class MemberAffiliationHandlerTest {
    static testMethod void getData_NewMemberAffiliationMethod() {
        Id progrouprecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider Group').getRecordTypeId();
        Id proAffrecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider Affiliation').getRecordTypeId();
        Id proTeamrecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider Team').getRecordTypeId();
        Id proUserrecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Provider User').getRecordTypeId();
            List<Account> accList=new List<Account>();
            Account ac = new Account();
            ac.Name =   'ProviderGroup';
            ac.RecordTypeId = progrouprecordTypeId;
            accList.add(ac);
            Account acff = new Account();
            acff.Name =   'ProviderAffiliation';
            acff.RecordTypeId = proAffrecordTypeId;
            acff.parentId=ac.id;
            accList.add(acff);
            Account acteam = new Account();
            acteam.LastName =   'ProviderTeam';
            acteam.RecordTypeId = proTeamrecordTypeId;
            accList.add(acteam);
            Account acUser = new Account();
            acUser.LastName =   'ProviderUser';
            acUser.RecordTypeId = proUserrecordTypeId;
            acUser.Email_Notification__c =true;
            accList.add(acUser);
            insert accList;
        List<program__c> programList=new List<program__c>();
            Program__c pgm = new Program__c();
            pgm.Program__c = 'Complex Care';
            programList.add(pgm);
            insert programList;
        account acUser1 = [select id,personcontactid from account where id =: acUser.id];
        AccountContactRelation acrrec = new AccountContactRelation();
        acrrec.ContactId = acUser1.personcontactid;             
        acrrec.Accountid = acteam.id;
        acrrec.Relationship__c = 'Provider User';
        insert acrrec;
        account acteam1 = [select id,personcontactid from account where id =: acteam.id];
        AccountContactRelation acrrec1 = new AccountContactRelation();
        acrrec1.ContactId = acteam1.personcontactid;            
        acrrec1.Accountid = acff.id;
        acrrec1.Relationship__c = 'Provider Team';
        insert acrrec1;
        AccountContactRelation acrrec2 = new AccountContactRelation();
        acrrec2.ContactId = acUser1.personcontactid;             
        acrrec2.Accountid = acff.id;
        acrrec2.Relationship__c = 'Provider User';
        insert acrrec2;
        List<Contact> conId = [SELECT id from contact where accountId =: acUser.Id];
        List<Profile> pList = [SELECT Id FROM Profile WHERE Name =: 'Care Advisor Connect Provider User'];
        system.runAs(new User(Id = UserInfo.getUserId())){
            User u = new User(Alias = 'standt', Email='flCareTeamtest@testorg.com', 
                              EmailEncodingKey='UTF-8', FirstName='Test007',LastName='Testing', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = pList[0].id, contactId =conId[0].Id,
                              TimeZoneSidKey='America/Los_Angeles',MobilePhone='9000000001', UserName='flCareTeamtest@testorg.com',IsActive=true);
            insert u;
        }
       
        List<Member_Affiliation__c> mflst = new List<Member_Affiliation__c>();
        Member_Affiliation__c Maffiliate = new Member_Affiliation__c();
        //Maffiliate.Provider__c = ac.Id;
        Maffiliate.Population__c = 'Adult';
        Maffiliate.Program__c = pgm.Id;
        Maffiliate.Provider_group__c = ac.Id;
        Maffiliate.Provider_Affiliation__c = acff.Id;
        Maffiliate.Email__c='PersonEmail@gmail.com';
        Maffiliate.Enrollment_Date__c=system.today();
        Maffiliate.Date_Of_Birth__c = System.today();
        Maffiliate.Member__c=ac.Id;
        Maffiliate.Status__c=true; 
        mflst.add(Maffiliate);
        insert mflst;
        Test.startTest();
        try
         {
            MemberAffiliationTriggerHandler memcall = new MemberAffiliationTriggerHandler();
            memcall.Memberrecordsharing(mflst,null);
        }
        catch(exception e)
        {
        }    
        Test.stopTest();
    }

}