src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACETHippaCategoryRule__c.object
<CustomObject>
    <fields>
        <fullName>Caller_SubType__c</fullName>
        <label>Caller SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal Representative</fullName>
                </value>
                <value>
                    <fullName>Parent/Guardian/Custody Holder</fullName>
                </value>
                <value>
                    <fullName>Third Parties</fullName>
                </value>
                <value>
                    <fullName>Interpreter for member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <label>Caller Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult Dependent</fullName>
                </value>
                <value>
                    <fullName>Minor Dependent</fullName>
                </value>
                <value>
                    <fullName>Self Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>General__c</fullName>
        <defaultValue>false</defaultValue>
        <label>General</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Age__c</fullName>
        <defaultValue>200</defaultValue>
        <description>Enter 200 when Age is &quot;Not Applicable&quot;</description>
        <inlineHelpText>Enter 200 when Age is &quot;Not Applicable&quot;</inlineHelpText>
        <label>Maximum Age</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Medical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Min_Age__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter 0 when Age is &quot;Not Applicable&quot;</description>
        <inlineHelpText>Enter 0 when Age is &quot;Not Applicable&quot;</inlineHelpText>
        <label>Minimum Age</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <label>ACET Hippa Category Rule</label>
    <nameField>
        <displayFormat>Rule-{000}</displayFormat>
        <label>ACET Hippa Category Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACET Hippa Category Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant Controller</fullName>
                </value>
                <value>
                    <fullName>Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Member Note</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Primary Benefits Administrator</fullName>
                </value>
                <value>
                    <fullName>Primary Billing Administrator</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>UHC Employee</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETHipaaDisclosureTest.cls
@isTest
private class ACETHipaaDisclosureTest {

    static testMethod void myUnitTest() {
      setUpData();
        ACETHIPPADisclosureController ctrl = new ACETHIPPADisclosureController();
        ctrl.subDOB = '1954-01-28';
        ctrl.orgDOB = '1954-01-28';
        ctrl.InteractionId = createInteraction();
        ctrl.runHippaCategoryRules();
        
    }
    public static void setUpData(){
      ACETHippaCategoryRule__c  rule = new ACETHippaCategoryRule__c ();
      rule.Caller_SubType__c = null;
      rule.Caller_Type__c = 'Member';
      rule.General__c = true;
      rule.Max_Age__c = 200;
      rule.Medical__c = true;
      rule.Min_Age__c = 0;
      rule.Sensitive__c = true;
      rule.Dependent__c = 'Adult Dependent';
      insert rule;
    }
    public static String createInteraction(){
      RecordType newRecord = [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
        
        Account accountTest = new Account();
        accountTest.FirstName = 'Test';
        accountTest.LastName = 'Test';
        accountTest.EID__c = 'Test';
        accountTest.EID__pc = 'Test';
        accountTest.RecordTypeId = newRecord.Id;
        insert accountTest;

    Account acc = [SELECT Id,personcontactid from Account where Id=:accountTest.Id];
        Contact con = [SELECT Id,LastName,FirstName,EID__c,AccountId from Contact where Id=:acc.personcontactid];
        con.Tax_ID__c = 'Test';
        con.NPI__c = 'Test';
      Interaction__c intraction = ACETTestDataUtility.createInteraction(con.Id, 'Test', 'Member','Test');
      insert intraction;
      return intraction.Id;
    }
}