src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Designation__c</fullName>
        <description>Indicates whether this family will receive personalized support from you or another advisor going forward.</description>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                    <default>true</default>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>3rd Party/Sibling</fullName>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                </value>
                <value>
                    <fullName>Researcher Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Family_Needs__c</fullName>
        <description>Auto populated based on whether there are any open opportunities for any family member. This allows you to know which families you have open actions for, this should be updated when a family is determined to be inactive.</description>
        <label>Family Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <description>Tells if family has any open cases/opportunities.</description>
        <label>Family Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Overview__c.object
<CustomObject>
    <description>Family information for MEP.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account the Family Information is related to.</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Overview</relationshipLabel>
        <relationshipName>Family_Overview</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Designation_Changed_Date__c</fullName>
        <description>Shows the designation changed date for a family for FEC Graduation purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Designation Changed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Designation__c</fullName>
        <description>How the family was added into MEP.</description>
        <label>Designation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Attempted</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Worked</fullName>
                </value>
                <value>
                    <fullName>3rd Party/Sibling</fullName>
                    <isActive>false</isActive>
                    <label>3rd Party/Sibling</label>
                </value>
                <value>
                    <fullName>Opt Out</fullName>
                    <isActive>false</isActive>
                    <label>Opt Out</label>
                </value>
                <value>
                    <fullName>Researcher Added</fullName>
                    <isActive>false</isActive>
                    <label>Researcher Added</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <label>Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Needs__c</fullName>
        <description>The level of support (High, Moderate, Low) a family needs from SNI.</description>
        <label>Family Needs</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <description>Indicates if family has any open cases.  Active &gt; open cases, Inactive = 0 open cases.</description>
        <label>Family Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <default>true</default>
                    <label>Inactive</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Active_Date__c</fullName>
        <description>Shows the last active date for a family for FEC Graduation purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Active Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if the group has an Onshore Restriction.  If Yes then only Onshore agents can view the records.  If No then onshore and offshore agents can view the records</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Overview</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Overview</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <description>Used for API extracting to avoid multiple extracts and vlookups to obtain name value versus ID</description>
        <formula>Case(
Profile.Name , 
&quot;PT1&quot;, &quot;System Administrator&quot;,
&quot;PT2&quot;, &quot;Standard User&quot;,
Profile.Name
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Profile Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <description>Since data loader extract only contains 18digit ID; this is used to provide name value for time saving efforts.</description>
        <formula>UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Since data loader extract only contains 18digit ID; this is used to provide name value for time saving efforts.</inlineHelpText>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SNI_FECGraduationEHUBBatchTest.cls
@isTest
public class SNI_FECGraduationEHUBBatchTest {
    @TestSetup
    static void setup(){
        User oUser = [select id,contactid, Name,Profile_Name__c,ProfileId,Role_Name__c FROM User Where id =: userInfo.getUserId()];
        List<Account> familyList = TestDataFactory.createBulkAccounts();
        List<Account> personList = new List<Account>();
        List<Family_Overview__c> familyOverviewList = new List<Family_Overview__c>();
        String familyRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family').getRecordTypeId();
        String personRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Integer idKey = 1;
        for(Account a :familyList){
            a.RecordTypeId = familyRecordType;
            a.Member_Id__c = '1231234567'+String.valueOf(idKey);
            a.OwnerId = oUser.Id;
            Family_Overview__c fam=new Family_Overview__c();
            fam.Account__c=a.Id;
            if(idKey == 1){
                fam.Designation__c = 'Assigned';
                fam.Family_Status__c = 'Inactive';
                fam.Last_Active_Date__c = (Date.today() - 385);
            } else if(idKey == 2){
                fam.Designation__c = 'Assigned';
                fam.Family_Status__c = 'Inactive';
                fam.Last_Active_Date__c = (Date.today() - 200);
            } else if(idKey == 3){
                fam.Designation__c = 'Deferred';
                fam.Designation_Changed_Date__c = (Date.today() - 200);
                fam.Last_Active_Date__c = (Date.today() - 200);
                
            } else if(idKey == 4){
                fam.Designation__c = 'Deferred';
                fam.Designation_Changed_Date__c = (Date.today() - 100);
                fam.Last_Active_Date__c = (Date.today() - 100);
            } else {
                fam.Family_Status__c='Active';
            }
            fam.Exception__c = 'No';
            fam.Family_Needs__c='Low';
            fam.UHG_Restriction__c='No';
            fam.Onshore_Restriction__c='No';
            familyOverviewList.add(fam);
            idKey++;
        }
        update familyList;
        insert familyOverviewList;
        for(integer i = 0; i<10; i++){
            Account accountTest = new Account();
            accountTest.FirstName = 'Luke';
            accountTest.LastName = 'Testwalker'+String.valueOf(i);
            accountTest.EID__c = 'lukeTestwalker'+String.valueOf(i)+'@testEmail.com';
            accountTest.RecordTypeId = personRecordType;
            personList.add(accountTest);
        }
        insert personList;
    }
    public testmethod static void testBatchOpenCases(){
        List<Id> famOverIdListToUpdate = new List<Id>(new Map<Id,Family_Overview__c>([Select Id from Family_Overview__c]).keySet());
        Test.startTest();
        SNI_FECGraduationEHUBBatch myBatchObject = new SNI_FECGraduationEHUBBatch(famOverIdListToUpdate);
        Database.executeBatch(myBatchObject);        
        Test.stopTest();   
    }
}