src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Par_Provider__c</fullName>
        <label>Par Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Contact_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Contact_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Contact_Preference__c</fullName>
        <label>Provider Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIR_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PIR Details</relationshipLabel>
        <relationshipName>PIR_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exact_Count_Unknown_Multiple_Claims__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exact Count Unknown; Multiple Claims</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_Reference_Facilitated_Referral__c</fullName>
        <defaultValue>false</defaultValue>
        <label>No Reference #; Facilitated Referral</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PC_External_Contact_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Par_Provider__c</fullName>
        <label>Par Provider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AARP Supplement</fullName>
                </value>
                <value>
                    <fullName>Charter</fullName>
                </value>
                <value>
                    <fullName>CHIP</fullName>
                </value>
                <value>
                    <fullName>Choice/Choice Plus</fullName>
                </value>
                <value>
                    <fullName>CIP/XL Health</fullName>
                </value>
                <value>
                    <fullName>Compass</fullName>
                </value>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>CRS</fullName>
                </value>
                <value>
                    <fullName>DSNP</fullName>
                </value>
                <value>
                    <fullName>Dual Medicaid and Medicare</fullName>
                </value>
                <value>
                    <fullName>Empire</fullName>
                </value>
                <value>
                    <fullName>Golden Rule</fullName>
                </value>
                <value>
                    <fullName>HARF</fullName>
                </value>
                <value>
                    <fullName>Harvard Pilgrim</fullName>
                </value>
                <value>
                    <fullName>HCBS</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>LTC</fullName>
                </value>
                <value>
                    <fullName>MAHP</fullName>
                </value>
                <value>
                    <fullName>Medica</fullName>
                </value>
                <value>
                    <fullName>Medicaid</fullName>
                </value>
                <value>
                    <fullName>Medicare Advantage</fullName>
                </value>
                <value>
                    <fullName>Medicare NPPO</fullName>
                </value>
                <value>
                    <fullName>Navigate</fullName>
                </value>
                <value>
                    <fullName>NHP</fullName>
                </value>
                <value>
                    <fullName>Oxford</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
                <value>
                    <fullName>Railroad</fullName>
                </value>
                <value>
                    <fullName>River Valley</fullName>
                </value>
                <value>
                    <fullName>Select/Select Plus</fullName>
                </value>
                <value>
                    <fullName>Sierra Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Contact_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Provider_Contact_Preference__c</fullName>
        <label>Provider Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Submission_Delay__c</fullName>
        <label>Reason for Submission Delay</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitter PTO/Weekend/Holiday</fullName>
                </value>
                <value>
                    <fullName>Additional submitter research/review</fullName>
                </value>
                <value>
                    <fullName>Analyst on PTO, incorrectly routed</fullName>
                </value>
                <value>
                    <fullName>CARCE Team</fullName>
                </value>
                <value>
                    <fullName>Case Cloned Incorrectly</fullName>
                </value>
                <value>
                    <fullName>Held for additional information</fullName>
                </value>
                <value>
                    <fullName>Issue from a previous case</fullName>
                </value>
                <value>
                    <fullName>Submitter Backlog</fullName>
                </value>
                <value>
                    <fullName>Routed to incorrect LOB in error</fullName>
                </value>
                <value>
                    <fullName>Split Case</fullName>
                </value>
                <value>
                    <fullName>Submitter System issues</fullName>
                </value>
                <value>
                    <fullName>Triage Backlog</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PIR Detail</label>
    <nameField>
        <displayFormat>PIR-{000000}</displayFormat>
        <label>PIR Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Details</pluralLabel>
    <recordTypes>
        <fullName>Proactive_Action_Partner</fullName>
        <active>true</active>
        <label>Proactive Action Partner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reactive_Resolution_Partners</fullName>
        <active>true</active>
        <label>Reactive Resolution Partners</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_InteractionCtrl.cls
public with sharing class ACET_FAST_InteractionCtrl {
    
    @AuraEnabled
    public static InteractionWrapper getInteractionWrapper(string personAccId,string interactRecordId, string caseRecordType){
        ACET_FAST_InteractionCtrl.InteractionWrapper interWrapper = new ACET_FAST_InteractionCtrl.InteractionWrapper();
        interWrapper.personAccount= [SELECT id, Name,Par_Provider__c, Provider_Contact__c, Provider_Contact_Email__c, 
                                     Provider_Contact_Phone__c, Provider_Contact_Preference__c, Tax_Id__c, EID__c FROM Account 
                                     WHERE id=:personAccId];
        interWrapper.selectedRecordTypeName=caseRecordType;
        interWrapper.caseRec.Interaction__c = interactRecordId;
        string caseRectypeDevName = ACET_FAST_Constants.caseRcTypNameRcTypDevNameMap.get(caseRecordType);
        interWrapper.caseRec.RecordTypeId = ACET_FAST_InteractionCtrl.getRecordTypeIdbyDevName('Case',caseRectypeDevName);
        interWrapper.caseRec.PC_Provider_TIN__c=interWrapper.personAccount.Tax_Id__c;
        interWrapper.availableMarketList.addAll(ACET_FAST_Utility.getPiklistValues('Case','FAST_PIP_Markets__c'));
        interWrapper.availableProductList.addAll(ACET_FAST_Utility.getPiklistValues('PIR_Detail__c','Products__c'));
        system.debug('Available products-->'+ interWrapper.availableProductList);
        if(caseRecordType=='Reactive Resolution'){
            interWrapper.caseRec.AccountId=interWrapper.personAccount.id;
            interWrapper.caseRec.Case_Type__c = 'Reactive Resolution';
            interWrapper.caseRec.PC_Is_There_Active_PRs__c = interWrapper.personAccount.Par_Provider__c;
            interWrapper.caseRec.Provider_Contact_Preference__c = interWrapper.personAccount.Provider_Contact_Preference__c;
            interWrapper.caseRec.PC_External_Contact_Name__c = interWrapper.personAccount.Provider_Contact__c;
            interWrapper.caseRec.PC_External_Contact_Email__c = interWrapper.personAccount.Provider_Contact_Email__c;
             interWrapper.caseRec.PC_External_Contact_Phone__c = interWrapper.personAccount.Provider_Contact_Phone__c;
            interWrapper.caseOriginList = ACET_FAST_Constants.caseOriginList;
            interWrapper.topicList = ACET_FAST_Constants.caseTopicList;
            interWrapper.sumissionDelayReasonList.addAll(ACET_FAST_Utility.getPiklistValues('PIR_Detail__c','Reason_for_Submission_Delay__c'));
            interWrapper.pirDetailRecord.RecordTypeID = ACET_FAST_InteractionCtrl.getRecordTypeIdbyDevName('PIR_Detail__c','Reactive_Resolution_Partners');
            interWrapper.pirDetailRecord.No_Reference_Facilitated_Referral__c=true;
            interWrapper.pirDetailRecord.Exact_Count_Unknown_Multiple_Claims__c=true;
            interWrapper.pirDetailRecord.Provider_Contact__c = interWrapper.personAccount.Provider_Contact__c;
            interWrapper.pirDetailRecord.Provider_Contact_Preference__c = interWrapper.personAccount.Provider_Contact_Preference__c;
            interWrapper.pirDetailRecord.Provider_Contact_Phone__c = interWrapper.personAccount.Provider_Contact_Phone__c;
            interWrapper.pirDetailRecord.PC_External_Contact_Email__c = interWrapper.personAccount.Provider_Contact_Email__c;
            interWrapper.pirDetailRecord.Par_Provider__c = interWrapper.personAccount.Par_Provider__c;
        }else{
            interWrapper.caseRec.Case_Type__c = 'Proactive Action';
            interWrapper.spTeamList = ACET_FAST_Constants.caseSpecialtyList;
            interWrapper.topicList = ACET_FAST_Constants.caseTopicList;
            interWrapper.pirDetailRecord.RecordTypeID = ACET_FAST_InteractionCtrl.getRecordTypeIdbyDevName('PIR_Detail__c','Proactive_Action_Partner');
        }
        return interWrapper;
    }
    @AuraEnabled
    public static ACET_FAST_InteractionCtrl.CaseResultWrapper finalSubmit(string wrapperJSON){
        InteractionWrapper intWrapVar = (InteractionWrapper)JSON.deserialize(wrapperJSON, InteractionWrapper.class);
        System.debug(intWrapVar);
        intWrapVar.caseRec.FAST_PIP_Markets__c=ACET_FAST_InteractionCtrl.convertMultipickList(intWrapVar.selectedMarketList);
        intWrapVar.pirDetailRecord.Products__c=ACET_FAST_InteractionCtrl.convertMultipickList(intWrapVar.selectedProductList);
        ACET_FAST_InteractionCtrl.CaseResultWrapper finalResult = new  ACET_FAST_InteractionCtrl.CaseResultWrapper();
        try{
            insert intWrapVar.caseRec;
            intWrapVar.pirDetailRecord.Case__c=intWrapVar.caseRec.id;
            insert intWrapVar.pirDetailRecord;
            case insertedCaseRec = new case();
            insertedCaseRec = [SELECT id, CaseNumber FROM Case Where id=:intWrapVar.caseRec.id];
            finalResult.caseRecordId = insertedCaseRec.id;
            finalResult.result = 'SUCCESS';
            finalResult.errorMessage='Case '+insertedCaseRec.CaseNumber+' Created Successfully';
        }
        catch(exception ex){
            system.debug('exception'+ex.getMessage());
            finalResult.caseRecordId = '';
            finalResult.result = 'ERROR';
            finalResult.errorMessage=ex.getMessage();
        }
        return finalResult;
    }
    private static string convertMultipickList(List<String> strList){
        system.debug('strList==>'+strList);
        string str='';
        for(string s:strList){
            if(str==''){
                str= s; 
            }else{
                str=str+';'+s;
            }
        }
        system.debug('str==>'+str);
        return str;
    }
    public static Id getRecordTypeIdbyDevName(String objectName, String strRecordTypeDevName){
        return  Schema.getGlobalDescribe().get(objectName).getDescribe().getRecordTypeInfosByDeveloperName().get(strRecordTypeDevName).getRecordTypeId();
    }
    public class InteractionWrapper{
        @AuraEnabled
        public Account personAccount{get;set;}
        @AuraEnabled
        public Case caseRec{get;set;}
        @AuraEnabled
        public PIR_Detail__c pirDetailRecord{get;set;}
        @AuraEnabled
        public String selectedRecordTypeName{get;set;}
        @AuraEnabled
        public List<string> availableMarketList{get;set;}
        @AuraEnabled
        public List<string> selectedMarketList{get;set;}
		@AuraEnabled
        public List<string> availableProductList{get;set;}
        @AuraEnabled
        public List<string> selectedProductList{get;set;}
        @AuraEnabled
        public List<string> caseOriginList{get;set;}
        @AuraEnabled
        public List<string> topicList{get;set;}
        @AuraEnabled
        public List<String> typeList{get;set;}
        @AuraEnabled
        public List<String> subTypeList{get;set;}
        @AuraEnabled
        public List<String> spTeamList{get;set;}
        @AuraEnabled
        public List<String> sumissionDelayReasonList{get;set;}
        public InteractionWrapper(){
            personAccount = new Account();
            caseRec = new case();
            pirDetailRecord = new PIR_Detail__c();
            selectedRecordTypeName='';
            availableMarketList= new List<string>();
            selectedMarketList= new List<string>();
            availableProductList = new List<string>();
            selectedProductList = new List<string>();
            caseOriginList = new List<string>();
            topicList = new List<string>();
            typeList = new List<String>();
            subTypeList = new List<String>();
            sumissionDelayReasonList = new List<String>();
            spTeamList = new List<String>();
        }
    }
    public class CaseResultWrapper{
        @AuraEnabled
        public string caseRecordId{get;set;}
        @AuraEnabled
        public string result{get;set;}
        @AuraEnabled
        public string errorMessage{get;set;}
    }
}