src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Id_ANI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Caller Phone Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant Controller</fullName>
                </value>
                <value>
                    <fullName>Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Member Note</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Primary Benefits Administrator</fullName>
                </value>
                <value>
                    <fullName>Primary Billing Administrator</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>UHC Employee</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Claim_Authorization_Referral_Number__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Claim/Authorization/Referral  Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>This field stores Group ID when originator is Producer/Group, and subject is Member.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Group ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <description>Interaction Type, as captured on the Explore page.</description>
        <label>Interaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Proactive Initiative</fullName>
                </value>
                <value>
                    <fullName>Walk-In</fullName>
                </value>
                <value>
                    <fullName>Inbound Correspondence</fullName>
                </value>
                <value>
                    <fullName>Research Only</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>SRS Resource Inquiry</fullName>
                </value>
                <value>
                    <fullName>SRS Escalated Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Member ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Originator Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Group/Employer</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>UHG</fullName>
                </value>
                <value>
                    <fullName>Internal UHG Employee</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Agency/Broker</fullName>
                </value>
                <value>
                    <fullName>Group Contact</fullName>
                </value>
                <value>
                    <fullName>Other Originator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TFN_Toll_Free_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TFN (Toll Free Number)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Interactions (Third Party)</relationshipLabel>
        <relationshipName>Interactions1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>First Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Name</label>
        <length>121</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name for 80</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Last Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Third Party</label>
    <nameField>
        <displayFormat>TP #-{0000000000}</displayFormat>
        <label>Third Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VCCD_Response__c.object
<CustomObject>
    <description>The Purpose of this object is to store incoming VCCD Request Details</description>
    <fields>
        <fullName>Ani__c</fullName>
        <description>The Purpose of this field is to Capture Contact Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Ani</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Caller Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ClaimId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimsDOSMD__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ClaimsDOSMD</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MSID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>MSID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>MemberId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NPI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ProductType</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionTypeTopic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>QuestionType Topic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>QuestionType</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubjectDOB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SubjectDOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TFN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TFN</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TaxId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ucid__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Ucid</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>lastName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>lastName</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>VCCD Response</label>
    <nameField>
        <displayFormat>VCCD-{0000000000}</displayFormat>
        <label>VCCD Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VCCD Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_InteractionOverviewCtrl.cls
public without sharing class ACET_InteractionOverviewCtrl {

    @AuraEnabled
    public static Interaction__c createInteraction(ACET_ExplorePageCtrl.FlowDetails flowDetails,
                                                   ACET_ProviderSearchCtrl.ProviderDetails providerDetails,
                                                   ACET_MemberSearchCtrl.ExplorePageMemberDetailsResponse memberResponseData,
                                                  Boolean isVCCD,
                                                  String VCCDRecordId) {
        try {
            System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: flowDetails: ' + flowDetails);
            System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: providerDetails: ' + providerDetails);
            System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: memberResponseData: ' + memberResponseData);
            Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
            Account memberAccount;
            Account providerAccount;
            Third_Party__c thirdParty = new Third_Party__c();
            Interaction__c interaction = new Interaction__c();
            String memberDOBWithSlash;
            if (memberResponseData != null) {
                memberDOBWithSlash = memberResponseData.dob.contains('-') ? SAEUtils.formatDate(memberResponseData.dob) : memberResponseData.dob;
            }
            if (providerDetails.isNoProviderToSearch) {
                if (memberResponseData.isValidMember) {
                    interaction = new Interaction__c(
                        Originator_Name__c = memberResponseData.firstName + ' ' + memberResponseData.lastName,
                        Originator_Type__c = 'Member',
                        Interaction_Type__c = flowDetails.interactionType
                    );
                    memberAccount = new Account(
                        RecordTypeId = personAccountRecordTypeId,
                        FirstName = memberResponseData.firstName,
                        LastName = memberResponseData.lastName,
                        EID__c = memberResponseData.firstName + ' ' + memberResponseData.lastName + ' ' + memberDOBWithSlash.remove('/') + ' ' + memberResponseData.memberId + ' ' + memberResponseData.groupNumber,
                        PersonBirthdate = Date.parse(memberDOBWithSlash),
                        Phone = memberResponseData.phoneNumber
                    );
                    Database.upsert(memberAccount, Account.Fields.EID__c);
                    System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: memberAccount: ' + memberAccount);
                    interaction.Originator__c = getPersonContactId(memberAccount.Id);
                } else if (memberResponseData != null && memberResponseData.isMemberNotFound) {
                    thirdParty = new Third_Party__c(
                        FullName__c = memberResponseData.firstName + ' ' + memberResponseData.lastName,
                        First_Name__c = memberResponseData.firstName,
                        LastName__c = memberResponseData.lastName,
                        DOB__c = Date.parse(memberDOBWithSlash),
                        Phone_Number__c = memberResponseData.phoneNumber
                    );
                    Database.upsert(thirdParty);
                    interaction.Third_Party__c = thirdParty.Id;
                    //US3172545 - No Provider to Search to MNF - Sravan - Start
                    interaction.Interaction_Type__c = flowDetails.interactionType;
                    //US3172545 - No Provider to Search to MNF - Sravan - End
                    if(string.isBlank(interaction.Originator_Type__c)) interaction.Originator_Type__c = 'Member';
                }
            } else if (providerDetails.isValidProvider) {
                providerAccount = new Account(
                    RecordTypeId = personAccountRecordTypeId,
                    FirstName = providerDetails.firstName,
                    LastName = providerDetails.lastName,
                    EID__c = providerDetails.providerId,
                    Tax_Id__c = providerDetails.taxId,
                    Phone = providerDetails.phoneNumber
                );
                Database.upsert(providerAccount, Account.Fields.EID__c);
                interaction = new Interaction__c(
                    Originator__c = getPersonContactId(providerAccount.Id),
                    Originator_Name__c = providerDetails.firstName + ' ' + providerAccount.lastName,
                    Originator_Type__c = 'Provider',
                    Interaction_Type__c = flowDetails.interactionType
                );
                /* if (memberResponseData.isValidMember) {
                    providerAccount = new Account(
                    RecordTypeId = personAccountRecordTypeId,
                    FirstName = memberResponseData.firstName,
                    LastName = memberResponseData.lastName,
                    EID__c = memberResponseData.firstName + ' ' + memberResponseData.lastName + ' ' + memberDOBWithSlash.remove('/') + ' ' + memberResponseData.memberId + ' ' + memberResponseData.groupNumber,
                    PersonBirthdate = Date.parse(memberDOBWithSlash),
                    Phone = memberResponseData.phoneNumber
                    );
                    Database.upsert(providerAccount, Account.Fields.EID__c);
                    System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: valid provider and member: providerAccount: ' + providerAccount);

                } else */
                if (memberResponseData != null && memberResponseData.isMemberNotFound) {
                    thirdParty = new Third_Party__c(
                        FullName__c = memberResponseData.firstName + ' ' + memberResponseData.lastName,
                        First_Name__c = memberResponseData.firstName,
                        LastName__c = memberResponseData.lastName,
                        DOB__c = Date.parse(memberDOBWithSlash),
                        Phone_Number__c = memberResponseData.phoneNumber
                    );
                    Database.upsert(thirdParty);
                    interaction.Third_Party__c = thirdParty.Id;
                }
            } else if (providerDetails.isProviderNotFound) {
                thirdParty = new Third_Party__c(
                    FullName__c = providerDetails.firstName + ' ' + providerDetails.lastName,
                    First_Name__c = providerDetails.firstName,
                    LastName__c = providerDetails.lastName,
                    Phone_Number__c = providerDetails.phoneNumber
                );
                Database.upsert(thirdParty);
                interaction = new Interaction__c(
                    Third_Party__c = thirdParty.Id,
                    Originator_Name__c = providerDetails.firstName + ' ' + providerDetails.lastName,
                    Originator_Type__c = 'Provider',
                    Interaction_Type__c = flowDetails.interactionType
                );
            } else if (providerDetails.isOther) {
				//DE356886 added by vinay
                List<String> orginatorName = new List<String>();
                String firstName,lastName;
                if(String.isNotBlank(flowDetails.contactName)){
                    orginatorName = flowDetails.contactName.split(' ');
                    if(orginatorName.size() > 0){
                        firstName = orginatorName[0];
                        lastName = orginatorName[1];
                    }
                }
                thirdParty = new Third_Party__c(
                    FullName__c = flowDetails.contactName,
					First_Name__c = firstName, 
                    LastName__c = lastName,
                    Phone_Number__c = flowDetails.contactNumber
                );
                Database.upsert(thirdParty);
                interaction = new Interaction__c(
                    Third_Party__c = thirdParty.Id,
                    Originator_Name__c = flowDetails.contactName,
                    Originator_Type__c = 'Other',
                    Interaction_Type__c = flowDetails.interactionType
                );
            }

            interaction = transformationVCCD(interaction,isVCCD,VCCDRecordId,flowDetails);//US2903847
            Database.insert(interaction);
            System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: interaction: ' + interaction);
            Interaction__c interactionRecord = [SELECT Id, Name, Originator__c FROM Interaction__c WHERE Id =: interaction.Id];
            System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: interactionRecord: ' + interactionRecord);
            return interactionRecord;
        } catch (exception e) {
            system.debug('exception::' + e.getStackTraceString());
            return null;
        }

    }

    @AuraEnabled
    public static Interaction__c updateInteraction(ACET_ExplorePageCtrl.FlowDetails flowDetails,
                                                   ACET_ProviderSearchCtrl.ProviderDetails providerDetails,
                                                   String interactionId,
                                                          Boolean isVCCD,
                                                  String VCCDRecordId) {
        System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: interactionId: ' + flowDetails);
        System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: interactionId: ' + providerDetails);
        System.debug('@@ ACET_InteractionOverviewCtrl: createInteraction: interactionId: ' + interactionId);
        Id personAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        Account providerAccount;
        Third_Party__c thirdParty = new Third_Party__c();
        Interaction__c interaction;
        if (providerDetails.isValidProvider) {
            providerAccount = new Account(
                RecordTypeId = personAccountRecordTypeId,
                FirstName = providerDetails.firstName,
                LastName = providerDetails.lastName,
                EID__c = providerDetails.providerId,
                Tax_Id__c = providerDetails.taxId,
                Phone = providerDetails.phoneNumber
            );
            Database.upsert(providerAccount, Account.Fields.EID__c);
            interaction = new Interaction__c(
                Originator__c = getPersonContactId(providerAccount.Id),
                Originator_Name__c = providerDetails.firstName + ' ' + providerAccount.lastName,
                Originator_Type__c = 'Provider',
                Interaction_Type__c = flowDetails.interactionType
            );
        } else if (providerDetails.isProviderNotFound) {
            thirdParty = new Third_Party__c(
                FullName__c = providerDetails.firstName + ' ' + providerDetails.lastName,
                First_Name__c = providerDetails.firstName,
                LastName__c = providerDetails.lastName,
                Phone_Number__c = providerDetails.phoneNumber
            );
            Database.upsert(thirdParty);
            interaction = new Interaction__c(
                Third_Party__c = thirdParty.Id,
                Originator_Name__c = providerDetails.firstName + ' ' + providerDetails.lastName,
                Originator_Type__c = 'Provider',
                Interaction_Type__c = flowDetails.interactionType
            );
        } else if (providerDetails.isOther) {
			//DE356886 added by vinay
                List<String> orginatorName = new List<String>();
                String firstName,lastName;
                if(String.isNotBlank(flowDetails.contactName)){
                    orginatorName = flowDetails.contactName.split(' ');
                    if(orginatorName.size() > 0){
                        firstName = orginatorName[0];
                        lastName = orginatorName[1];
                    }
                }
            thirdParty = new Third_Party__c(
                FullName__c = flowDetails.contactName,
				First_Name__c = firstName,
                LastName__c = lastName,
                Phone_Number__c = flowDetails.contactNumber
            );
            Database.upsert(thirdParty);
            interaction = new Interaction__c(
                Third_Party__c = thirdParty.Id,
                Originator_Name__c = flowDetails.contactName,
                Originator_Type__c = 'Other',
                Interaction_Type__c = flowDetails.interactionType
            );
        }
        if (!providerDetails.isNoProviderToSearch) {
            interaction.Id = interactionId;
            interaction = transformationVCCD(interaction,isVCCD,VCCDRecordId,flowDetails);//US2903847
            Database.update(interaction);
        }
        interaction = [SELECT Id, Name, Originator__c FROM Interaction__c WHERE Id =: interactionId];
        System.debug('@@ ACET_InteractionOverviewCtrl: updateInteraction: interaction: ' + interaction);
        return interaction;
    }

    //US2903847
    public static Interaction__c transformationVCCD(Interaction__c intRecord,Boolean isVCCD, string VCCDRecordId,ACET_ExplorePageCtrl.FlowDetails flowDetails){
         //US2631703 - Durga- 08th June 2020
         Interaction__c interaction = intRecord;
        //US2903847 -START
        if(isVCCD && string.isNotBlank(VCCDRecordId)){
                List<VCCD_Response__c> VCCDRecord = [SELECT Id,Ani__c, ClaimId__c, ClaimsDOSMD__c, MemberId__c, MSID__c, NPI__c, ProductType__c, QuestionType__c, SubjectDOB__c,
                QuestionTypeTopic__c, TaxId__c, TFN__c, Ucid__c FROM VCCD_Response__c WHERE Id= :VCCDRecordId];
                if(!VCCDRecord.isEmpty()){
                    interaction.Tax_Id__c = VCCDRecord[0].TaxId__c != null  ? VCCDRecord[0].TaxId__c :  '--';
                    interaction.Caller_Type__c = VCCDRecord[0].ProductType__c;
                    interaction.TFN_Toll_Free_Number__c = VCCDRecord[0].TFN__c != null  ? VCCDRecord[0].TFN__c  : '--';
                    interaction.Caller_Id_ANI__c  = VCCDRecord[0].Ani__c != null ? VCCDRecord[0].Ani__c : '--';
                    interaction.Member_Id__c      = VCCDRecord[0].MemberId__c != null ? VCCDRecord[0].MemberId__c : '--';
                    interaction.NPI__c = VCCDRecord[0].NPI__c != null ? VCCDRecord[0].NPI__c : '--';
                    interaction.Group_ID__c  =  '--';
                    interaction.Question_Type__c  = VCCDRecord[0].QuestionTypeTopic__c != null ? VCCDRecord[0].QuestionTypeTopic__c : '--';
                    interaction.Claim_Authorization_Referral_Number__c  = VCCDRecord[0].ClaimId__c != null ? VCCDRecord[0].ClaimId__c : '--';
                    interaction.Member_Date_of_Birth__c  =  VCCDRecord[0].SubjectDOB__c;
                    delete VCCDRecord[0];
                }
            }
        else if(!isVCCD && flowDetails != null && flowDetails.isGenesys && String.isNotBlank(String.valueof(flowDetails.IVRinfo))){
            string respstr= json.serialize(flowDetails.IVRinfo);
            Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(respstr);
            if(responseMap != null && !responseMap.isEmpty()){
                interaction.Tax_Id__c = responseMap.get('TaxId__c') != NULL ? (string) responseMap.get('TaxId__c') : '--';
                if(responseMap.get('ProductType__c') != NULL) interaction.Caller_Type__c = (string) responseMap.get('ProductType__c');
                interaction.TFN_Toll_Free_Number__c = responseMap.get('TFN__c') != NULL ? (string) responseMap.get('TFN__c') : '--';
                interaction.Caller_Id_ANI__c  =  responseMap.get('Ani__c') != NULL ? (string) responseMap.get('Ani__c') : '--';
                interaction.Member_Id__c     = responseMap.get('MemberId__c') != NULL ? (string) responseMap.get('MemberId__c') : '--';
                interaction.NPI__c = responseMap.get('NPI__c') != NULL ? (string) responseMap.get('NPI__c') : '--';
                interaction.Group_ID__c  =  '--';
                interaction.Question_Type__c  = string.isNotBlank(flowDetails.GeneysysQuestionType) ? flowDetails.GeneysysQuestionType : '--';
                interaction.Claim_Authorization_Referral_Number__c = responseMap.get('ClaimId__c') != NULL ? (string) responseMap.get('ClaimId__c') : '--';
                if(responseMap.get('SubjectDOB__c') != NULL){
                    if(string.valueof(responseMap.get('SubjectDOB__c')).contains('-')){
                        interaction.Member_Date_of_Birth__c  = Date.valueof(string.valueof(responseMap.get('SubjectDOB__c')));
                    }
                    else{
                        string DOB= string.valueof(responseMap.get('SubjectDOB__c'));
                        if(string.isNotBlank(DOB) && DOB.length() == 8 ) interaction.Member_Date_of_Birth__c = Date.valueof(DOB.substring(0,4)+'-'+ DOB.substring(4,6)+'-'+DOB.substring(6,8));
                    }
                }
            }
        }
        else{
            interaction.Tax_Id__c = '--';
            interaction.TFN_Toll_Free_Number__c = '--';
            interaction.Caller_Id_ANI__c  = '--';
            interaction.Member_Id__c      = '--';
            interaction.NPI__c = '--';
            interaction.Group_ID__c  = '--';
            interaction.Question_Type__c  = '--';
            interaction.Claim_Authorization_Referral_Number__c  = '--';

        }
        //US2903847 -END
        return interaction;
    }

    public static Id getPersonContactId(Id personAccountId) {
        return [SELECT Id, FirstName, LastName, PersonContactId FROM Account WHERE Id =: personAccountId].PersonContactId;
    }
    
    @AuraEnabled
    public static String getHippaGuideLinesUrl(){
       String endPoint = SAEUtils.getHippaGuideLinesUrl();
        return endPoint;
    }

}