src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACETLGT_Confetti__c.object
<CustomObject>
    <fields>
        <fullName>Header_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Header Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Milestone</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profile_List__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Profile List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>UserId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ACET Confetti</label>
    <nameField>
        <displayFormat>CONF-{000}</displayFormat>
        <label>ACET Confetti Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACET Confetti</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETMedicalLossRatioControllerTest.cls
@isTest
public class ACETMedicalLossRatioControllerTest{
     public static testmethod void ACETLGT_showConfettiTestmethod() {
         user userinfo = TestDataFactory.getUser('ECM Back Office Agent');
                     ACETLGT_Confetti__c confi = new ACETLGT_Confetti__c();
         confi.Header_Message__c = 'CONGRATULATIONS!!!';
           confi.Milestone__c = 125.2;
         confi.Profile_List__c ='ECM Back Office Agent';
         confi.UserId__c = userinfo.id;
         insert confi;
         list<string> redidlist = new list<string>();
         redidlist.add(confi.id);
       //  ACETLGT_showConfetti.getsObjectCountClassic(redidlist);
        
    }
    
    public static testmethod void ACETMedicalLossRatioPage() {
            PageReference ACETMedicalLossRatio = Page.ACETMedicalLossRatio;
            Interaction__c interactionId = TestDataFactory.createInteraction();
      RecordType newRecord = [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
          
          Account accountTest = new Account();
          accountTest.FirstName = 'Test';
          accountTest.LastName = 'Contact';
          accountTest.EID__c = 'PIN';
          accountTest.EID__pc = 'PIN';
          accountTest.RecordTypeId = newRecord.Id;
          insert accountTest;
  
      Account acc = [SELECT Id,personcontactid from Account where Id=:accountTest.Id];
          Contact cont = [SELECT Id,LastName,FirstName,EID__c,AccountId from Contact where Id=:acc.personcontactid];            ACETMedicalLossRatio.getParameters().put('interactionId', InteractionId.Id);
            ACETMedicalLossRatio.getParameters().put('contactId',cont.Id);
            ACETMedicalLossRatio.getParameters().put('callTopic','MedicalLossRatio');            
            ACETMedicalLossRatio.getParameters().put('SRK','test');
            Test.setCurrentPage(ACETMedicalLossRatio);  
            Apexpages.StandardController ACETMedicalLossCtrl = new Apexpages.standardController(InteractionId);           
            ACETMedicalLossRatioController ACETMedicalLossContr = new ACETMedicalLossRatioController();
            ACETMedicalLossContr.interaction = interactionId;
            ACETMedicalLossContr.Subject = cont; 
            ACETMedicalLossContr.swivelATNE_URL= 'test'; 
            ACETMedicalLossContr.swivelORBIT_URL= 'test'; 
     }  
 }