src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParticipantAdminAlias__c</fullName>
        <description>Created for WEX Health SSO connected app</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ParticipantAdminAlias</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParticipantEmployeeExternalId__c</fullName>
        <description>Created for WEX Health SSO Connected App</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ParticipantEmployeeExternalId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParticipantEmployerCode__c</fullName>
        <description>Created for WEX Health SSO Connected App</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ParticipantEmployerCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRK_KeyChain__c</fullName>
        <description>Store SRK Key Chain which is used for upserting Accounts</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>SRK KeyChain</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SRK_KeyChain__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SRK KeyChain</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Highlight_Panel_GroupInfo__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Highlight Panel GroupInfo</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Group/Employer</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>UHG</fullName>
                </value>
                <value>
                    <fullName>Internal UHG Employee</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Agency/Broker</fullName>
                </value>
                <value>
                    <fullName>Group Contact</fullName>
                </value>
                <value>
                    <fullName>Other Originator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Organization_Properties__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Organization Properties</label>
</CustomObject>

src/objects/OrgSpecificConfigurations__c.object
<CustomObject>
    <fields>
        <fullName>EndpointDomain__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebserviceConfigurations__c</fullName>
        <label>Webservice Configurations</label>
        <referenceTo>WebserviceConfigurations__c</referenceTo>
        <relationshipLabel>Org Specific Configurations</relationshipLabel>
        <relationshipName>OrgSpecificConfigurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Org Specific Configurations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Specific Configurations</pluralLabel>
    <recordTypes>
        <fullName>ServiceAPI</fullName>
        <active>true</active>
        <label>Service API</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WebserviceConfigurations__c.object
<CustomObject>
    <fields>
        <fullName>AuthorizationToken__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Authorization Token</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Has_Mutual_Authentication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Added for Certification(Mutual Authentication)</description>
        <label>Has Mutual Authentication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Headers__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Headers</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Webservice Configurations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Webservice Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webservice Configurations</pluralLabel>
    <recordTypes>
        <fullName>Service_API</fullName>
        <active>true</active>
        <label>Service API</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OPTUM_MemberAccountController_Test.cls
/*
 Name           : OPTUM_MemberAccountController_Test
 Created By     : Prasad kammella
 Created Date   : Oct 29th, 2020
 Description    : Code coverage for OPTUM_MemberAccountController 
 */
@isTest
public with sharing class OPTUM_MemberAccountController_Test {
public static String endDomain ='https://stg-faro-dmz-api.optum.com/faro/financial/accounts/v4.0/lookup';
    static testMethod void createint() {
        RecordType newRecord = [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
    //Insert Account record
        Account accountTest1 = new Account();
        accountTest1.FirstName = 'TestFirst';
        accountTest1.LastName = 'TestLast';
        accountTest1.EID__c = '12345';
        accountTest1.EID__pc = '12345';
		accountTest1.SRK_KeyChain__c ='abc';
        accountTest1.SRK_KeyChain__pc ='abc';
        accountTest1.ParticipantEmployeeExternalId__c = '0006851714';
        accountTest1.ParticipantEmployerCode__c = 'OPT';
	    accountTest1.ParticipantAdminAlias__c = 'J17894';
        accountTest1.RecordTypeId = newRecord.Id;
        insert accountTest1;
        //Insert Contact record
        Contact con = new Contact();
        con.FirstName = 'TestFname';
        con.lastname = 'TestLName';
        con.Tax_ID__c = '123456';
        con.NPI__c = '123457';
        insert con;
         //Insert Interaction record
        String JSONStr = '{"UHCBS":"","GroupN":"Test Group Name","GroupStatus":"Active","ServiceTeam":"NY Large","EffectiveStartDate":"3/1/2016","RiskManagement":"Rating Method","RatingMethod":"Support","RenewalDate":"3/1/2016","RelationshipType":"Mother","groupSName":"Test GroupName"}';
        Interaction__c inte = new Interaction__c();
        inte.Originator__c = con.id;
        inte.Originator_Type__c = 'Member';
        inte.Highlight_Panel_GroupInfo__c = JSONStr;
        insert inte;
      //Passing parameters to controller method
      string dt = '01/01/2020';
      OPTUM_MemberAccountController member = new OPTUM_MemberAccountController();
        OPTUM_MemberAccountController.getUser();
		OPTUM_MemberAccountController.getorg();
        OPTUM_MemberAccountController.queryInteraction('inte.id'); 
        OPTUM_MemberAccountController.createInteraction('Phone call','Member',accountTest1,'','');
        OPTUM_MemberAccountController.addPersonAccount('test','Optum',dt,'Eid','0006851714','J17894','OPT');
		OPTUM_MemberAccountController.addPersonAccount('test','Optum',dt,'Eid','0006851714','J17894','OPT');
        OPTUM_VCCDBridgeController.addPersonAccount('test','Optum',dt,'Eid','0006851714','J17894','OPT');
		OPTUM_VCCDBridgeController.addPersonAccount('test','Optum',dt,'Eid','0006851714','J17894','OPT');
        OPTUM_VCCDBridgeController.createInteraction('Phone call','Member',accountTest1,'','');
		OPTUM_MemberAccountController.getPersonAccounts('Eid');
        OPTUM_MemberAccountController.getPlatformCacheResponse('optum');
		OPTUM_MemberAccountController.updateIntOriginator('originatorId','subjectID','tpRel');
		OPTUM_MemberAccountController.getPersonAccounts('');
        OPTUM_MemberAccountController.formatDatewithslash('');
		//US3668445-Genesys controller test class
        OPTUM_GenesysController osc = new OPTUM_GenesysController();
        osc.run();
        OPTUM_GenesysController.parsedDate('01011988');
		

    }

    
	@isTest static void testSearchMemberWithSSN() {
        String faroId='73939F194FBA4104E053326C750A8837';
		String serviceApi='ServiceAPI';
        Organization_Properties__c orgProps1 = Organization_Properties__c.getOrgDefaults();
        orgProps1.OrganizationName__c = 'Rollstonqa';
        Upsert orgProps1;
        Organization_Properties__c orgProps = Organization_Properties__c.getOrgDefaults();
        orgProps.OrganizationName__c = 'QA';
        Upsert orgProps;
        WebserviceConfigurations__c tokenAPIWSConfig = new WebserviceConfigurations__c(
            Name = 'OptumVCCDMemberSearch',
            RecordTypeId = Schema.SObjectType.WebserviceConfigurations__c.getRecordTypeInfosByDeveloperName().get('Service_API').getRecordTypeId(),
            Method__c = 'GET',
            Headers__c = '[{"key":"FAROID","value":"<:FARO_ID:>"},{"key":"Content-Type","value":"application/json"}]',
            AuthorizationToken__c = '',
            Timeout__c = 10000,
            Has_Mutual_Authentication__c =true
        );
        Insert tokenAPIWSConfig;
         OrgSpecificConfigurations__c orgsp = new OrgSpecificConfigurations__c(
               RecordTypeId = Schema.SObjectType.OrgSpecificConfigurations__c.getRecordTypeInfosByDeveloperName().get(serviceApi).getRecordTypeId(),
               Name ='qa',
               EndpointDomain__c =endDomain,
               WebserviceConfigurations__c=tokenAPIWSConfig.Id
        );
        Insert orgsp;
        OrgSpecificConfigurations__c orgsp2 = new OrgSpecificConfigurations__c(
               RecordTypeId = Schema.SObjectType.OrgSpecificConfigurations__c.getRecordTypeInfosByDeveloperName().get(serviceApi).getRecordTypeId(),
               Name ='Rollstonqa',
               EndpointDomain__c =endDomain,
               WebserviceConfigurations__c=tokenAPIWSConfig.Id
        );
        Insert orgsp2;
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('OptumMemberserviceresponse');
        mock.setStatusCode(200);
        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);  
        Test.startTest();
        OPTUM_MemberAccountController.searchMemberWithSSN(faroId);
        Test.stopTest();
    }
     static testMethod void createint2() {
       OPTUM_MemberAccountController.SRKKeyChain='test';
        string dt = '01/01/2020';
      OPTUM_MemberAccountController.addPersonAccount('test','Optum',dt,'!abc','0006851714','J17894','OPT'); 
      OPTUM_Utils.convertReqURLToReqParamMap('test.com');
    }
}