src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Provider Affiliation</relationshipLabel>
        <relationshipName>Programs_Offered</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Group_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Provider Team</relationshipLabel>
        <relationshipName>Provider_Team</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <description>It is used to capture the information of all the Programs offered by UHC. </description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Program</valueSetName>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Message__c.object
<CustomObject>
    <description>When a new Direct Message is initiated following data will be stored in the object 

1.FeedID (DirectMessag Feed ID)
2.Account ID (Family account ID)
3.Marked (Initially this will be false, This is using to show the red flag)</description>
    <fields>
        <fullName>Feed_Id__c</fullName>
        <description>Record ID of the DirectMessageFeed object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Feed Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use to display red flag visible and hidden  in the messaging list UI</description>
        <label>Marked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages (Member)</relationshipLabel>
        <relationshipName>RTMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages (Program)</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProviderUser_List__c</fullName>
        <description>Store the provider user list selected from TO dropdown</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ProviderUser_List</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Provider_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Team</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages (Provider Team)</relationshipLabel>
        <relationshipName>ProviderTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SNI FL Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SNI FL Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SNI FL Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Message_Provider_Team__c.object
<CustomObject>
    <description>Junction object which stores relationship to Provider Team and SNI_FL_Message object</description>
    <fields>
        <fullName>Provider_Team__c</fullName>
        <description>Linked to provider team record type account</description>
        <label>Provider Team</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Message_Provider_Teams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Message__c</fullName>
        <description>Relationship with the SNI FL Message object to uniquely identify the provider team related message</description>
        <label>SNI FL Message</label>
        <referenceTo>SNI_FL_Message__c</referenceTo>
        <relationshipName>Message_Provider_Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SNI FL Message Provider Team</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Message Provider Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SNI FL Message Provider Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SNI_FL_Message_Status__c.object
<CustomObject>
    <description>Stores information regarding whether user click the message or not. This object will store

1. Lookup to (SNI FL Message)
2. Lookup to Agent Object
3. IsRead ( To check whether user read or not)</description>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores related agent ID</description>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SNI_FL_Message_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field hods whether user read the message or not</description>
        <label>IsRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link between SNI_FL_Message object</description>
        <label>SNI FL Message</label>
        <referenceTo>SNI_FL_Message__c</referenceTo>
        <relationshipLabel>SNI FL Message Statuses</relationshipLabel>
        <relationshipName>SNI_FL_Message_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SNI FL Message Status</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SNI FL  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SNI FL Message Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Complex Care</fullName>
    </customValue>
    <customValue>
        <fullName>Rare Conditions</fullName>
    </customValue>
    <customValue>
        <fullName>Diagnostic Odyssey</fullName>
    </customValue>
    <masterLabel>Program</masterLabel>
</GlobalValueSet>

src/classes/SNI_FL_ProviderMessageContentDisplay.cls
/********************************************************************************* 
Class Name     : SNI_FL_ProviderMessageContentDisplay.apxc
Description    : Handling Provider Messaging Message Content Display Functions US3128862
Created By     : Pavithra Fernando
Created Date   : 16/01/2021
  
Modification Log 
---------------------------------------------------------------------------------- 
Developer                   Date                   Description

----------------------------------------------------------------------------------            

*********************************************************************************/

public without sharing class SNI_FL_ProviderMessageContentDisplay {

    public static final String TEAMNAME = 'ACDC ';
    public static final String LINENUMBER = 'LineNumber ';
    public static final String FAMILYLINKPROFILE = 'Family Link Provider User';
    public static final String FAMILYENGAGEMENTPROFILE = 'Center for Health Navigation';
    

    //Retrieve directMessageWrapper object for given feedID. This will be invoked when a user clicks 
    //a message from the message list
    //Author: Pavithra (ACDC)
    public static SNI_FLDirectMessageWrapper getDirectMessageWrapper(String feedID,String userID){
        
        SNI_FLDirectMessageWrapper.SNI_FLUserDetails initiatedUser;
        SNI_FLDirectMessageWrapper.SNI_FL_PersonAccount memberInfo;
        List<String> providerTeam = new List<String>();
        List<SNI_FLDirectMessageWrapper.SNI_FLUserDetails> involvedUsers = new List<SNI_FLDirectMessageWrapper.SNI_FLUserDetails>();
        List<SNI_FLDirectMessageWrapper.SNI_FL_ProviderTeam> ptUsers = new List<SNI_FLDirectMessageWrapper.SNI_FL_ProviderTeam>();
        SNI_FLDirectMessageWrapper.SNI_FLMessage flMessage;
        SNI_FLDirectMessageWrapper.SNI_FLDirectMessageFeed directMessageFeed;
        
        Map<ID,List<FeedComment>> mapOfFeedComments;
        List<SNI_FLDirectMessageWrapper.SNI_FL_DirectMessageFeedComments> lstFeeedComment = new List<SNI_FLDirectMessageWrapper.SNI_FL_DirectMessageFeedComments>();
        String profileName;
        
        try{
            profileName = [Select Profile.Name from User where Id=:UserInfo.getUserId()].Profile.Name;
                        
            //Retrive SNI_FL_Message__c record matches with FeedID and creating SNI_FLMessage Wrapper object
            SNI_FL_Message__c flMsg = [SELECT Id, (SELECT id,IsRead__c FROM SNI_FL_Message_Statuses__r WHERE Agent__c=:UserInfo.getUserId()), Feed_Id__c, Marked__c, Member_Id__c, Member_Id__r.LastName, Member_Id__r.Salutation, Member_Id__r.FirstName, Program__c, ProviderUser_List__c FROM SNI_FL_Message__c WHERE Feed_Id__c=:feedID LIMIT 1];
            
            List<SNI_FL_Message_Status__c> msgStatus = flMsg.SNI_FL_Message_Statuses__r;
            
            memberInfo = new SNI_FLDirectMessageWrapper.SNI_FL_PersonAccount(flMsg.Member_Id__r.FirstName,flMsg.Member_Id__r.LastName,flMsg.Member_Id__c,flMsg.Member_Id__r.Salutation);

            List<SNI_FL_Message_Provider_Team__c> lstProTeam = [SELECT Provider_Team__c, Provider_Team__r.Name FROM SNI_FL_Message_Provider_Team__c WHERE SNI_FL_Message__c =: flMsg.Id ]; 

            for(SNI_FL_Message_Provider_Team__c pt: lstProTeam){
                providerTeam.add(pt.Provider_Team__c);
            }

            ID providerUserrecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Provider_User').getRecordTypeId();    

            List<AccountContactRelation> acr = [SELECT Contact.LastName, Contact.Salutation, Contact.FirstName, ContactId, Contact.AccountId, AccountId FROM AccountContactRelation WHERE AccountId IN :providerTeam AND Contact.IsPersonAccount=true AND Contact.Account.RecordTypeId=:providerUserrecordTypeId ];

            List<String> ptMembers = new List<String>();

            for(SNI_FL_Message_Provider_Team__c pt: lstProTeam){
                List<SNI_FLDirectMessageWrapper.SNI_FL_PersonAccount> lstUsers = new List<SNI_FLDirectMessageWrapper.SNI_FL_PersonAccount>();
                for(AccountContactRelation ac: acr){
                    ptMembers.add(ac.ContactId);
                    if(ac.AccountId == pt.Provider_Team__c){
                        lstUsers.add(new SNI_FLDirectMessageWrapper.SNI_FL_PersonAccount(ac.Contact.FirstName, ac.Contact.LastName, ac.ContactId, 'PT'));
                    }
                }
                ptUsers.add(new SNI_FLDirectMessageWrapper.SNI_FL_ProviderTeam(pt.Provider_Team__c, pt.Provider_Team__r.Name, lstUsers));
            }

            flMessage = new SNI_FLDirectMessageWrapper.SNI_FLMessage(flMsg.Feed_Id__c,flMsg.Marked__c,msgStatus.size()>0?msgStatus[0].IsRead__c:false,memberInfo,ptUsers);

            Set<String> toUserIds = new Set<String>();
            if(!string.isBlank(flMsg.ProviderUser_List__c)){
                toUserIds.addAll(flMsg.ProviderUser_List__c.split(';'));
            }

            Map<ID,User> toUserMap = getMapOfUserdetail(toUserIds);//Retriving map of userIDs and user records

            for(String s: toUserIds){
                User userInvolved = toUserMap.get(s);
                involvedUsers.add(new SNI_FLDirectMessageWrapper.SNI_FLUserDetails(userInvolved.FirstName,userInvolved.LastName,userInvolved.Id,userInvolved.profile.name,userInvolved.userrole.name));
            }
  
            //Retrieving drirectMessageFeed record for the feedID
            List<DirectMessageFeed> lstDirectMessageFeed =  [SELECT Id,Parent.Id, Parent.Subject,Body,LastModifiedDate,CreatedDate,CreatedById, ParentId FROM DirectMessageFeed WHERE Id =:feedID ];
			 system.debug('89 '+lstDirectMessageFeed.size());
            //Preparing initated user wrapper and involved user wrapper objects 
            List<DirectMessageMember> lstDirectMessageMember = [SELECT Id,DirectMessageId,MemberId FROM DirectMessageMember WHERE DirectMessageId=:lstDirectMessageFeed[0].ParentId ];
            system.debug('92 '+lstDirectMessageMember.size());
      
            Set<String> msgMembers = new Set<String>();
            for(DirectMessageMember mem: lstDirectMessageMember){
                msgMembers.add(mem.MemberId);
            }

            Set<String> ptUserIds = new Set<String>();
            for(User u : [SELECT Id FROM User WHERE ContactId IN :ptMembers]){
                ptUserIds.add(u.Id);
            }

            Map<ID,User> memberDetailMap = getMapOfUserdetail(msgMembers);//Retriving map of userIDs and user records
            
            for(DirectMessageMember member:lstDirectMessageMember){
                if(member.MemberId == userID) {
                    User initUser = memberDetailMap.get(userID);
                    initiatedUser = new SNI_FLDirectMessageWrapper.SNI_FLUserDetails(initUser.FirstName,initUser.LastName,initUser.Id,initUser.profile.name,initUser.userrole.name);
                }
                else if(!toUserIds.contains(member.MemberId)){
                    User userInvolved = memberDetailMap.get(member.MemberId);
                    if(userInvolved.profile.name == FAMILYENGAGEMENTPROFILE || userInvolved.profile.name == 'System Administrator'){
                        involvedUsers.add(new SNI_FLDirectMessageWrapper.SNI_FLUserDetails(userInvolved.FirstName,userInvolved.LastName,userInvolved.Id,userInvolved.profile.name,userInvolved.userrole.name));
                    } else if(userInvolved.profile.name == FAMILYLINKPROFILE &&  !toUserIds.contains(member.MemberId) && !ptUserIds.contains(member.MemberId)){
                        involvedUsers.add(new SNI_FLDirectMessageWrapper.SNI_FLUserDetails(userInvolved.FirstName,userInvolved.LastName,userInvolved.Id,userInvolved.profile.name,userInvolved.userrole.name));
                    }
                }
            }
            
            mapOfFeedComments = getCommentsForFeed(lstDirectMessageFeed, profileName);
            Map<ID,User> lstOfUser = getUserdetails();//Retriving map of userIDs and user records
           
            if(mapOfFeedComments != NULL){
                Map<ID,ContentVersion> attachments = getContentDocumentData(mapOfFeedComments.get(feedID));
                Map<ID,ContentDistribution> contentDistributions = getContentDistribution(mapOfFeedComments.get(feedID));
                for(FeedComment comment:mapOfFeedComments.get(feedID)){
                    User commentedUser = lstOfUser.get(comment.CreatedById);
                    ContentVersion version = attachments.get(comment.id);
                    ContentDistribution distribution = contentDistributions.get(comment.id);
                    
                    String userType;
                    if(commentedUser.profile.name == FAMILYENGAGEMENTPROFILE || commentedUser.profile.name == 'System Administrator'){
                        userType = 'AD';
                    } else {
                        if(commentedUser.profile.name == FAMILYLINKPROFILE && toUserIds.contains(commentedUser.Id)){
                            userType = 'PU';
                        } else if(commentedUser.profile.name == FAMILYLINKPROFILE &&  (!toUserIds.contains(commentedUser.Id) && ptUserIds.contains(commentedUser.Id))){
                            userType = 'PT';
                        } else if(commentedUser.profile.name == FAMILYLINKPROFILE &&  (!toUserIds.contains(commentedUser.Id) && !ptUserIds.contains(commentedUser.Id))){
                            userType = 'PU';
                        }
                    }

                    if(version != NULL){
                        lstFeeedComment.add(new SNI_FLDirectMessageWrapper.SNI_FL_DirectMessageFeedComments(comment.CommentBody,new SNI_FLDirectMessageWrapper.SNI_FLUserDetails(commentedUser.FirstName,commentedUser.LastName,commentedUser.Id,userType,commentedUser.userrole.name),comment.CreatedDate,
                                                                                                            version.ContentDocument.LatestPublishedVersionId,version.ContentDocument.FileExtension,version.ContentDocument.Title,true,distribution != NULL?distribution.ContentDownloadUrl:NULL));
                    }
                    else{
                        lstFeeedComment.add(new SNI_FLDirectMessageWrapper.SNI_FL_DirectMessageFeedComments(comment.CommentBody,new SNI_FLDirectMessageWrapper.SNI_FLUserDetails(commentedUser.FirstName,commentedUser.LastName,commentedUser.Id,userType,commentedUser.userrole.name),comment.CreatedDate,null,null,null,false,null));
                    }
                }
            }
            
            directMessageFeed = new SNI_FLDirectMessageWrapper.SNI_FLDirectMessageFeed(lstDirectMessageFeed[0].CreatedDate,lstDirectMessageFeed[0].LastModifiedDate,lstDirectMessageFeed[0].Body,lstDirectMessageFeed[0].Id,initiatedUser);            
            return new SNI_FLDirectMessageWrapper(involvedUsers,lstFeeedComment,lstDirectMessageFeed[0].Parent.Subject,directMessageFeed,flMessage,0,0,0,0,0);
            
        }catch(Exception ex){
            System.debug(TEAMNAME +ex.getMessage()+ LINENUMBER +ex.getLineNumber());
            return null;
        }
        
    }

    public static Map<Id,User> getMapOfUserdetail(Set<String> memList){
        try{
            Map<ID,User> lstOfUser = new Map<ID,User>([SELECT ID,FirstName,LastName,Profile.Name,UserRole.Name, ContactId FROM User WHERE Id IN :memList]);
            return lstOfUser;
        }catch(Exception ex){
            System.debug(TEAMNAME +ex.getMessage()+ LINENUMBER +ex.getLineNumber());
            return null;
        }
    }
         
    
    //Retrieve user records using a map structure. User id and each 
    //user record is retriving 
    public static Map<Id,User> getUserdetails(){
        try{
            Map<ID,User> lstOfUser = new Map<ID,User>([SELECT ID,FirstName,LastName,Profile.Name, UserRole.Name,ContactId FROM User]);
            return lstOfUser;
        }catch(Exception ex){
            System.debug(TEAMNAME +ex.getMessage()+ LINENUMBER +ex.getLineNumber());
            return null;
        }
    }
    
    //retrieves a mpa of directMessage feeds and related comments for each feed
    public static Map<ID,List<FeedComment>> getCommentsForFeed(List<DirectMessageFeed> lstDirectMsgFeeds, String profileName){
        
        Set<ID> feedIDs = new Set<ID>();
        Map<ID,List<FeedComment>> feedIdsWithComments = new Map<ID,List<FeedComment>>();
        
        try{
            for(DirectMessageFeed feed:lstDirectMsgFeeds){
                feedIDs.add(feed.id);
            }
            List<FeedComment> lstFeedComments = new List<FeedComment>();
            lstFeedComments = [SELECT Id,CreatedById,CreatedDate,RelatedRecordId,CommentBody,FeedItemId FROM FeedComment WHERE CreatedDate = LAST_N_DAYS:182 AND FeedItemId IN :feedIDs ORDER BY CreatedDate DESC LIMIT 10];
            
            
            if(!lstFeedComments.isEmpty()){
                for(FeedComment feeedcmt:lstFeedComments){
                    
                    if(feedIdsWithComments.containsKey(feeedcmt.FeedItemId)){
                        
                        List<FeedComment> lstValues = feedIdsWithComments.get(feeedcmt.FeedItemId);
                        lstValues.add(feeedcmt);
                        feedIdsWithComments.put(feeedcmt.FeedItemId,lstValues);
                        
                    }else{
                        
                        List<FeedComment> lstValues = new List<FeedComment>();
                        lstValues.add(feeedcmt);
                        feedIdsWithComments.put(feeedcmt.FeedItemId,lstValues);
                    }
                }
                
                return feedIdsWithComments;
            }else{
                return null;
            }
        }catch(Exception ex){
            System.debug(TEAMNAME +ex.getMessage()+ LINENUMBER +ex.getLineNumber());
            return null;
        }
    }
    
    //Retrieve a map of contentdocument records with comment id and contentdocument record
    public static Map<ID,ContentVersion> getContentDocumentData(List<FeedComment> lstOfComments){
        Map<ID,ContentVersion> commentIdsWithContent = new Map<ID,ContentVersion>();
        Set<ID> relatedRecords = new Set<ID>();
        Map<ID,ContentVersion> contentVersion = new Map<Id,ContentVersion>();
        try{
            for(FeedComment comment:lstOfComments){
                if(comment.RelatedRecordId != NULL){
                    relatedRecords.add(comment.RelatedRecordId);
                }
            }
            List<ContentVersion> lstOfContentVersions = [SELECT ID,ContentDocument.Title,ContentDocument.FileExtension,ContentDocument.LatestPublishedVersionId FROM ContentVersion WHERE Id IN :relatedRecords ];
            for(ContentVersion version:lstOfContentVersions){
                contentVersion.put(version.Id,version);
            }
            for(FeedComment comment:lstOfComments){
                if(comment.RelatedRecordId != NULL){
                    commentIdsWithContent.put(comment.Id,contentVersion.get(comment.RelatedRecordId));
                }
            }
            return commentIdsWithContent;
        }catch(Exception ex){
            System.debug(TEAMNAME +ex.getMessage()+ LINENUMBER +ex.getLineNumber());
            return null;
        }            
    }
    
    //Retrieve ContentDistribution records for each comment. A map data structure will be created with comment ids 
    //and each content distribution record 
    public static Map<ID,ContentDistribution> getContentDistribution(List<FeedComment> lstOfComments){
        
        Map<ID,ContentDistribution> commentIdsWithContentDistribution = new Map<ID,ContentDistribution>();
        Set<ID> relatedRecords = new Set<ID>();
        Map<ID,ContentDistribution> contentdistribution = new Map<Id,ContentDistribution>();
        
        try{
            
            for(FeedComment comment:lstOfComments){
                if(comment.RelatedRecordId != NULL){
                    relatedRecords.add(comment.RelatedRecordId);
                }
            }
            
            List<ContentDistribution> lstOfContentDistribution = [SELECT Id, ContentVersionId, ContentDownloadUrl FROM ContentDistribution WHERE ContentVersionId IN :relatedRecords];
            
            for(ContentDistribution distribution:lstOfContentDistribution){
                contentdistribution.put(distribution.ContentVersionId,distribution);
            }
            
            for(FeedComment comment:lstOfComments){
                if(comment.RelatedRecordId != NULL){
                    commentIdsWithContentDistribution.put(comment.Id,contentdistribution.get(comment.RelatedRecordId));
                }
            }
            
            return commentIdsWithContentDistribution;
        }catch(Exception ex){
            System.debug(TEAMNAME +ex.getMessage()+ LINENUMBER +ex.getLineNumber());
            return null;
        }
    }

 
}