src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <description>Store provider or member id received from OIL. Use it for upserting Accounts used for storing providers and members</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Text(255) (External ID) (Unique Case Insensitive)</inlineHelpText>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EID</label>
        <length>120</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PIR_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Claim_Type__c</fullName>
        <label>Claim Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCFA</fullName>
                </value>
                <value>
                    <fullName>NDC</fullName>
                </value>
                <value>
                    <fullName>UB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Formal_Complaint_Filed__c</fullName>
        <label>Formal Complaint Filed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Bearing__c</fullName>
        <label>Interest Bearing?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue_Category__c</fullName>
        <label>Issue Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>Early Warning System</fullName>
                </value>
                <value>
                    <fullName>First Time Visit</fullName>
                </value>
                <value>
                    <fullName>National PR Team Only</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Rework</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issue_Subcategory__c</fullName>
        <label>Issue Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Issue_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Additional Info Needed</fullName>
                </value>
                <value>
                    <fullName>Direct Intake from Provider</fullName>
                </value>
                <value>
                    <fullName>Known Service Issue</fullName>
                </value>
                <value>
                    <fullName>Reconsideration Failure</fullName>
                </value>
                <value>
                    <fullName>System Updated</fullName>
                </value>
                <value>
                    <fullName>Exhausted Delegate</fullName>
                </value>
                <value>
                    <fullName>External Rework</fullName>
                </value>
                <value>
                    <fullName>File Preparation</fullName>
                </value>
                <value>
                    <fullName>High Dollar</fullName>
                </value>
                <value>
                    <fullName>Internal Rework</fullName>
                </value>
                <value>
                    <fullName>Legal/DOI/Regulatory Affairs</fullName>
                </value>
                <value>
                    <fullName>Medicare Exhaust</fullName>
                </value>
                <value>
                    <fullName>Month End/Quarterly Escalations</fullName>
                </value>
                <value>
                    <fullName>Overpayment Recoupment</fullName>
                </value>
                <value>
                    <fullName>ppoOne NDC repricing</fullName>
                </value>
                <value>
                    <fullName>ppoOne Repricing (non NDC)</fullName>
                </value>
                <value>
                    <fullName>Purged</fullName>
                </value>
                <value>
                    <fullName>Research Complex Issue</fullName>
                </value>
                <value>
                    <fullName>Trend Identification Request</fullName>
                </value>
                <value>
                    <fullName>United as Secondary</fullName>
                </value>
                <value>
                    <fullName>Unpaid/Unprocessed</fullName>
                </value>
                <value>
                    <fullName>Balance Billing</fullName>
                </value>
                <value>
                    <fullName>CA/delegate</fullName>
                </value>
                <value>
                    <fullName>Contract/Demo Update</fullName>
                </value>
                <value>
                    <fullName>Coordination of Benefits</fullName>
                </value>
                <value>
                    <fullName>Inappropriate Referral to Mailbox</fullName>
                </value>
                <value>
                    <fullName>Member Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LA_C_S_Reason_for_Provider_Issue__c</fullName>
        <label>LA C&amp;S Reason for Provider Issue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incorrect Claim Payment</fullName>
                </value>
                <value>
                    <fullName>Reimbursement Rates</fullName>
                </value>
                <value>
                    <fullName>Prior Authorization</fullName>
                </value>
                <value>
                    <fullName>Provider Enrollment / Provider Credentialing</fullName>
                </value>
                <value>
                    <fullName>Lack of Information / Response</fullName>
                </value>
                <value>
                    <fullName>Recoupment</fullName>
                </value>
                <value>
                    <fullName>Third Party Liability</fullName>
                </value>
                <value>
                    <fullName>Lower Level of Care</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Contact__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Submission_Delay__c</fullName>
        <label>Reason for Submission Delay</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Submitter PTO/Weekend/Holiday</fullName>
                </value>
                <value>
                    <fullName>Additional submitter research/review</fullName>
                </value>
                <value>
                    <fullName>Analyst on PTO, incorrectly routed</fullName>
                </value>
                <value>
                    <fullName>CARCE Team</fullName>
                </value>
                <value>
                    <fullName>Case Cloned Incorrectly</fullName>
                </value>
                <value>
                    <fullName>Held for additional information</fullName>
                </value>
                <value>
                    <fullName>Issue from a previous case</fullName>
                </value>
                <value>
                    <fullName>Submitter Backlog</fullName>
                </value>
                <value>
                    <fullName>Routed to incorrect LOB in error</fullName>
                </value>
                <value>
                    <fullName>Split Case</fullName>
                </value>
                <value>
                    <fullName>Submitter System issues</fullName>
                </value>
                <value>
                    <fullName>Triage Backlog</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region_V_Work_Type__c</fullName>
        <label>Region V Work Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Specialty_Team__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>Resolution</fullName>
                </value>
                <value>
                    <fullName>Account Receivable</fullName>
                    <isActive>false</isActive>
                    <label>Account Receivable</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Remark_Explanation_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Remark/Explanation Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specialty_Team__c</fullName>
        <label>Specialty Team</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Local Ancillary</fullName>
                </value>
                <value>
                    <fullName>National Ancillary</fullName>
                </value>
                <value>
                    <fullName>NE Ancillary</fullName>
                </value>
                <value>
                    <fullName>NE ROS</fullName>
                </value>
                <value>
                    <fullName>Region V</fullName>
                </value>
                <value>
                    <fullName>SNI</fullName>
                </value>
                <value>
                    <fullName>Supervisor Escalation Team</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Status listed as open when case is open and must be closed to close the case</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Reopen</fullName>
                </value>
                <value>
                    <fullName>Additional Information Needed</fullName>
                    <isActive>false</isActive>
                    <label>Additional Information Needed</label>
                </value>
                <value>
                    <fullName>Monitoring</fullName>
                    <isActive>false</isActive>
                    <label>Monitoring</label>
                </value>
                <value>
                    <fullName>New</fullName>
                    <isActive>false</isActive>
                    <label>New</label>
                </value>
                <value>
                    <fullName>OGS</fullName>
                    <isActive>false</isActive>
                    <label>OGS</label>
                </value>
                <value>
                    <fullName>Pending Closed</fullName>
                    <isActive>false</isActive>
                    <label>Pending Closed</label>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                    <isActive>false</isActive>
                    <label>Reopened</label>
                </value>
                <value>
                    <fullName>Triaged</fullName>
                    <isActive>false</isActive>
                    <label>Triaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter_to_Contact_Provider_at_Closure__c</fullName>
        <inlineHelpText>Submitter is responsible to contact the Provider upon closure.</inlineHelpText>
        <label>Submitter to Contact Provider at Closure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PIR Detail</label>
    <nameField>
        <displayFormat>PIR-{000000}</displayFormat>
        <label>PIR Detail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_CommunityCaseCreateTest.cls
@isTest
public with sharing Class ACET_FAST_CommunityCaseCreateTest {
    
    static final String PIR_SUPPORT_PROFILE = 'System Administrator'; //'PIR Support Cases Profile'

    @testSetup static void setup() {
        string personAccRecordTypeID = ACET_Fast_ProviderContactCtrl.getRecordTypeIdbyDevName('Account','PersonAccount');        
        Account personAcc = new Account(FirstName ='Test', LastName ='TestProvider',RecordTypeId = personAccRecordTypeID, Tax_Id__c='061330992', EID__c='06133099212345');
        insert personAcc;
    }
    
    public static testmethod void testValidUserPIRCreateandEdit(){
        Profile supportUserProfile = ACET_Fast_TestDataFactory.getProfile(PIR_SUPPORT_PROFILE);      
        user fastUser = ACET_Fast_TestDataFactory.getUserRecord(supportUserProfile.id);
        insert fastUser;
        
        
        
        system.runAs(fastUser){
            case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
            
            PIR_Detail__c pir = new PIR_Detail__c(Formal_Complaint_Filed__c='Yes',
                                                  Remark_Explanation_Code__c='test',Status__c='Open',
                                                  Issue_Category__c='First Time Visit',Issue_Subcategory__c='Additional Info Needed',
                                                  Interest_Bearing__c='No',Specialty_Team__c='Region V',
                                                  Region_V_Work_Type__c='Accounts Receivable',LA_C_S_Reason_for_Provider_Issue__c='Reimbursement Rates',
                                                  Claim_Type__c='NDC',
                                                  Submitter_to_Contact_Provider_at_Closure__c='Yes',Reason_for_Submission_Delay__c='Submitter PTO/Weekend/Holiday',
                                                  Provider_Contact__c='Test',Provider_Contact_Preference__c='Both',
                                                  Par_Provider__c='Yes',Claims_Overturned__c='Overturned',
                                                  Will_this_be_closed_in_Practice_Mgmt__c='Yes',Provider_Was_contacted__c='Submitter to Contact Provider',
                                                  Exact_Count_Unknown_Multiple_Claims__c=true, No_Reference_Facilitated_Referral__c=true);
            
            try{
              ACET_FAST_CommunityCaseCreate.recordSave(caseRec, pir, 'TestProvider') ;
               
            }catch(exception ex){
                system.debug(ex.getMessage());
            }
            
        }
        
    }
    
}