src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Policy_ID__c</fullName>
        <description>Policy ID for the subscriber of the family.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Policy ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Provider User</fullName>
                </value>
                <value>
                    <fullName>Provider Team</fullName>
                </value>
                <value>
                    <fullName>Provider Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Family_Overview__c.object
<CustomObject>
    <description>Family information for MEP.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account the Family Information is related to.</description>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Family</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Overview</relationshipLabel>
        <relationshipName>Family_Overview</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Family Overview</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Overview Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Overview</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Member_Information__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Members Information</relationshipLabel>
        <relationshipName>Members_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Member Information</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Member Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members Information</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SNICaseTriggerHelperTest.cls
@isTest
public class SNICaseTriggerHelperTest {
    
    @isTest static void prePopulateFieldValuesMethod(){
        Id coRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Case Overview').getRecordTypeId();
        Id ecmRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('ECM').getRecordTypeId();
        Id familyRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Family').getRecordTypeId();
        Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
        User u = [Select id from User where Profile.Name = 'System Administrator' and isActive = true limit 1];
        List<Case> addCase = new List<Case>();
        Map<Id,Case> CaseMap = new Map<Id,Case>();
        system.runAs(u){
            Account ac = new Account();
            ac.Member_ID__c = '453543145';
            ac.Policy_ID__c = '0070145';
            ac.Name =   'Member1 Bourne Family';
            ac.RecordTypeId = familyRecordTypeId;
            insert ac;
            
            Account pa =new account();
            pa.PersonBirthdate = date.valueOf(ACETUtility.formatDateFutureDate('6/17/1979'));
            pa.firstName = 'Member1'; 
            pa.lastName = 'Bourne'; 
            pa.RecordTypeId = personAccRecordTypeId;
            pa.Policy_ID__c = '123456';
            insert pa;
            
            Account personAcc = [Select PersonContactId From Account Where Id = :pa.Id];
            
            AccountContactRelation acr = new AccountContactRelation();
            acr.ContactId = personAcc.PersonContactId;            
            acr.Accountid = ac.id;
            acr.Relationship__c = 'Child/Other';
            insert acr;
            
            Case coCase = TestDataFactory.createCases(1)[0];
            coCase.RecordTypeId =coRecordTypeID;
            coCase.AccountId = pa.Id;
            Insert coCase;
            addCase.add(coCase);
            
            Case ecmCas = TestDataFactory.createCases(1)[0];
            ecmCas.RecordTypeId =ecmRecordTypeID;
            ecmCas.Topic__c = 'Appeals - Post Service';
            ecmCas.Type__c = 'Family Advisor';
            ecmCas.ParentId = coCase.Id;
            ecmCas.Subject_Group_ID__c = '123456';
            ecmCas.Case_Type__c = 'Opportunity';
            Insert ecmCas;
            
            addCase.add(ecmCas);
            CaseMap.put(ecmCas.Id, ecmCas);
            
            CaseTeamRole caseRole = new CaseTeamRole();
            caseRole.Name = 'XYZ';
            caseRole.AccessLevel = 'Read';
            insert caseRole;
            
            CaseTeamMember caseTeam = new CaseTeamMember();
            caseTeam.ParentId = coCase.Id;
            caseTeam.MemberId = personAcc.PersonContactId;
            caseTeam.TeamRoleId = caseRole.Id;
            insert caseTeam;
            
            Family_Overview__c famOverview = new Family_Overview__c();
            famOverview.Account__c = ac.Id;
            insert famOverview;
            
            Member_Information__c memInfo = new Member_Information__c();
            memInfo.Account__c = pa.Id;
            insert memInfo;
            
            SNICaseTriggerHelper.prePopulateFieldValues(addCase);  
            SNICaseTriggerHelper.copyCaseTeamtoOpportunity(addCase);
            SNICaseTriggerHelper.sniCaseRecordTypeSet();
            Boolean tempValue = true;
            SNICaseTriggerHelper.calculateActiveCount(CaseMap, tempValue, tempValue);
            set<Id> conIdTempSet = new set<Id>();
            conIdTempSet.add(personAcc.PersonContactId);
            set<Id> delCaseRecords = new set<Id>();
            delCaseRecords.add(ecmCas.Id);
            SNICaseTriggerHelper.updateDetail(conIdTempSet,delCaseRecords);
        }
        
    }
}