src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assigned_Advisor__c</fullName>
        <description>Name of the Account owner.  Used to display on list views.</description>
        <formula>Owner.FirstName + &quot; &quot; + Owner.LastName</formula>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program and Styx Dashboard.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>Onshore Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <description>Used to indicate if group has an Onshore restriction and to limit visibility of object</description>
        <label>UHG Restriction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Family</fullName>
        <active>true</active>
        <description>Family Account</description>
        <label>Family</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>Member_ID__c</fullName>
        <description>Member ID of family in SNI program.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <inlineHelpText>E&amp;I = Member ID
C&amp;S = Medicaid Number</inlineHelpText>
        <label>Member ID</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Provider User</fullName>
                </value>
                <value>
                    <fullName>Provider Team</fullName>
                </value>
                <value>
                    <fullName>Provider Team Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Relationship__c</fullName>
        <description>Family member’s Relationship in the family.</description>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Child/Other</fullName>
                </value>
                <value>
                    <fullName>Non-Policy Caregiver</fullName>
                </value>
                <value>
                    <fullName>Spouse/Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Subscriber/Recipient</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Message_Request_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Advisor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Assigned Advisor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City/State </label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Member ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Content__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Message Content</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Message_Recipients__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Message Recipients</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message_Subject__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Message Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onshore_Restriction__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Onshore Restriction</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Message__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SNI FL Message</label>
        <referenceTo>SNI_FL_Message__c</referenceTo>
        <relationshipName>Message_Request_For_Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UHG_Restriction__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>UHG Restriction</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Message Request Queue</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Message Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Message Request Queue</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SNI_FL_Message__c.object
<CustomObject>
    <description>When a new Direct Message is initiated following data will be stored in the object 

1.FeedID (DirectMessag Feed ID)
2.Account ID (Family account ID)
3.Marked (Initially this will be false, This is using to show the red flag)</description>
    <fields>
        <fullName>Member_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SNI FL Messages (Member)</relationshipLabel>
        <relationshipName>RTMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SNI FL Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SNI FL Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SNI FL Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SNI_FL_ThreeWayCommunicationController.cls
/********************************************************************************* 
Class Name     : SNI_FL_ThreeWayCommunicationController
Description    : Logic related to 3way communication functionality
Created By     : Sameera De Silva US3376756 
Created Date   : 3/23/2021
***********************************************************************************/

public with sharing class SNI_FL_ThreeWayCommunicationController {

    private static final string ERRORMSG = 'Error Occured: SNI_FL_ThreeWayCommunicationController ';
    /**
     * @description insert new message request record when a new message initating from 
     *              mymessage tab/family level/backup advisor
     * @param inputValues 
     */    
    public static void createNewMessageRequest(Map<String,Object> parameters,String sniMessageID){
        

        if(parameters != NULL && parameters.get('selectedQueue') != NULL){
            try{

                AccountContactRelation familyAccountDetails = getFamilyAccountDetails((String)parameters.get('FamilyAccountID'));
                system.debug('values**' + familyAccountDetails);
                Message_Request_Queue__c messageRequest = new Message_Request_Queue__c();
                if(familyAccountDetails != NULL){
                    messageRequest.Assigned_Advisor__c = familyAccountDetails.Account.Owner.Name;
                    messageRequest.City_State__c = familyAccountDetails.Contact.MailingCity+','+familyAccountDetails.Contact.MailingState;
                    messageRequest.Family_Name__c = familyAccountDetails.Account.Name;
                    messageRequest.Onshore_Restriction__c = familyAccountDetails.Account.Onshore_Restriction__c;
                    messageRequest.UHG_Restriction__c = familyAccountDetails.Account.UHG_Restriction__c;
                    messageRequest.Member_ID__c = familyAccountDetails.Account.Member_ID__c;
                }
                messageRequest.Message_Content__c = ((String)parameters.get('MessageContent')).stripHtmlTags();
                messageRequest.Message_Subject__c = (String)parameters.get('MessageSubject');
                
                if(!Test.isRunningTest())
                    messageRequest.SNI_FL_Message__c = sniMessageID;

                Map<Object,Object> m = (Map<Object,Object>)parameters.get('selectedQueue');
                
                messageRequest.OwnerId = (String)m.get('value');
				system.debug('owner is --- ' + (String)m.get('value'));
                messageRequest.Message_Recipients__c = '';
                for(String userName:getUserRelatedData((List<ID>)parameters.get('ToUsers'))){
                    
                    messageRequest.Message_Recipients__c += userName+',';
                }
                messageRequest.Message_Recipients__c = messageRequest.Message_Recipients__c.removeEnd(',');

                // US3393183 - Nantha -ACDC
                Set<String> toList = new Set<String>();
                toList.add(messageRequest.OwnerId);
                system.debug('tolst is---' + toList);

                String subject = 'Message Request has been received for ' + messageRequest.Family_Name__c + '... Please accept!';
                String body = 'Please review the Message Request Queue page to see request.';
                
                insert messageRequest;

                CustomNotificationType notificationType = [SELECT ID FROM CustomNotificationType WHERE DeveloperName ='SNI_FL_Message_Notification'];
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
                notification.setNotificationTypeId(notificationType.ID);
                notification.setTargetId(messageRequest.Id);
                notification.setTitle(subject);
                notification.setBody(body);
                notification.send(toList); 
                // US3393183 - Nantha -ACDC 

            }catch(Exception ex){
                System.debug(ERRORMSG+ex.getMessage());
            }
        } 
    }

    /**
     * @description getFamilyaccount related data
     * @param accountID 
     * @return  `AccountContactRelation`
     */    
    private static AccountContactRelation getFamilyAccountDetails(String accountID){

        try{
            return [SELECT Id, Account.Member_ID__c,Account.Onshore_Restriction__c,Account.UHG_Restriction__c,Account.Name,Account.Owner.Name,Relationship__c, 
            ContactId,Contact.MailingCity,Contact.MailingState FROM AccountContactRelation where 
            AccountID=:accountID LIMIT 1]; //AND Relationship__c='Subscriber/Recipient' LIMIT 1
        }catch(Exception ex){
            
            System.debug(ERRORMSG+ex.getMessage());
            return null;
        }
    }

    /**
     * @description gettting user related datas
     * @param toUsers 
     * @return  `List<User>`
     */    
    private static List<String> getUserRelatedData(List<ID> toUsers){

        try{
            List<String> userNames = new List<String>();

            for(User usr:[SELECT Name FROM User where AccountId IN:toUsers OR Id IN:toUsers]){
                
                userNames.add(usr.Name);
            }
            return userNames;

        }catch(Exception ex){
            System.debug(ERRORMSG+ex.getMessage());
            return null;
        }

    }

    /**
     * @description US3379195
     * @param messageReqId,  userId
     * @user  Pavithra ACDC
     */   
    // 
    @AuraEnabled    
    public static void getMessageRequestQueueDetails(String messageReqId, String userId){
    SNI_FL_MessageRequestQueueController.getMessageRequestQueueDetails(messageReqId,userId);
    }

}