src/objects/ACETHippaCategoryRule__c.object
<CustomObject>
    <fields>
        <fullName>Caller_SubType__c</fullName>
        <label>Caller SubType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Personal Representative</fullName>
                </value>
                <value>
                    <fullName>Parent/Guardian/Custody Holder</fullName>
                </value>
                <value>
                    <fullName>Third Parties</fullName>
                </value>
                <value>
                    <fullName>Interpreter for member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <label>Caller Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Adult Dependent</fullName>
                </value>
                <value>
                    <fullName>Minor Dependent</fullName>
                </value>
                <value>
                    <fullName>Self Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>General__c</fullName>
        <defaultValue>false</defaultValue>
        <label>General</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Age__c</fullName>
        <defaultValue>200</defaultValue>
        <description>Enter 200 when Age is &quot;Not Applicable&quot;</description>
        <inlineHelpText>Enter 200 when Age is &quot;Not Applicable&quot;</inlineHelpText>
        <label>Maximum Age</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Medical__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Medical</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Min_Age__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter 0 when Age is &quot;Not Applicable&quot;</description>
        <inlineHelpText>Enter 0 when Age is &quot;Not Applicable&quot;</inlineHelpText>
        <label>Minimum Age</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sensitive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sensitive</label>
        <type>Checkbox</type>
    </fields>
    <label>ACET Hippa Category Rule</label>
    <nameField>
        <displayFormat>Rule-{000}</displayFormat>
        <label>ACET Hippa Category Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACET Hippa Category Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant Controller</fullName>
                </value>
                <value>
                    <fullName>Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Member Note</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Primary Benefits Administrator</fullName>
                </value>
                <value>
                    <fullName>Primary Billing Administrator</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>UHC Employee</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Group/Employer</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>UHG</fullName>
                </value>
                <value>
                    <fullName>Internal UHG Employee</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Agency/Broker</fullName>
                </value>
                <value>
                    <fullName>Group Contact</fullName>
                </value>
                <value>
                    <fullName>Other Originator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Interactions (Third Party)</relationshipLabel>
        <relationshipName>Interactions1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <label>Third Party</label>
    <nameField>
        <displayFormat>TP #-{0000000000}</displayFormat>
        <label>Third Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Third_Party_Originator__c.object
<CustomObject>
    <description>to store the originator association between a third party and a subject</description>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Third Party Originators</relationshipLabel>
        <relationshipName>Third_Party_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Third Party Originator</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Third Party Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Originators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETHIPPADisclosureController.cls
public without sharing class ACETHIPPADisclosureController {
    private Interaction__c Interaction {get;set;} 
    public String InteractionId {get;set;}
    public Set<String> categories {get;set;}
    public String subDOB {get;set;}
    public String orgDOB {get;set;}
    public Integer callerAge {get;set;}
    private List<ACETHippaCategoryRule__c> hippaRules;
    public ACETHIPPADisclosureController(){

        categories = new Set<String>();
    }

    public void runHippaCategoryRules(){
        system.debug('runHippaCategoryRules called');
        Interaction = ACETMemberQueryUtil.queryInteraction(interactionId);


        String callerType = Interaction.Originator_Type__c;//Member/provider/Producer/Employer/Broker
        if(callerType.contains('Employer')){
            callerType = 'Employer';
        }
        Integer subjectAge = getAgeFromDOB(subDOB);
        system.debug('subjectAge >> '+subjectAge);
        system.debug('orgDOB >> '+orgDOB);
        String orgDependent;
        if(!String.isEmpty(orgDOB)){
            callerAge = getAgeFromDOB(orgDOB);
            orgDependent = callerAge >= 18 ? 'Adult Dependent' : 'Minor Dependent';
        }else{
            orgDependent = null; 
        }
        
        String callerSubType; //Will be third party originator type
        if(Interaction.Third_Party__c != null){
            List<Third_Party_Originator__c> TPOList = [SELECT Id,Name FROM Third_Party_Originator__c WHERE Third_Party__c = :Interaction.Third_Party__c];
            if(TPOList != null && TPOList.size() > 0)
                callerSubType = TPOList[0].Name;
            orgDependent = null;
        }
        List<String> cstList =new List<String>();
        cstList.add(callerSubType);
        cstList.add('Third Parties');
        Integer callerAge;
 

        categories = new Set<String>();
        system.debug(callerType + ' :: '+cstList + ' :: '+orgDependent );
        hippaRules = [SELECT Caller_SubType__c,Caller_Type__c,General__c,Max_Age__c,Medical__c,Min_Age__c,Sensitive__c
                      FROM ACETHippaCategoryRule__c where
                      (caller_type__c = :callerType and 
                      Caller_subtype__c in :cstList and 
                      Dependent__c = : orgDependent and
                      max_age__c > : subjectAge and
                      min_age__c < : subjectAge)];
        system.debug(hippaRules);
        if(!hippaRules.isEmpty()){
            for(ACETHippaCategoryRule__c rule : hippaRules){
                    if(rule.General__c){
                        categories.add('General');
                    }
                    if(rule.Medical__c){
                        categories.add('Medical');
                    }
                    if(rule.Sensitive__c){
                        categories.add('Sensitive');
                    }    
                
            }           
        }


    }

    public Integer getAgeFromDOB(String dob){
        String dateWithDash;
        Date d;
        if(dob != null && dob.contains('/')){
            dateWithDash = ACETUtility.formatMMDDYYYYwithSlashToYYYYMMDDwithDash(dob);
        }
        if(dob != null && dob.contains('-')){
            dateWithDash = dob;
        }  
        if(dateWithDash != null) {    
            d = Date.valueOf(dateWithDash);        
            return Integer.valueOf(d.daysBetween(Date.today())/365); 
        }
        else
            return null;       
    }

}