src/objects/Alert__c.object
<CustomObject>
    <description>Used to store Provider and Member Alerts which are imported into SF from UHG SharePoint</description>
    <fields>
        <fullName>Alert_Comments__c</fullName>
        <description>Alert Comments</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Alert Comments</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Alert_Title__c</fullName>
        <description>Alert&apos;s title</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Alert Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Benefit_Bundle_Option_ID__c</fullName>
        <description>Benefit Bundle Option ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Benefit Bundle Option ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <description>Indicates audience of alert</description>
        <label>Business Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Polaris</fullName>
                </value>
                <value>
                    <fullName>Spire</fullName>
                </value>
                <value>
                    <fullName>PIR - RR/PA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>Start Date for alert&apos;s Effective Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>End Date of alert&apos;s effective date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Based on alert type, either member&apos;s group # or provider&apos;s facility #</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Number__c</fullName>
        <description>Based on alert type, either member&apos;s id or provider&apos;s tax id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SharePoint_ID__c</fullName>
        <description>External Id to found on excel worksheets for the row (alert)  stored in SharePoint</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SharePoint ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates what type of alert: member, member group, provider, provider group</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Member Group</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Provider Group</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Alert_Business_Segment__mdt.object
<CustomObject>
    <fields>
        <fullName>Business_Segment__c</fullName>
        <label>Business Segment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Alert Business Segment</label>
    <pluralLabel>Alert Business Segments</pluralLabel>
</CustomObject>

src/classes/ACETLGT_HighlightsPanelController.cls
public class ACETLGT_HighlightsPanelController {
    
    public ACETLGT_HighlightsPanelController(){}
    
    public List<Alert__c> getNoAlert(String type, String memProId, String groupNo, string bundleId){
        String groupType = type + ' Group';
        List<Alert__c> tempListAlert = new List<Alert__c>();
        String query = '';
        User currentUser = [SELECT Profile.Name FROM USER WHERE Id =:UserInfo.getUserId()];
        List<Alert_Business_Segment__mdt> alertBusinessSegment = [
            SELECT 
            Business_Segment__c 
            FROM Alert_Business_Segment__mdt 
            WHERE MasterLabel =:currentUser.Profile.Name
        ];
        List<List <sObject>> searchList = new List<List<SObject>>();
        if(String.isBlank(groupNo) && String.isBlank(memProId)){
            return tempListAlert;
        }
		if(bundleId != null && bundleId != ''){
			query = 'FIND  \'' + bundleId + '\' IN ALL Fields Returning Alert__c';
          	query += ' (Id,SharePoint_ID__c,Type__c,Group_Number__c,ID_Number__c,Benefit_Bundle_Option_ID__c,Alert_Title__c,Effective_Date__c,Alert_Comments__c,End_Date__c WHERE Effective_Date__c <= TODAY AND End_Date__c >= TODAY '+(alertBusinessSegment!=null && alertBusinessSegment.size()>0?'AND Business_Segment__c=\''+alertBusinessSegment[0].Business_Segment__c+'\'':'')+' ORDER BY Type__c,Effective_Date__c DESC)';
          	searchList = search.query(query);
          	tempListAlert.addAll(((List<Alert__c>)searchList[0]));
		}
        if(String.isNotBlank(memProId) && memProId.length() > 1){
            query = 'FIND  \'' + memProId + '\' IN ALL Fields Returning Alert__c';
                query += ' (Id,SharePoint_ID__c,Type__c,Group_Number__c,ID_Number__c,Benefit_Bundle_Option_ID__c,Alert_Title__c,Effective_Date__c,Alert_Comments__c,End_Date__c WHERE Effective_Date__c <= TODAY AND End_Date__c >= TODAY '+(alertBusinessSegment!=null && alertBusinessSegment.size()>0?'AND Business_Segment__c=\''+alertBusinessSegment[0].Business_Segment__c+'\'':'')+' AND Type__c = \''+ type +'\'  ORDER BY Type__c,Effective_Date__c DESC)';
            searchList = search.query(query);
            tempListAlert.addAll(((List<Alert__c>)searchList[0]));
        }
        
        if(String.isNotBlank(groupNo) && groupNo.length() > 1){
            if(type==null){  
              query = 'FIND  \'' + groupNo + '\' IN ALL Fields Returning Alert__c';
              query += ' (Id,SharePoint_ID__c,Type__c,Group_Number__c,ID_Number__c,Benefit_Bundle_Option_ID__c,Alert_Title__c,Effective_Date__c,Alert_Comments__c,End_Date__c WHERE Effective_Date__c <= TODAY AND End_Date__c >= TODAY ORDER BY Type__c,Effective_Date__c DESC)';
            }else{
                type += ' Group';
                query = 'FIND  \'' + groupNo + '\' IN ALL Fields Returning Alert__c';
                    query += ' (Id,SharePoint_ID__c,Type__c,Group_Number__c,ID_Number__c,Benefit_Bundle_Option_ID__c,Alert_Title__c,Effective_Date__c,Alert_Comments__c,End_Date__c WHERE Effective_Date__c <= TODAY AND End_Date__c >= TODAY '+(alertBusinessSegment!=null && alertBusinessSegment.size()>0?'AND Business_Segment__c=\''+alertBusinessSegment[0].Business_Segment__c+'\'':'')+'AND Type__c = \''+ type +'\' ORDER BY Type__c,Effective_Date__c DESC)';
            }
            searchList = search.query(query);
            tempListAlert.addAll(((List<Alert__c>)searchList[0]));
        }
        
        
        return tempListAlert;  
    }

}