src/objects/Bookmark_Links__c.object
<CustomObject>
    <description>This object is used to store bookmark links displayed on the application footer. This object will be business enabled.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Must be true for bookmark link to active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <description>Display name of links</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Display Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profiles__c</fullName>
        <description>Profiles enabled for each link</description>
        <label>Profiles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACET Motion</fullName>
                </value>
                <value>
                    <fullName>ACET Provider</fullName>
                </value>
                <value>
                    <fullName>ACET Member</fullName>
                </value>
                <value>
                    <fullName>OF CSR</fullName>
                </value>
                <value>
                    <fullName>System Administrator</fullName>
                </value>
                <value>
                    <fullName>ACET EB Agent</fullName>
                </value>
                <value>
                    <fullName>ECM Back Office Agent</fullName>
                </value>
                <value>
                    <fullName>Research User</fullName>
                </value>
                <value>
                    <fullName>Provider Service</fullName>
                </value>
                <value>
                    <fullName>ACET ETS-BE</fullName>
                </value>
                <value>
                    <fullName>ACET ETS-BE Research User</fullName>
                </value>
                <value>
                    <fullName>Provider Issue Resolution</fullName>
                </value>
                <value>
                    <fullName>FPS OST</fullName>
                </value>
                <value>
                    <fullName>ACET CSO</fullName>
                    <isActive>false</isActive>
                    <label>ACET CSO</label>
                </value>
                <value>
                    <fullName>ACET CSS</fullName>
                    <isActive>false</isActive>
                    <label>ACET CSS</label>
                </value>
                <value>
                    <fullName>ACET DCSM</fullName>
                    <isActive>false</isActive>
                    <label>ACET DCSM</label>
                </value>
                <value>
                    <fullName>ACET Rapid Responder Team</fullName>
                    <isActive>false</isActive>
                    <label>ACET Rapid Responder Team</label>
                </value>
                <value>
                    <fullName>ACET System Administrator</fullName>
                    <isActive>false</isActive>
                    <label>ACET System Administrator</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>Hyperlink URL</description>
        <encryptionScheme>None</encryptionScheme>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Bookmark Link</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Bookmark Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookmark Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETBookmarkLinksController.cls
public with sharing class ACETBookmarkLinksController {
    
   
    public List<Bookmark_Links__c> lstBookmarkLinks{get;set;}
    public string CIRRUSURL{get;set;}
    public string membID{get;set;}
    
    
    public ACETBookmarkLinksController()
    {
        membID = '';
            Id profileId=userinfo.getProfileId();
            String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
            system.debug('ProfileName'+profileName);
            
            lstBookmarkLinks = [select name,Display_Name__c,Profiles__c,URL__c,Active__c from Bookmark_Links__c where Active__c = true and Profiles__c includes (:profileName) order by Display_Name__c];
    } 
    
    public void fetchCirrusSSOURL(){
        String MemberId = ApexPages.currentPage().getParameters().get('memId');
        system.debug('>>>>MemberId'+MemberId);
        CIRRUSURL = ACETCirrusLandingPageCtrl.GenerateCIRRUSURL(MemberId,'memberDetail','Member','','');
    }
    
    
 }