src/objects/Call_Topic_Access__c.object
<CustomObject>
    <label>Call Topic Access</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Call Topic Access Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Topic Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VCCD_Response__c.object
<CustomObject>
    <description>The Purpose of this object is to store incoming VCCD Request Details</description>
    <fields>
        <fullName>AcctManagerPhone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>AcctManagerPhone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ani__c</fullName>
        <description>The Purpose of this field is to Capture Contact Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Ani</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Caller Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ClaimId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimsDOSMD__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ClaimsDOSMD</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HIPPAFlag__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HIPPAFlag</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>MSID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>MemberId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NPI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ProductType</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionTypeCode__c</fullName>
        <description>This field will store the Question Type code from VCCD Request</description>
        <encryptionScheme>None</encryptionScheme>
        <label>QuestionType Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>QuestionType</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubjectDOB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SubjectDOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TFN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TFN</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TaxId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ucid__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Ucid</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisionClaimID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>VisionClaimID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>claimsDOS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>claimsDOS</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dentalClaimID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>dentalClaimID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>dnis__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>dnis</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>eligibilityTypeCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>eligibilityTypeCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>groupID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>groupID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This Flag is Used to check if the Current record is Active or not</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legacyProviderId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>legacyProviderId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>producerID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>producerID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rcKeyCallId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Caller Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>VCCD Response</label>
    <nameField>
        <displayFormat>VCCD-{0000000000}</displayFormat>
        <label>VCCD Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VCCD Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETLGT_VCCDBridgeController.cls
public class ACETLGT_VCCDBridgeController {

    /**
     * Used to Insert Incoming VCCD Details to VCCD Response Object.
     * Return Type : VCCD_Response__c for the Logged In User
     */
    @AuraEnabled
    public static clsVccdResponse getVCCDData() {
        String strQuestionType = '';
        clsVccdResponse objReturnResponse = null;
        User objUser = [Select id, FederationIdentifier from User where Id = : UserInfo.getUserId()];
        List<VCCD_Response__c> lstVCCDResponse = new List<VCCD_Response__c>();
        List<Call_Topic_Access__c> lstCallTopicTypes = new List<Call_Topic_Access__c>();

        lstVCCDResponse = [SELECT Id,Ani__c, Caller_Type__c, ClaimsDOSMD__c, ClaimId__c, MSID__c, MemberId__c, NPI__c, ProductType__c, QuestionTypeCode__c, SubjectDOB__c, QuestionType__c, TFN__c, TaxId__c, Ucid__c, isActive__c, eligibilityTypeCode__c, HIPPAFlag__c, producerID__c, groupID__c, legacyProviderId__c, AcctManagerPhone__c, claimsDOS__c, VisionClaimID__c, dentalClaimID__c, rcKeyCallId__c, dnis__c FROM VCCD_Response__c WHERE (MSID__c= :objUser.FederationIdentifier AND isActive__c = true) ORDER BY createddate desc];
         system.debug('lstVCCDResponse'+lstVCCDResponse);
         
      List<Call_Topic_Access__c> CallTopicAccess = [SELECT Id, Name FROM Call_Topic_Access__c where Name = : lstVCCDResponse[0].QuestionType__c limit 1];

        
        if(lstVCCDResponse.isEmpty() == false) {
            String CallTopicID = String.valueOf(CallTopicAccess[0].Id);
            
            objReturnResponse = new clsVccdResponse(lstVCCDResponse[0],CallTopicID);
        }

        return objReturnResponse;
    }

    /**
     * Used to update current VCCDResponse Record
     * Return Type : No Return Type
     */
    @AuraEnabled
    public static void updateCurrentRecordToInactive(VCCD_Response__c objVccdResponse){
        if(objVccdResponse != null) {
            objVccdResponse.ownerId = UserInfo.getUserId();
            objVccdResponse.isActive__c = false;
            update objVccdResponse;
        }
    }

    /**
     * Used to return Current User Record
     * Return Type : User Object Instance
     */
    @AuraEnabled
    public static User getUserDetails(){
        return [Select id, Name, Profile.Name ,FirstName, LastName from User Where id =: UserInfo.getUserId()];
    }

    /**
     * Wrapper Class to Return the VccdResponse Object and Related Question Type
    */
    public class clsVccdResponse {
        @AuraEnabled public VCCD_Response__c objVccdResponse {get;set;} {objVccdResponse = new VCCD_Response__c();}
        @AuraEnabled public String strCallTopicType { get;set; } {strCallTopicType = '';}
        @AuraEnabled public String CallTopicID { get;set; } {CallTopicID = '';}

        public clsVccdResponse(VCCD_Response__c objResponse,String CallTopicID) {
            this.objVccdResponse = objResponse;
            this.CallTopicID = CallTopicID;
            
        }
    }
}