src/objects/Case_Item__c.object
<CustomObject>
    <description>Used to track tasks to be performed on single topic.</description>
    <fields>
        <fullName>Advocate_Comments__c</fullName>
        <description>Comments that are created by the person working the case item/claim</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This information is viewed by providers, avoid acronyms &amp; internal jargon</inlineHelpText>
        <label>Advocate Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Claim_Outcome_Status__c</fullName>
        <description>The final status of the claim in the case item as determined by Advocate working the case item</description>
        <label>Claim Outcome Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Claim Adjusted</fullName>
                </value>
                <value>
                    <fullName>Claim Adjusted - No Additional Payment</fullName>
                </value>
                <value>
                    <fullName>Claim Partially Adjusted</fullName>
                </value>
                <value>
                    <fullName>Claim Upheld</fullName>
                </value>
                <value>
                    <fullName>Claim Upheld Adtl Information Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Number__c</fullName>
        <description>Internal UHC Member Identification number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Member Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Unresolved</fullName>
                    <default>true</default>
                    <label>Unresolved</label>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Process</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Pending Provider Information</fullName>
                </value>
                <value>
                    <fullName>Reopen</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Case Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <recordTypes>
        <fullName>PIR_Case_Items</fullName>
        <active>true</active>
        <description>Record type is created for Reactive and Proactive</description>
        <label>PIR Case Items</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PIR_Root_Cause_Case_Item__c.object
<CustomObject>
    <description>This object is used to store the root cause values of case on case items</description>
    <fields>
        <fullName>Case_Item__c</fullName>
        <description>this is look up field to case item object</description>
        <label>Case Item</label>
        <referenceTo>Case_Item__c</referenceTo>
        <relationshipName>PIR_Root_Cause_Case_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Root_Cause_1_Key_Code__c</fullName>
        <description>this field will store the root cause 1 Key Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 1 Key Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_1__c</fullName>
        <description>this field will store the root cause 1 value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_2_Key_Code__c</fullName>
        <description>this field will store the root cause 2 Key Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 2 Key Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_2__c</fullName>
        <description>this field will store the root cause 2 value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_3_Key_Code__c</fullName>
        <description>this field will store the root cause 3 Key Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 3 Key Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_3__c</fullName>
        <description>this field will store the root cause 3 value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_4_Key_Code__c</fullName>
        <description>this field will store the root cause 4 Key Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 4 Key Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_4__c</fullName>
        <description>this field will store the root cause 4 value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_5_Key_Code__c</fullName>
        <description>this field will store the root cause 5 Key Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 5 Key Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Root_Cause_5__c</fullName>
        <description>this field will store the root cause 5 value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Root Cause 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>PIR Root Cause Case Item</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>RootCause</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Root Cause Case Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACET_FAST_CaseItemTriggerHelperTest.cls
/*****************************************************************************************************
ACET_FAST_CaseItemTriggerHelperTest
Testing Class Name:  ACET_FAST_CaseItemTriggerHelper
Author: Shaik Mohammad Yaseen
Date: 09/05/2021
Description: This is test class and used to get test coverage for ACET_FAST_CaseItemTriggerHelper. 
Initial: Shaik Mohammad Yaseen
******************************************************************************************************/
@isTest(SeeAllData=false)
public class ACET_FAST_CaseItemTriggerHelperTest {
    public static testMethod void testCaseItemTrig(){
        Profile sysAdminPrf = ACET_Fast_TestDataFactory.getSysAdminPrf();
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        user sysAdminUser;
        System.runAs(thisUser){
            sysAdminUser = ACET_Fast_TestDataFactory.getUserRecord(sysAdminPrf.id);
            insert sysAdminUser;
        }
        case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
        insert caseRec;
        Id recordTypeId =Schema.SObjectType.Case_Item__c.getRecordTypeInfosByDeveloperName().get('PIR_Case_Items').getRecordTypeId();
        System.runAs(sysAdminUser){
            Case_Item__c cItem = new Case_Item__c(Case__c=caseRec.Id);
            citem.RecordTypeId = recordTypeId;
            cItem.ExternalID__c = '121221i2121';
            cItem.Member_Number__c = 'Test';
            cItem.Status__c='New';
            insert cItem;
            
            try{
                cItem.Status__c='Resolved';
                cItem.Claim_Outcome_Status__c = 'Claim Adjusted';
                cItem.Advocate_Comments__c= 'Test comments for feed';
                
                PIR_Root_Cause_Case_Item__c rcItem = new PIR_Root_Cause_Case_Item__c(Root_Cause_1__c='test1',
                                                                                     Root_Cause_1_Key_Code__c='test1code',
                                                                                     Root_Cause_2__c='test2',
                                                                                     Root_Cause_2_Key_Code__c='test2code',
                                                                                     Root_Cause_3__c='test3',
                                                                                     Root_Cause_3_Key_Code__c='test3code',
                                                                                     Root_Cause_4__c='test4',
                                                                                     Root_Cause_4_Key_Code__c='test4code',
                                                                                     Root_Cause_5__c='test5',
                                                                                     Root_Cause_5_Key_Code__c='test5code',
                                                                                     Case_Item__c=cItem.Id);
                PIR_Root_Cause_Case_Item__c rcItem2 = new PIR_Root_Cause_Case_Item__c(Root_Cause_1__c='test1',
                                                                                      Root_Cause_1_Key_Code__c='test1code',
                                                                                      Root_Cause_2__c='test2',
                                                                                      Root_Cause_2_Key_Code__c='test2code',
                                                                                      Root_Cause_3__c='test3',
                                                                                      Root_Cause_3_Key_Code__c='test3code',
                                                                                      Root_Cause_4__c='test4',
                                                                                      Root_Cause_4_Key_Code__c='test4code',
                                                                                      Root_Cause_5__c='test5',
                                                                                      Case_Item__c=cItem.Id);
                insert rcItem;
                insert rcItem2;
                update cItem;
            }
            catch(exception ex){
                system.debug('exception is '+ex.getMessage());
            }
        }
    }
    public static testMethod void testCaseItemTrig1(){
        Profile sysAdminPrf = ACET_Fast_TestDataFactory.getSysAdminPrf();
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        user sysAdminUser;
        System.runAs(thisUser){
            sysAdminUser = ACET_Fast_TestDataFactory.getUserRecord(sysAdminPrf.id);
            insert sysAdminUser;
        }
        case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
        insert caseRec;
        System.runAs(sysAdminUser){
            Case_Item__c cItem = new Case_Item__c(Case__c=caseRec.Id);
            cItem.Advocate_Comments__c = 'test';
            insert cItem;
            
            try{
                PIR_Root_Cause_Case_Item__c rcItem = new PIR_Root_Cause_Case_Item__c(Root_Cause_1__c='test1',
                                                                                     Root_Cause_1_Key_Code__c='test1code',
                                                                                     Root_Cause_2__c='test2',
                                                                                     Root_Cause_2_Key_Code__c='test2code',
                                                                                     Root_Cause_3__c='test3',
                                                                                     Root_Cause_3_Key_Code__c='test3code',
                                                                                     Root_Cause_4__c='test4',
                                                                                     Root_Cause_4_Key_Code__c='test4code',
                                                                                     Root_Cause_5__c='test5',
                                                                                     Root_Cause_5_Key_Code__c='test5code',
                                                                                     Case_Item__c=cItem.Id);
                insert rcItem;
                cItem.Advocate_Comments__c = 'test2';
                update cItem;
            }
            catch(exception ex){
                system.debug('exception is '+ex.getMessage());
            }
        }
    }
}