src/objects/Case_Item__c.object
<CustomObject>
    <description>Used to track tasks to be performed on single topic.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Number__c</fullName>
        <description>Internal number used for documentation on a call, claim adjustment, or external contact</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Original reference number from the first level service model failure</inlineHelpText>
        <label>Reference Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Case Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PIR_Resolution_Partner__c.object
<CustomObject>
    <description>It is used to store Resolution Partner information related to PIR (FAST/PIP) cases.</description>
    <fields>
        <fullName>Case_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Item</label>
        <referenceTo>Case_Item__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Resolution_Partner_Number__c</fullName>
        <description>Case Resolution Partner Number</description>
        <displayFormat>CRPN-{000000}</displayFormat>
        <label>Case Resolution Partner Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold Case record - #US2853220</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PIR Resolution Partners</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Store the comments of RP</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Days_Past_SLA__c</fullName>
        <description>To display the days its behind/ahead of the SLA.</description>
        <formula>FLOOR(TODAY() - SLA_Due_Date__c)</formula>
        <label>Days Past SLA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Escalation_Notes__c</fullName>
        <description>This field will hold Escalation Notes - #US2853220</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Escalation Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <formula>Case_Item__r.ExternalID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>External ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Reference_Number__c</fullName>
        <description>Store the reference number for this resolution partner.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Reference Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Matrix_Proactive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up to Provider Matrix record</description>
        <label>Internal Business Partner</label>
        <referenceTo>Provider_Matrix__c</referenceTo>
        <relationshipLabel>PIR Proactive RP</relationshipLabel>
        <relationshipName>PIR_Proactive_RP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Matrix_Reactive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up to Provider Matrix record</description>
        <label>Resolution Partners Name</label>
        <referenceTo>Provider_Matrix__c</referenceTo>
        <relationshipLabel>PIR Reactive RP</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resolution_Partner_Outcome__c</fullName>
        <description>#US2853220
Indicate whether the issue has been resolved by the resolution partner, or is still unresolved and must be sent back.</description>
        <label>Resolution Partner Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incorrect Route</fullName>
                </value>
                <value>
                    <fullName>Must Resend</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA_Completion_Date__c</fullName>
        <description>#US2853220
Date when they resolve this resolution partner</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SLA Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA_Due_Date__c</fullName>
        <description>SLA Due Date of the Resolution Partner.</description>
        <formula>SLA_Routed_Date__c+Provider_Matrix_Reactive__r.Resolution_Partner_SLA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA_Indicator__c</fullName>
        <description>Indicate icon based on SLA

Yellow icon = Open SLA
Green icon = Completed SLA
Red icon = SLA needs attention</description>
        <formula>IF(
(!ISBLANK( SLA_Completion_Date__c ) &amp;&amp; SLA_Completion_Date__c &lt; SLA_Due_Date__c &amp;&amp;  TEXT(Resolution_Partner_Outcome__c ) != &apos;Open&apos; ),
IMAGE(&quot;/img/msg_icons/confirm32.png&quot;, &quot;Status Indicator&quot;, 30, 30),
IF((SLA_Due_Date__c &gt; (TODAY()) &amp;&amp; TEXT(Resolution_Partner_Outcome__c ) == &apos;Open&apos;),
IMAGE(&quot;/img/msg_icons/warning32.png&quot;, &quot;Status Indicator&quot;, 30, 30),
IMAGE(&quot;/img/msg_icons/error32.png&quot;, &quot;Status Indicator&quot;, 30, 30)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Yellow icon = Open SLA
Green icon = Completed SLA
Red icon = SLA needs attention</inlineHelpText>
        <label>SLA Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Routed_Date__c</fullName>
        <description>#US2853220
Date when they route it to the resolution partner</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SLA Routed Date</label>
        <type>Date</type>
    </fields>
    <label>PIR Resolution Partner</label>
    <nameField>
        <displayFormat>PRP-{000000000}</displayFormat>
        <label>PIR Resolution Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIR_Resolution_Partners_Reference__c.object
<CustomObject>
    <description>It is used to store Reference number associated to the PIR Resolution Partners.</description>
    <fields>
        <fullName>Case_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Item Number</label>
        <referenceTo>Case_Item__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners References</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_Past_SLA__c</fullName>
        <formula>FLOOR(TODAY() - SLA_Due_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days Past SLA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIR_Resolution_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#US2853220 - Look up to RP record.</description>
        <label>PIR Resolution Partner</label>
        <referenceTo>PIR_Resolution_Partner__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners References</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Store the PR or Benefit OPS #</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Reference #</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Completion_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SLA Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA_Due_Date__c</fullName>
        <description>SLA Due Date of the Resolution Partner.</description>
        <formula>SLA_Routed_Date__c +  PIR_Resolution_Partner__r.Provider_Matrix_Reactive__r.Resolution_Partner_SLA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SLA Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLA_Indicator__c</fullName>
        <description>ndicate icon based on SLA

Yellow icon = Open SLA
Green icon = Completed SLA
Red icon = SLA needs attention</description>
        <formula>IF(
(!ISBLANK( SLA_Completion_Date__c ) &amp;&amp; SLA_Completion_Date__c &lt; SLA_Due_Date__c &amp;&amp; Completed__c == TRUE ),
IMAGE(&quot;/img/msg_icons/confirm32.png&quot;, &quot;Status Indicator&quot;, 30, 30),
IF((SLA_Due_Date__c &gt; (TODAY()) &amp;&amp; Completed__c == FALSE),
IMAGE(&quot;/img/msg_icons/warning32.png&quot;, &quot;Status Indicator&quot;, 30, 30),
IMAGE(&quot;/img/msg_icons/error32.png&quot;, &quot;Status Indicator&quot;, 30, 30)
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Yellow icon = Open SLA
Green icon = Completed SLA
Red icon = SLA needs attention</inlineHelpText>
        <label>SLA Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Routed_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SLA Routed Date</label>
        <type>Date</type>
    </fields>
    <label>PIR Resolution Partners Reference</label>
    <nameField>
        <displayFormat>PRPR-{000000000}</displayFormat>
        <label>PIR Resolution Partners Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Provider_Matrix__c.object
<CustomObject>
    <label>Provider Matrix</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_PIRResolutionParterCtrl.cls
/*****************************************************************************************************
ACET_FAST_PIRResolutionParterCtrl 
Test Class Name:  ACET_FAST_PIRResolutionParterCtrlTest
Author: Ratna Kumar Mukiri
Description: This class will provide the business logic for both aura Components ACET_FAST_PIRResolutionParteCmp and ACET_FAST_PIRResolutionParterdetails
Reference:US2941823 - FAST Case Permissions and Fields Validations
17/04/2021 - Ratna Kumar Mukiri - Initial
******************************************************************************************************/
public with sharing class ACET_FAST_PIRResolutionParterCtrl {
    
     @AuraEnabled 
    public static CaseItemWrapper getCaseItemRecord(string caseItemId){
       
        CaseItemWrapper caseItemWrap = new CaseItemWrapper();
        Case_Item__c caseItemRec = new Case_Item__c();
        if(caseItemId!='' && caseItemId!=null){
            caseItemRec=[SELECT Id,Name,ExternalID__c, Case__c,Reference_Number__c FROM Case_Item__c WHERE id=:caseItemId];
            caseItemWrap.caseItem = caseItemRec;
        }
   
        return caseItemWrap;
    }
    
    @AuraEnabled 
    public static void updateCaseItem(Case_Item__c caseItemRec){
    
        
      }
    @AuraEnabled
    public static PIR_Resolution_Partner__c getRPRecord(string caseItemRPRecId){
        PIR_Resolution_Partner__c caseItemRPRec = new PIR_Resolution_Partner__c();
        if(caseItemRPRecId!='' && caseItemRPRecId!=null){
            caseItemRPRec=[SELECT Id,Name,Case_Item__c,External_ID__c,createdby.name, Case__c, Escalation_Notes__c, SLA_Routed_Date__c,
                           Resolution_Partner_Outcome__c, SLA_Completion_Date__c,
                           SLA_Due_Date__c, Days_Past_SLA__c, Case_Resolution_Partner_Number__c,
                           Partner_Reference_Number__c, Comments__c, SLA_Indicator__c, Provider_Matrix_Reactive__c,Provider_Matrix_Reactive__r.Name, 
                           Provider_Matrix_Proactive__c FROM PIR_Resolution_Partner__c WHERE id=:caseItemRPRecId];
        }
        return caseItemRPRec;
    }

    @AuraEnabled
    public static PIR_Resolution_Partners_Reference__c getReferenceRecord(String caseItemRPRecId)
    {
        System.debug('check '+caseItemRPRecId);
         PIR_Resolution_Partners_Reference__c caseItemRPRec = new PIR_Resolution_Partners_Reference__c();
        if(caseItemRPRecId!='' && caseItemRPRecId!=null){
            caseItemRPRec=[SELECT Id,Name,CreatedBy.Name, SLA_Routed_Date__c,
                            SLA_Completion_Date__c,PIR_Resolution_Partner__c,CreatedById
                            FROM PIR_Resolution_Partners_Reference__c WHERE PIR_Resolution_Partner__c=:caseItemRPRecId];
        }
        return caseItemRPRec;
    }
    
    @AuraEnabled
    public static case getCaseRecord(string caseRecId){
        case caseRec = new case();
        if(caseRecId!='' && caseRecId!=null){
            caseRec=[SELECT id,RecordType.Name, CaseNumber,status,Case_Type__c,FAST_PIP_Markets__c,Original_Received_Date__c FROM Case WHERE id=:caseRecId];
        }
        return caseRec;
    }
  @AuraEnabled  
  public static PIR_Resolution_Partners_Reference__c  getRPRefrenceNumberRecord(String caseItemRefNoId)
  {
    PIR_Resolution_Partners_Reference__c caseItemRefNo = new PIR_Resolution_Partners_Reference__c();
        if(caseItemRefNoId!='' && caseItemRefNoId!=null){
            caseItemRefNo=[SELECT Id,Name,Case_Item__r.Name,Reference__c,SLA_Completion_Date__c,SLA_Routed_Date__c 
                                                  from PIR_Resolution_Partners_Reference__c WHERE Reference__c=:caseItemRefNoId ];
        }
        return caseItemRefNo;
    }   
 

  @AuraEnabled
  public static ACET_FAST_PIRResolutionParterCtrl.ResultWrapper validateRPRecord(ID prMatrixId,ID caseId){ 
  
     ACET_FAST_PIRResolutionParterCtrl.ResultWrapper finalResult = new  ACET_FAST_PIRResolutionParterCtrl.ResultWrapper();
       
    List<PIR_Resolution_Partner__c> rPRecord = new List<PIR_Resolution_Partner__c>();
      if(prMatrixId!=null && caseId!=null ){
         rPRecord=[SELECT Id,name, Case__c,Provider_Matrix_Reactive__r.Name from  PIR_Resolution_Partner__c where Case__c =:caseId and Provider_Matrix_Reactive__c =:prMatrixId];
       }  
      if(rPRecord.size()>0){
          finalResult.rpName = rPRecord[0].Name;
        finalResult.rpID = rPRecord[0].id;
       }
        return finalResult;
    
   }
      @AuraEnabled
     public static ACET_FAST_PIRResolutionParterCtrl.ResultWrapper getRPName(id recId){
        ACET_FAST_PIRResolutionParterCtrl.ResultWrapper finalResult = new  ACET_FAST_PIRResolutionParterCtrl.ResultWrapper();
        PIR_Resolution_Partner__c rpRec = [select id, Name from PIR_Resolution_Partner__c where id =: recId];
        finalResult.rpName = rpRec.Name;
        finalResult.rpID = rpRec.id;
        return finalResult;
    } 
      public class ResultWrapper{
        @AuraEnabled
        public string rpName{get;set;}
        @AuraEnabled
        public string rpID{get;set;}
    }
    public class CaseItemWrapper{
        @AuraEnabled
        public Case_Item__c caseItem;
        @AuraEnabled
        public String prNumber;
         @AuraEnabled
        public String prRefNumber;
        
    }
}