src/objects/Case_Item__c.object
<CustomObject>
    <description>Used to track tasks to be performed on single topic.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Case Item</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Case Item #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PIR_Resolution_Partner__c.object
<CustomObject>
    <description>It is used to store Resolution Partner information related to PIR (FAST/PIP) cases.</description>
    <fields>
        <fullName>Case_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Item</label>
        <referenceTo>Case_Item__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold Case record - #US2853220</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PIR Resolution Partners</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SLA_Routed_Date__c</fullName>
        <description>#US2853220
Date when they route it to the resolution partner</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SLA Routed Date</label>
        <type>Date</type>
    </fields>
    <label>PIR Resolution Partner</label>
    <nameField>
        <displayFormat>PRP-{000000000}</displayFormat>
        <label>PIR Resolution Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIR_Resolution_Partners_Reference__c.object
<CustomObject>
    <description>It is used to store Reference number associated to the PIR Resolution Partners.</description>
    <fields>
        <fullName>Case_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Item Number</label>
        <referenceTo>Case_Item__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners References</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIR_Resolution_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#US2853220 - Look up to RP record.</description>
        <label>PIR Resolution Partner</label>
        <referenceTo>PIR_Resolution_Partner__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners References</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Store the PR or Benefit OPS #</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Reference #</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA_Routed_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SLA Routed Date</label>
        <type>Date</type>
    </fields>
    <label>PIR Resolution Partners Reference</label>
    <nameField>
        <displayFormat>PRPR-{000000000}</displayFormat>
        <label>PIR Resolution Partners Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_ReferenceNumberTriggerTest.cls
@isTest
public class ACET_FAST_ReferenceNumberTriggerTest {
    
    public static testMethod void testWithFastUser(){
        Profile sysAdminPrf = ACET_Fast_TestDataFactory.getSysAdminPrf();
        user sysAdminUser = ACET_Fast_TestDataFactory.getUserRecord(sysAdminPrf.id);
        insert sysAdminUser;
        system.runAs(sysAdminUser){
     		case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
            insert caseRec;
            
            PIR_Resolution_Partner__c rPRecord =ACET_Fast_TestDataFactory.getPIRRPRec(caseRec.id);
            insert rPRecord;
            
            Case_Item__c casItem=new Case_Item__c (Case__c	=caseRec.id);
            insert casItem;
            PIR_Resolution_Partners_Reference__c casRPR=new PIR_Resolution_Partners_Reference__c(Case_Item__c=casItem.id,
                                                                                                 PIR_Resolution_Partner__c=rPRecord.id,
                                                                                                 Reference__c='1234');
            casRPR.SLA_Routed_Date__c = system.today();
            insert casRPR;
            PIR_Resolution_Partners_Reference__c casRPR1=new PIR_Resolution_Partners_Reference__c(Case_Item__c=casItem.id,
                                                                                                  PIR_Resolution_Partner__c=rPRecord.id,
                                                                                                  Reference__c='12324');
            casRPR1.SLA_Routed_Date__c = system.today() - 20;
            insert casRPR1;
            
            casRPR1.SLA_Routed_Date__c = system.today() - 40;
            update casRPR1;
        }
   
    }
    
}