src/objects/CHN_Qualified_Data__c.object
<CustomObject>
    <fields>
        <fullName>CHN_Qualified__c</fullName>
        <defaultValue>true</defaultValue>
        <label>CHN Qualified</label>
        <type>Checkbox</type>
    </fields>
    <label>EFS Qualified Data</label>
    <nameField>
        <displayFormat>EFSQ-{00000}</displayFormat>
        <label>EFS Qualified Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFS Qualified Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SENS_Publish__c.object
<CustomObject>
    <description>Stores the transactional data when there is a change in Designation, a new referral is made or a member opt-out of CHN.  This data is consumed by eVisor and OMNI</description>
    <fields>
        <fullName>CHN_Qualified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EFS Qualified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Family_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SENS Publish</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>SENS Publish Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SENS Publish</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/sensPublishCustomAPI_Test.cls
@isTest
public class sensPublishCustomAPI_Test{


    static testMethod void  getSensPublishDetailstTestMethod(){
        
        Sens_Publish__c  senPub = new Sens_Publish__c ();
        senPub.Family_Status__c = 'test';
        insert senPub;
        
        CHN_Qualified_Data__c chnqua = new CHN_Qualified_Data__c();
        chnqua.CHN_Qualified__c = true;
        insert chnqua;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();  
       
        req.httpMethod = 'GET';
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        sensPublishCustomAPI.getSensPublishDetails();       
        Test.stopTest(); 
       
    }

    static testMethod void  updateMethodTest(){
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();

        List<Sens_Publish__c>  senPubLst = new List<Sens_Publish__c>();
        Sens_Publish__c  senPub = new Sens_Publish__c ();
        senPub.Family_Status__c = 'test';
        senPubLst.add(senPub);
        insert senPubLst;
        Date dt = date.valueOf('1982-02-22');
        Map<String,String> bodySet = new Map<String,String>();
        bodySet.put('MemberId','2323232323');
        bodySet.put('PolicyId','1313131313');
        bodySet.put('DOB','1982-02-22');
        req.requestURI ='/services/apexrest/abc/xyz/';
        req.requestBody = Blob.valueOf(JSON.serializePretty(bodySet));
        
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        sensPublishCustomAPI.getSensMemberInfo();
        Test.stopTest();
    }
}