src/objects/Claim_Impact_Report_Form__c.object
<CustomObject>
    <description>Claim Impact Report object is used by CPM users, it will be capture the Report Information.</description>
    <fields>
        <fullName>Project_Details__c</fullName>
        <label>Project Details</label>
        <referenceTo>Project_Details__c</referenceTo>
        <relationshipLabel>Claim Impact Report Forms</relationshipLabel>
        <relationshipName>Claim_Impact_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Claim Impact Report Form</label>
    <nameField>
        <displayFormat>CPM-{00000000}</displayFormat>
        <label>Claim Impact Report Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Impact Report Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Details__c.object
<CustomObject>
    <description>This object is used to capture different types of Provider Claims under Case.</description>
    <fields>
        <fullName>Parent_Case__c</fullName>
        <label>Parent Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Provider_Claims</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CPM Project</label>
    <nameField>
        <displayFormat>PJD-{000000000}</displayFormat>
        <label>CPM Project Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPM Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project_Submission_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Project Submission Details</relationshipLabel>
        <relationshipName>Project_Submission_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Submission Detail</label>
    <nameField>
        <displayFormat>PSD-{000}</displayFormat>
        <label>Project Submission Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Submission Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ACETCPMCaseRouteControllerTest.cls
/*
ACETCPMCaseRouteControllerTest
Testing Class Name:  ACETCPMCaseRouteController
Author: Ganesh Medisetti
Date: 08/17/2020
Description: This is test class and used to get test coverage for ACETCPMCaseRouteController. 
Initial: Ganesh Medisetti
*/
@isTest
public class ACETCPMCaseRouteControllerTest {
	@isTest 
    public static void testFetchCsIdNBaseUrl() {
        Case cs = new Case(subject = 'Text');
        insert cs;
        Project_Submission_Detail__c sbd = new Project_Submission_Detail__c(case__c = cs.id);
        insert sbd;
		ACETCPMCaseRouteController.fetchCsIdNBaseUrl(string.valueOf(sbd.id));
        Project_Details__c projDetails = new Project_Details__c(Parent_Case__c = cs.id);
        insert projDetails;
        Claim_Impact_Report_Form__c cirf = new Claim_Impact_Report_Form__c(Project_Details__c = projDetails.Id);
        insert cirf;
        ACETCPMCaseRouteController.fetchCsIdNBaseUrl(cirf.id);
    }
}