src/objects/Document_Type__mdt.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WS_Field_Name__c</fullName>
        <label>WS Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Document Type</label>
    <pluralLabel>Document Types</pluralLabel>
</CustomObject>

src/objects/Document_Type_Field__mdt.object
<CustomObject>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>String</fullName>
                    <default>true</default>
                    <label>String</label>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
                <value>
                    <fullName>Boolean</fullName>
                </value>
                <value>
                    <fullName>Integer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                    <label>Text</label>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Id</fullName>
                </value>
                <value>
                    <fullName>Alphanumeric</fullName>
                </value>
                <value>
                    <fullName>Alphanumeric_Special_Characters</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WS_Field_Name__c</fullName>
        <label>WS Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Document Type Field</label>
    <pluralLabel>Document Type Fields</pluralLabel>
</CustomObject>

src/objects/Document_Type_Search_By_Field__mdt.object
<CustomObject>
    <fields>
        <fullName>Document_Type_Field__c</fullName>
        <label>Document Type Field</label>
        <referenceTo>Document_Type_Field__mdt</referenceTo>
        <relationshipLabel>Document Type Search By Fields</relationshipLabel>
        <relationshipName>Document_Type_Search_By_Fields</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <referenceTo>Document_Type__mdt</referenceTo>
        <relationshipLabel>Document Type Search By Fields</relationshipLabel>
        <relationshipName>Document_Type_Search_By_Fields1</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Document Type Search By Field</label>
    <pluralLabel>Document Type Search By Fields</pluralLabel>
</CustomObject>

src/classes/ACETSNIWorkOrderICUELetterController.cls
public class ACETSNIWorkOrderICUELetterController {
       public class ICUEResultWrapper{
        @AuraEnabled public ACET_ICUELetterResult resultWrapper {get;set;}
        @AuraEnabled public string message {get;set;}
        @AuraEnabled public integer statusCode {get;set;}
        @AuraEnabled public String indexName {get;set;}
    } 
     @AuraEnabled
    public static ICUEResultWrapper findICUELetter(String srnNumber,String documentType){      
        ICUEResultWrapper dataWrap = new ICUEResultWrapper();
        if(String.isNotBlank(documentType)) {
    		ICUEDocRequest icueRequest = new ICUEDocRequest();
    		List<Document_Type__mdt> docTypes = [SELECT Id,Label, Document_Type__c, WS_Field_Name__c FROM Document_Type__mdt where Document_Type__c = :documentType];
    		if(docTypes.size() > 0){
              	icueRequest.indexName =docTypes[0].WS_Field_Name__c;
            }
			List<Document_Type_Search_By_Field__mdt> lstSearchFilter = [SELECT Id, DeveloperName, Document_Type_Field__r.Label, Document_Type__r.Document_Type__c, Document_Type_Field__r.Field_Name__c, Document_Type_Field__r.Field_Type__c, Document_Type_Field__r.WS_Field_Name__c, Document_Type_Field__r.Data_Type__c, Document_type_Field__r.Operator__c FROM Document_Type_Search_By_Field__mdt where Document_Type__r.Document_Type__c=:documentType];
			if(!lstSearchFilter.isEmpty() && String.isNotBlank(srnNumber)) {
        	List<ICUEDocRequest.FilterClauses> FilterClausesLst = new List<ICUEDocRequest.FilterClauses>();
        	ICUEDocRequest.FilterClauses FilterClauses = new ICUEDocRequest.FilterClauses();
        	FilterClauses.type_Z = lstSearchFilter[0].Document_type_Field__r.Operator__c;
        	FilterClauses.name = lstSearchFilter[0].Document_Type_Field__r.WS_Field_Name__c;
        	FilterClauses.value = srnNumber;
        	FilterClausesLst.add(FilterClauses);
        	ICUEDocRequest.Criteria Criteria = new ICUEDocRequest.Criteria();
        	Criteria.filterClauses = FilterClausesLst;
        	icueRequest.Criteria = Criteria;
            System.debug(icueRequest);
            System.debug(documentType + srnNumber);
            ACETWSCalloutResult calloutResult = new ACETWSCalloutResult();
            ACET_ICUELetterResult responseResult = new ACET_ICUELetterResult();
            ACET_ICUELetterWS icueLetterWS = new ACET_ICUELetterWS('CHS',icueRequest); 
            if(icueRequest != null){
                calloutResult = icueLetterWS.findICUELetter(srnNumber);
                responseResult = (ACET_ICUELetterResult)calloutResult.Response;
            }
            dataWrap.resultWrapper = responseResult;
            dataWrap.message = calloutResult.Message;
            dataWrap.statusCode = calloutResult.statusCode;
            dataWrap.indexName = icueRequest.indexName;
        }
      }
        System.debug(dataWrap.resultWrapper);
        return dataWrap;
    }
    @AuraEnabled
    public static string getSearchParamValue (Id recordId,String searchField){
        System.debug(searchField);
        String sObjName = recordId.getSObjectType().getDescribe().getName();
        String searchParam;
        String query = 'SELECT Id,' +searchField+ ' from ' +sObjName+ ' where Id = \'' +recordId+ '\'';
        System.debug(query);
        List<sObject> sobjList = Database.query(query);
        if(!sobjList.isEmpty() && sobjList[0].get(searchField) != null) {
            searchParam  = (String) sobjList[0].get(searchField);
        }
        return searchParam;
    }
}