src/objects/EntitlementAssignment__c.object
<CustomObject>
    <fields>
        <fullName>CaseOrigin__c</fullName>
        <label>Case Origin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Inbound Correspondence</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Walk-In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EntitlementAssignmentExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EntitlementAssignmentExternalID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EntitlementName__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Entitlement Name</label>
        <referenceTo>Entitlement</referenceTo>
        <relationshipLabel>Entitlement Assignments</relationshipLabel>
        <relationshipName>Entitlement_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProfileName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>TTS_Access__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TTS Access</label>
        <referenceTo>TTS_Access__c</referenceTo>
        <relationshipLabel>Entitlement Assignments</relationshipLabel>
        <relationshipName>Entitlement_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TTS_ExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TTS_ExternalID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic1__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Topic</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type</valueSetName>
        </valueSet>
    </fields>
    <label>Entitlement Assignment</label>
    <nameField>
        <displayFormat>EA-{000000000}</displayFormat>
        <label>Entitlement Assignment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entitlement Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TTS_Access__c.object
<CustomObject>
    <description>access control to type and sub type from profile and role</description>
    <fields>
        <fullName>Limit_To_Profiles__c</fullName>
        <label>Limit To Profiles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ACET EB Agent</fullName>
                </value>
                <value>
                    <fullName>ACET Member</fullName>
                </value>
                <value>
                    <fullName>ACET Motion</fullName>
                </value>
                <value>
                    <fullName>ACET Provider</fullName>
                </value>
                <value>
                    <fullName>ECM Back Office Agent</fullName>
                </value>
                <value>
                    <fullName>Center for Health Navigation</fullName>
                </value>
                <value>
                    <fullName>Family Engagement Center - Read Only</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>OF CSR</fullName>
                </value>
                <value>
                    <fullName>Provider Claims</fullName>
                </value>
                <value>
                    <fullName>Provider Issue Resolution</fullName>
                </value>
                <value>
                    <fullName>Provider Service</fullName>
                </value>
                <value>
                    <fullName>Research User</fullName>
                </value>
                <value>
                    <fullName>SNI_ECM_Back_Office_Agent</fullName>
                </value>
                <value>
                    <fullName>SNI Member</fullName>
                </value>
                <value>
                    <fullName>System Administrator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Limit_To_Roles__c</fullName>
        <label>Limit To Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CSR Agent</fullName>
                </value>
                <value>
                    <fullName>Accounts Payable - Agent</fullName>
                </value>
                <value>
                    <fullName>Accounts Payable - Supervisor</fullName>
                </value>
                <value>
                    <fullName>ACET Front Office</fullName>
                </value>
                <value>
                    <fullName>Asian Initiatives B&amp;E Call Center - Agent</fullName>
                </value>
                <value>
                    <fullName>Asian Initiatives B&amp;E Call Center - Supervisor</fullName>
                </value>
                <value>
                    <fullName>Asian Initiatives Member - Agent</fullName>
                </value>
                <value>
                    <fullName>Asian Initiatives Member - Supervisor</fullName>
                </value>
                <value>
                    <fullName>B&amp;E Call Center/CST - Manager</fullName>
                </value>
                <value>
                    <fullName>B&amp;E Call Center/CST - Site Director</fullName>
                </value>
                <value>
                    <fullName>B&amp;E Call Center - Agent</fullName>
                </value>
                <value>
                    <fullName>B&amp;E Call Center - Customer Support Team</fullName>
                </value>
                <value>
                    <fullName>B&amp;E Call Center - Supervisor</fullName>
                </value>
                <value>
                    <fullName>Benefit Advocate - Agent</fullName>
                </value>
                <value>
                    <fullName>Benefit Advocate Customer Support Team - Agent</fullName>
                </value>
                <value>
                    <fullName>Benefit Advocate Customer Support Team - Supervisor</fullName>
                </value>
                <value>
                    <fullName>Benefit Advocate - Manager</fullName>
                </value>
                <value>
                    <fullName>Benefit Advocate - Site Director</fullName>
                </value>
                <value>
                    <fullName>Benefit Advocate - Supervisor</fullName>
                </value>
                <value>
                    <fullName>BES Senior Resolution Specialist</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>CART</fullName>
                </value>
                <value>
                    <fullName>Claims Research and Adjustments</fullName>
                </value>
                <value>
                    <fullName>Clinical - Agent</fullName>
                </value>
                <value>
                    <fullName>Clinical - Supervisor</fullName>
                </value>
                <value>
                    <fullName>Complex Medical Claims - Agent</fullName>
                </value>
                <value>
                    <fullName>Complex Medical Claims - Supervisor</fullName>
                </value>
                <value>
                    <fullName>Configuration - Agent</fullName>
                </value>
                <value>
                    <fullName>Configuration - Supervisor</fullName>
                </value>
                <value>
                    <fullName>CPM - Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <inlineHelpText>Leave blank if value access is controlled by the Type value</inlineHelpText>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Topic</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type</valueSetName>
        </valueSet>
    </fields>
    <label>TTS Access</label>
    <nameField>
        <displayFormat>TTSA-{000000000}</displayFormat>
        <label>TTSA #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TTS Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Subtype.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1099sa Reprint Request</fullName>
    </customValue>
    <customValue>
        <fullName>1st Level Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>1st Level Balanced Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Level, Over $300</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Level Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party bill pay/verify fnds</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Fee Waiver</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Fee Waiver WEX</fullName>
    </customValue>
    <customValue>
        <fullName>5498sa Reprint Request</fullName>
    </customValue>
    <customValue>
        <fullName>5500 Requests</fullName>
    </customValue>
    <customValue>
        <fullName>A&amp;G Determination</fullName>
    </customValue>
    <customValue>
        <fullName>Account Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Account Number Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Account Offering Change</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Rebuild</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulators</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Bill Pay</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Bill Pay WEX</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Return</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Return WEX</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal Fraud</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal WEX</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisitions</fullName>
    </customValue>
    <customValue>
        <fullName>Activation/PIN setup</fullName>
    </customValue>
    <customValue>
        <fullName>Activation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Active License(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete/Update</fullName>
    </customValue>
    <masterLabel>Subtype</masterLabel>
</GlobalValueSet>

src/globalValueSets/Topic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACC</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Receivable</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals &amp; Grievances</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Post Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Pre Service</fullName>
    </customValue>
    <customValue>
        <fullName>Balance Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Benefits and Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>CI</fullName>
    </customValue>
    <customValue>
        <fullName>Claims</fullName>
    </customValue>
    <customValue>
        <fullName>Coaching</fullName>
    </customValue>
    <customValue>
        <fullName>Commissions</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Accounts</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Option(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Coordination of Benefits</fullName>
    </customValue>
    <customValue>
        <fullName>Create Authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Create PCP Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Critical Condition Pre-emptive Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Debit Cards</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Drug Approval Status</fullName>
    </customValue>
    <customValue>
        <fullName>Email issues to be sent to the CSS team for handling/follow up</fullName>
    </customValue>
    <customValue>
        <fullName>Employer/Broker Other Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Enroll Member</fullName>
    </customValue>
    <customValue>
        <fullName>Enroll Subscriber</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated Call Backs</fullName>
    </customValue>
    <masterLabel>Topic</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Closure</fullName>
    </customValue>
    <customValue>
        <fullName>Account Maintenance/Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Account set up/Enrollment</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Rebuild</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Review</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Newborn (paper file only)</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information Needed</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>After Call Work- Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Alt Address</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative Medicine Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary Contracting</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Pre Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Status</fullName>
    </customValue>
    <customValue>
        <fullName>Apple</fullName>
    </customValue>
    <customValue>
        <fullName>Authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Behavioral Health</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Discrepancies</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Limitation Review</fullName>
    </customValue>
    <customValue>
        <fullName>BH Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Inquiry - Awaiting Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Issue</fullName>
    </customValue>
    <customValue>
        <fullName>C&amp;S Cosmos</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

src/classes/ECMEntitlementAssignmentHelper.cls
public with sharing class ECMEntitlementAssignmentHelper {
    
    public static final String ObjectName = 'EntitlementAssignment__c';

    private static List<String> assignmentFiledList;
    private static List<String> exculdeList = new List<String> {'CaseOrigin__c','TTS_Access__c','IsActive__c','ProfileName__c','EntitlementName__c',
                                                                'RoleName__c','TTS_ExternalID__c','Topic1__c','SortOrder__c'  ,'EntitlementAssignmentExternalID__c'     
                                                                };
    private static String assignmentFiled;
    static {
       //if(assignmentFiled == null){
                assignmentFiledList = new List<String>();
                assignmentFiled = ACETQueryUtil.consructCustomFieldQuery(ObjectName,exculdeList,assignmentFiledList);
            //}
        }

   
   /*
    Assign entitlement  id into case object
   */
    public static void assignEntitlementId(Case cas){
        ID entitlementId = null;
        String topic = '\''+ cas.Topic__c + '\'';
        User owner;
        //String query = assignmentFiled + ' where IsActive__c = true and Topic1__c =  '+ topic +'order by SortOrder__c asc' ;
        string TTSQueryString;
       // getting case owner ID
       try{
       List<User> owners = [Select userRole.parentRoleId,userRoleId,UserRole.Name,Profile.Name from User where id = : cas.OwnerId ];
       userRole parentRole ;
       userRole grandParentRole;
       if(owners.size() > 0){
        List<userRole> parentRolelist = [select Name,parentroleId from userRole where id =: owners[0].userRole.parentroleId LIMIT 1];
        if(parentRolelist.size() > 0){
            parentRole = parentRolelist[0];
            List<userRole> grandParentRolelist = [select Name,parentroleId from userRole where id =: parentRole.parentroleId LIMIT 1];
            grandParentRole = grandParentRolelist.size() > 0?grandParentRolelist[0]:null;
        }
       }
       if(cas.Type__c != null){
          
           if(cas.Subtype__c != null){          
               if(owners != null && owners[0].Profile != null && owners[0].Profile.Name != null && owners[0].Profile.Name != '' ){
                   TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\' AND Type__c =\''+ cas.Type__c +'\' AND Subtype__c = \''+cas.Subtype__c+'\' AND (Limit_To_Profiles__c INCLUDES (\''+owners[0].Profile.Name+'\') OR Limit_To_Profiles__c = null OR Limit_To_Roles__c INCLUDES (\''+ owners[0].UserRole.Name+'\') OR Limit_To_Roles__c INCLUDES (\''+ parentRole.Name+'\') OR Limit_To_Roles__c INCLUDES (\''+ grandParentRole.Name+'\') )';
               }else{
                   TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\' AND Type__c =\''+ cas.Type__c +'\' AND Subtype__c = \''+cas.Subtype__c+'\' ';
               }
           }else if(owners != null && owners[0].Profile != null && owners[0].Profile.Name != null && owners[0].Profile.Name != ''){
               TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\' AND Type__c =\''+ cas.Type__c +'\' AND (Limit_To_Profiles__c INCLUDES (\''+owners[0].Profile.Name+'\') OR Limit_To_Profiles__c = null OR Limit_To_Roles__c INCLUDES (\''+ owners[0].UserRole.Name+'\') OR Limit_To_Roles__c INCLUDES (\''+ parentRole.Name+'\') OR Limit_To_Roles__c INCLUDES (\''+ grandParentRole.Name+'\') )';
           }else{
               TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\' AND Type__c =\''+ cas.Type__c +'\' ';
           }
       }else{
               if(owners != null && owners.size() > 0 && owners[0].Profile != null && owners[0].Profile.Name != null && owners[0].Profile.Name != ''){
                   if(owners[0].UserRole != null && owners[0].UserRole.Name !=  null)
                       TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\' AND (Limit_To_Profiles__c INCLUDES (\''+owners[0].Profile.Name+'\') OR Limit_To_Profiles__c = null )';
                   else{
                       TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\' AND (Limit_To_Profiles__c INCLUDES (\''+owners[0].Profile.Name+'\') OR Limit_To_Profiles__c = null OR Limit_To_Roles__c INCLUDES (\''+ owners[0].UserRole.Name+'\') OR Limit_To_Roles__c INCLUDES (\''+ parentRole.Name+'\') OR Limit_To_Roles__c INCLUDES (\''+ grandParentRole.Name+'\'))';
                   } 
               }else{
                   TTSQueryString = 'Select id FROM TTS_Access__c WHERE Topic__c = \''+cas.Topic__c+'\'  ';
               }
        }
           
           system.debug('------TTSQueryString----->'+ TTSQueryString);
           List<TTS_Access__c> ttsList = Database.query(TTSQueryString);
           Set<Id> ttsIdset = new Set<Id>();
           system.debug('------ttsList----->'+ ttsList);
           for(TTS_Access__c tts:ttsList){
               ttsIdset.add(tts.Id);
           }
           system.debug('------ttsIdset----->'+ ttsIdset);
           String query = assignmentFiled + ' where IsActive__c = true and TTs_Access__c IN : ttsIdset order by SortOrder__c asc' ;
           map<id, userRole> userRoleMap = new map<id, userRole> ();
           if(owners != null && owners.size() > 0 ){
                set<id> currentAndparentRoleIds = new set<id>();
                for(user u : owners){
                    if(u.userRoleId != null){
                        currentAndparentRoleIds.add(u.userRoleId);
                    }
                    if(u.userRole.parentRoleId != null){
                        currentAndparentRoleIds.add(u.userRole.parentRoleId);
                    }
                }
                //getting parent, grand parent role id and Name
                set<id> roleIdsTillGrandParent = new set<id>();
                if(currentAndparentRoleIds.size() > 0){
                    for(UserRole ur : [select id, Name, parentRoleId from userRole where id In:currentAndparentRoleIds]){
                        roleIdsTillGrandParent.add(ur.id);
                        roleIdsTillGrandParent.add(ur.parentRoleId);
                    }
                }
                if(roleIdsTillGrandParent.size() > 0){
                    userRoleMap = new map<id, userRole>([select id, Name, parentRoleId from userRole where id In:roleIdsTillGrandParent]);
                }
                system.debug(userRoleMap);
           }
            
           if(owners.size() > 0) {
            
              owner = owners[0];
           }
            
            for(EntitlementAssignment__c entitlement:Database.query(query)){
               system.debug('-----Entitlement----->'+ entitlement); 
               if(isBasicCriteriaMatch(cas,entitlement,owner,userRoleMap) && isStandrdCaseFieldMatch(cas,entitlement)){
                     system.debug('-----1----->'+ entitlement); 
                     List<String> valueCheckList = getNotNulValuesForEntitlement(entitlement);
                     system.debug('-----2----->'+ valueCheckList); 
                     Integer index = 0;
                     for(String consField:valueCheckList) {
                            system.debug('-----3----->'+ valueCheckList); 
                            if(IsFieldAvliable(cas,consField) && entitlement.get(consField) == cas.get(consField)){
                                system.debug('-----4----->'+ valueCheckList); 
                                index++;
                            }else{
                                break;
                            }
                        }
                        system.debug('-----5----->'+ valueCheckList.size() +'<----->'+ index); 
                        if(valueCheckList.size() == index) {
                            cas.EntitlementId  = entitlement.EntitlementName__c;
                            return;
                        }
                }
                
            }
        
        }
        Catch(exception e){
        
        }
        
    }

  /*
   
    To Match the case owner basic information
  */
  public static boolean isBasicCriteriaMatch(Case cas,EntitlementAssignment__c entitlement, user casOwner,map<id, userRole> userRoleMap) {
     boolean isMatched = false;
     if(casOwner != null) {    
        
            Set<String> setOfEAProfiles = new Set<String>();
            Set<String> setOfEARoles = new Set<String>();
            
            if(entitlement.ProfileName__c != null){
                setOfEAProfiles = getUniqueValues(entitlement.ProfileName__c);
            }         
            if(entitlement.RoleName__c != null){
                setOfEARoles = getUniqueValues(entitlement.RoleName__c);
            }  
            system.debug('-----11----->'+ setOfEAProfiles +'<----->'+ setOfEARoles); 
            system.debug('-----11.1----->'+ setOfEAProfiles.contains(casOwner.Profile.Name) +'<----->'+ isMatchedWithCurrentOrParentOrGrandParentRole(entitlement,setOfEARoles,casOwner,userRoleMap) );   
            if ((entitlement.ProfileName__c == null  ||  setOfEAProfiles.contains(casOwner.Profile.Name)) && 
                ( isMatchedWithCurrentOrParentOrGrandParentRole(entitlement,setOfEARoles,casOwner,userRoleMap) )){
                    system.debug('-----12----->'+ setOfEAProfiles +'<----->'+ setOfEARoles);   
                    isMatched = true;
            }else if(entitlement.ProfileName__c == null && entitlement.RoleName__c == null  ){
                system.debug('-----13----->'+ setOfEAProfiles +'<----->'+ setOfEARoles);   
                isMatched = true;
            } 
     }
      return isMatched;
  }
  
  public static boolean isMatchedWithCurrentOrParentOrGrandParentRole(EntitlementAssignment__c entitlement,Set<String> setOfRouteRoles,user caseOwner,map<id, userRole> userRoleMap ){
        if(entitlement.RoleName__c == null){
            return true;
        }else if(setOfRouteRoles != null){
            id userRoleId = caseOwner.UserRoleId;            
            system.debug('-----21----->'+ userRoleId +'<----->'+ setOfRouteRoles);   
            if(userRoleId != null && userRoleMap.get(userRoleId) != null && setOfRouteRoles.contains(userRoleMap.get(userRoleId).Name )){
                return true;
            }else if(userRoleId != null && userRoleMap.get(userRoleId) != null && userRoleMap.get(userRoleId).parentRoleId != null){
                id parentRoleId = userRoleMap.get(userRoleId).parentRoleId;
                system.debug('-----22----->'+ parentRoleId +'<----->'+ userRoleMap.get(userRoleId));   
                if(userRoleMap.get(parentRoleId) != null && setOfRouteRoles.contains(userRoleMap.get(parentRoleId).Name)){
                    return true;
                }else if(parentRoleId != null && userRoleMap.get(parentRoleId) != null){
                    id grandParentRoleId = userRoleMap.get(parentRoleId).parentRoleId;
                    system.debug('-----23----->'+ grandParentRoleId +'<----->'+ userRoleMap.get(parentRoleId));   
                    if(userRoleMap.get(grandParentRoleId) != null && setOfRouteRoles.contains(userRoleMap.get(grandParentRoleId).Name)){
                        return true;
                    }
                }
            }       
        }
        return false;
    }
  
 
 /*
  To Match the standard case field match
 */
  public static boolean isStandrdCaseFieldMatch(Case cas,EntitlementAssignment__c entitlement) {
     boolean isMatched = false;
        if ((entitlement.CaseOrigin__c == null || entitlement.CaseOrigin__c == cas.Origin)){
             isMatched = true;
     }
      return isMatched;
  }
 
 
     /*
      Find the list of field need to check in EntitlementAssignment__c
      */ 
      private static List<String> getNotNulValuesForEntitlement(EntitlementAssignment__c entitlement) {
        List<String> valueCheckList = new List<String>();
        for(String consField:assignmentFiledList) {
    
                if(entitlement.get(consField) != null){
                    valueCheckList.add(consField);
                }
            }
            return valueCheckList;
      }
    
     /*
      Make sure Case object have field is avliable
     */
    public static boolean IsFieldAvliable(SObject sobj,String consColoumn) {
        String objName = String.valueOf(sobj.getsObjectType());
        return Schema.getGlobalDescribe().get(objName).getDescribe().fields.getMap().get(consColoumn)!=null;
     }

    /*
   method to convert String of ';' separated values list of unique values
    */
   private static Set<String> getUniqueValues(String inputString){
       list<String> listOfValues = new list<String>();
       set<String> uniqueValues = new set<String>();          
                  
       if(inputString.contains(';')){           
            listOfValues= inputString.split(';');
       }
       else{
            listOfValues.add(inputString);
       }                
       if(listOfValues.size() >0){      
            for(String str :listOfValues){  
                if(!uniqueValues.contains(str.trim())){ 
                    uniqueValues.add(str.trim());
                }                                           
            }                          
       }        
        return uniqueValues;    
    } 
    
}