src/objects/Family_Link_Rx_Medication__c.object
<CustomObject>
    <description>US2841187- this object will give the ability to view a family&apos;s medication in SENS and Family Link</description>
    <fields>
        <fullName>Directions__c</fullName>
        <description>This will give instructions on how to use the medication</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Directions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will link the Rx Medication to a family</description>
        <label>Family</label>
        <referenceTo>Family_Overview__c</referenceTo>
        <relationshipLabel>Family Link Rx Medications</relationshipLabel>
        <relationshipName>Family_Link_Rx_Medications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pharmacy_Phone_Number__c</fullName>
        <description>This will hold the phone number for the pharmacy that fills the prescription</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Pharmacy Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Pharmacy__c</fullName>
        <description>This will hold the pharmacy name that filled the prescription</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Pharmacy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pill_Size__c</fullName>
        <description>This will show the pill size for the medication</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Pill Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refill_Date__c</fullName>
        <description>This will hold the refill date on the Rx medication</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Refill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Rx_Number__c</fullName>
        <description>This will contain the id number for the prescription</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Rx Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This will determine whether the Rx Medication is active or not</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Link Rx Medication</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Link Rx Medications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SNI_FL_RxMedicationsController.cls
//US2841187: This apex class return the fields of Rx Meds Custom object associated with current Family
//Author Name : Derek DuChene
public class SNI_FL_RxMedicationsController {
	@AuraEnabled
    public static String getUserProfile(){
        Id profileId=userinfo.getProfileId();
        String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
        return profileName;
    }
    
    @AuraEnabled
    public static List<Family_Link_Rx_Medication__c> fetchRxMedications(String recordID)
    {
        List <Family_Link_Rx_Medication__c> fo = new  List <Family_Link_Rx_Medication__c>();
        try {
            if(recordID !=NULL)
            {
                fo= [select Id, Name, Pill_Size__c, Directions__c, Rx_Number__c, Refill_Date__c, Pharmacy__c, Pharmacy_Phone_Number__c from Family_Link_Rx_Medication__c where Status__c ='Active' and Family__c=: recordID order by CreatedDate desc];
                
            }
            return fo;
        }
        catch(Exception e){ return null;}
    }
    
    @AuraEnabled
    public static Family_Link_Rx_Medication__c editRxMed(Family_Link_Rx_Medication__c selRxMed) {
        if(selRxMed!=NULL) {
            upsert selRxMed;
        }
        return selRxMed;
    }
    
    @AuraEnabled
    public static Family_Link_Rx_Medication__c removeRxMed(Family_Link_Rx_Medication__c selRxMed) {
        if(selRxMed!=NULL) {
        	selRxMed.Status__c = 'Removed';
            upsert selRxMed;
        }
        return selRxMed;
    }
}