src/objects/Family_Story_Guide__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Offered</fullName>
                </value>
                <value>
                    <fullName>Offered</fullName>
                </value>
                <value>
                    <fullName>Declined (Not Interested)</fullName>
                </value>
                <value>
                    <fullName>Declined (Busy, Try Again)</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Partially Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Story Guide</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Story Guide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Story Guide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Story_Guide_Answers__c.object
<CustomObject>
    <fields>
        <fullName>Family_Story_Guide_Questionare__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Family Story Guide Questionare</label>
        <referenceTo>Family_Story_Guide_Questionare__c</referenceTo>
        <relationshipLabel>Family Story Guide Answers</relationshipLabel>
        <relationshipName>Family_Story_Guide_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Family_Story_Guide__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Family Story Guide</label>
        <referenceTo>Family_Story_Guide__c</referenceTo>
        <relationshipLabel>Family Story Guide Answers</relationshipLabel>
        <relationshipName>Family_Story_Guide_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Family Story Guide Answers</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Story Guide Answers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Story Guide Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Story_Guide_Questionare__c.object
<CustomObject>
    <fields>
        <fullName>QuestionNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question#</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Order__c</fullName>
        <label>Question Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A) Never</fullName>
                </value>
                <value>
                    <fullName>H) N/A</fullName>
                </value>
                <value>
                    <fullName>B) Sometimes</fullName>
                </value>
                <value>
                    <fullName>C) Usually</fullName>
                </value>
                <value>
                    <fullName>D) Always</fullName>
                </value>
                <value>
                    <fullName>A) Yes</fullName>
                </value>
                <value>
                    <fullName>B) No</fullName>
                </value>
                <value>
                    <fullName>A) Food</fullName>
                </value>
                <value>
                    <fullName>B) Medicine</fullName>
                </value>
                <value>
                    <fullName>C) Electricity</fullName>
                </value>
                <value>
                    <fullName>D) Heating or Air Conditioning</fullName>
                </value>
                <value>
                    <fullName>E) Mortgage or Rent</fullName>
                </value>
                <value>
                    <fullName>F) Transportation</fullName>
                </value>
                <value>
                    <fullName>I) None of the above</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insurance and Finance</fullName>
                </value>
                <value>
                    <fullName>Caregiver Support</fullName>
                </value>
                <value>
                    <fullName>Social Determinants</fullName>
                </value>
                <value>
                    <fullName>Experience with Providers</fullName>
                </value>
                <value>
                    <fullName>Education and Schools</fullName>
                </value>
                <value>
                    <fullName>Transition to Adulthood</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family Story Guide Questionare</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Family Story Guide Questionare Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family Story Guide Questionare</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETFamilyStoryGuideUIControllerTest.cls
@isTest
public class ACETFamilyStoryGuideUIControllerTest {
    @isTest
    public static void test1(){
         Family_Story_Guide__c fsg1 = ACETFamilyStoryGuideUIControllerTest.createFSG1();  
        Family_Story_Guide_Questionare__c qs1 = ACETFamilyStoryGuideUIControllerTest.createQuestion('Insurance and Finance',1.1,'1.1','A) Yes');
        Family_Story_Guide_Questionare__c qs2 = ACETFamilyStoryGuideUIControllerTest.createQuestion('Social Determinants',3.1,'3.1','A) Food');
        Family_Story_Guide_Questionare__c qs3 = ACETFamilyStoryGuideUIControllerTest.createQuestion('Social Determinants',3.1,'3.1','B) Medicine');
        Family_Story_Guide_Questionare__c qs4 = ACETFamilyStoryGuideUIControllerTest.createQuestion('Insurance and Finance',6.1,'6.1','B) No');
        Family_Story_Guide_Answers__c anw1 = ACETFamilyStoryGuideUIControllerTest.createANswer(fsg1.id,qs1.id);
		Family_Story_Guide_Answers__c anw2 = ACETFamilyStoryGuideUIControllerTest.createANswer(fsg1.id,qs2.id);
        list<string> lstStr = ACETFamilyStoryGuideUIController.getPickListValuesIntoList();
        
        List<ACETFamilyStoryGuideUIController.wrapperQuestions> lstWrap = ACETFamilyStoryGuideUIController.getTopicQuestions('Insurance and Finance');
        List<ACETFamilyStoryGuideUIController.wrapperQuestions> lstWrap1 = ACETFamilyStoryGuideUIController.getDefaultTopicQuestions();
        
        
        string fsg = ACETFamilyStoryGuideUIController.getFsgStatus(fsg1.id);
        list<string> lstStr1 = ACETFamilyStoryGuideUIController.getSavedInterventions(fsg1.id);
        list<Family_Story_Guide_Answers__c> lstAnsw =  ACETFamilyStoryGuideUIController.getSavedAnswers(fsg1.id);
        map<string,list<ACETFamilyStoryGuideUIController.wrapperAnswers>> mapansw = ACETFamilyStoryGuideUIController.forNotesSection(fsg1.id, new list<string>{'Insurance and Finance'});
		map<string,list<ACETFamilyStoryGuideUIController.wrapperAnswers>> mapansw1 = ACETFamilyStoryGuideUIController.forNotesSection(fsg1.id, new list<string>{'Social Determinants'});
        ACETFamilyStoryGuideUIController.saveDeleteAnswers(string.valueOf(fsg1.id),string.valueOf(qs1.id),'','','2.1');
        ACETFamilyStoryGuideUIController.saveDeleteAnswers(string.valueOf(fsg1.id),string.valueOf(qs2.id),'','','3.1');
		ACETFamilyStoryGuideUIController.saveDeleteAnswers(string.valueOf(fsg1.id),string.valueOf(qs2.id)+';'+string.valueOf(qs3.id),'','','3.1');
        ACETFamilyStoryGuideUIController.saveDeleteAnswers(string.valueOf(fsg1.id),string.valueOf(qs1.id),'','','6.1');
		ACETFamilyStoryGuideUIController.saveDeleteAnswers(string.valueOf(fsg1.id),string.valueOf(qs1.id),'','','6.2');
        ACETFamilyStoryGuideUIController.saveDeleteAnswers(string.valueOf(fsg1.id),string.valueOf(qs1.id),'','','1.3');
        list<string> lstcomplddata = ACETFamilyStoryGuideUIController.getCompletedData(fsg1.id);
    }
    public static Family_Story_Guide__c createFSG1(){
        Family_Story_Guide__c fsg = new Family_Story_Guide__c();
        fsg.Status__c = 'Not Offered';
        insert fsg;
        return fsg;
    }
    public static Family_Story_Guide_Questionare__c createQuestion(string topic,decimal qOrd, string qNum,string response){
        Family_Story_Guide_Questionare__c qs1 = new Family_Story_Guide_Questionare__c();
        qs1.Topic__c = topic;
        qs1.Question__c = 'Many families need help paying for healthcare needs. Insurance, government programs, private foundations and grants can be possible sources for such help. Have you had the opportunity to see if your child might be eligible for these kinds of supports?';
        qs1.Question_Order__c = qOrd;
        qs1.QuestionNumber__c = qNum;
        qs1.Response__c = response;
        insert qs1;
        return qs1;
    }
    public static Family_Story_Guide_Answers__c createANswer(string fsgId, string fsgQsid){
        Family_Story_Guide_Answers__c fsgAn = new Family_Story_Guide_Answers__c();
        fsgAn.Family_Story_Guide__c = fsgId;
        fsgAn.Family_Story_Guide_Questionare__c = fsgQsid;
        insert fsgAn;
        return fsgAn;
    }
}