src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Original_Received_Date__c</fullName>
        <description>Date that the original request was received.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the received date of the original request.</inlineHelpText>
        <label>Original Received Date</label>
        <type>Date</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PublishResult__c.object
<CustomObject>
    <description>This Object will hold the all Published platform events details</description>
    <fields>
        <fullName>CPU_Processing_Status__c</fullName>
        <description>Silk route:This will hold the Case CPU Processing Status values</description>
        <encryptionScheme>None</encryptionScheme>
        <label>CPU Processing Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventUid__c</fullName>
        <description>Silk route: Case id or associated Object id capture at this place</description>
        <encryptionScheme>None</encryptionScheme>
        <label>EventUid</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReplayId__c</fullName>
        <description>Silk route: Platform event unique number hold at this place</description>
        <label>ReplayId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PublishResult</label>
    <nameField>
        <displayFormat>PBR-{0000}</displayFormat>
        <label>PublishResult Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PublishResults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_TriageCmpCtrl.cls
public with sharing class ACET_FAST_TriageCmpCtrl {
    
  @AuraEnabled
  public static case getCaseRecord(string caseRecId){
        case caseRec = new case();
        if(caseRecId!='' && caseRecId!=null){
            caseRec=[SELECT id,RecordType.Name,CPU_Processing_Status__c,Interaction__c, CaseNumber,status,Case_Type__c,FAST_PIP_Markets__c,Original_Received_Date__c FROM Case WHERE id=:caseRecId];
        }
        return caseRec;
    }
    
  @AuraEnabled
  public static String publishPFEvent(case casRec){
      if(casRec.CPU_Processing_Status__c =='Case Items Partially Enriched'){
              ACET_FAST_PlatformEventsHandler.firePlatformEvent(new List<case>{casRec});
      }

    return string.valueOf([select id,ReplayId__c from PublishResult__c where EventUid__c=:casRec.id  order by ReplayId__c desc limit 1].ReplayId__c);
 }
}