src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <description>Interaction Type, as captured on the Explore page.</description>
        <label>Interaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Proactive Initiative</fullName>
                </value>
                <value>
                    <fullName>Walk-In</fullName>
                </value>
                <value>
                    <fullName>Inbound Correspondence</fullName>
                </value>
                <value>
                    <fullName>Research Only</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>SRS Resource Inquiry</fullName>
                </value>
                <value>
                    <fullName>SRS Escalated Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Group/Employer</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>UHG</fullName>
                </value>
                <value>
                    <fullName>Internal UHG Employee</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Agency/Broker</fullName>
                </value>
                <value>
                    <fullName>Group Contact</fullName>
                </value>
                <value>
                    <fullName>Other Originator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originator__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Originator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Interactions</relationshipLabel>
        <relationshipName>Interactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tst_Date_Field__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Field</label>
        <type>Date</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETMemberNotFoundController.cls
public with sharing class ACETMemberNotFoundController {
    public String InteractionType { get; set; }
    public String EmployerName {get;set;}
    public String GroupNumber {get;set;}
    public Date dateOfBirth { get; set; }
    public String LastName { get; set; }
    public String FirstName { get; set; }
    public String memberId { get; set; }
    public String zipcode { get; set; }
    public String State {get;set;}
    public String PhoneNumber {get;set;}
    public Interaction__c StartDate{get;set;}
     
    public Interaction__c  Interaction{get;set;}
    Public string NotFoundFLowName {get;set;}
    public ACETMemberNotFoundController() {
        StartDate = new Interaction__c();
        String InteractionId = ApexPages.currentPage().getParameters().get('InteractionId');        
        system.debug('------Interaction id---->'+InteractionId);
        string addInfo = ApexPages.currentPage().getParameters().get('additionalInfo');
            system.debug('!!!@@@addInfo'+addInfo);
        NotFoundFLowName = 'MemberNotFoundFlow';                
        if(InteractionId == '')
        {
        
            Interaction = new Interaction__c();
            InteractionType = ApexPages.currentPage().getParameters().get('IT');
            Interaction.Interaction_Type__c = InteractionType;
        }
        else
        {
            Interaction = ACETMemberQueryUtil.queryInteraction(interactionId);
        }
        //InteractionType = ApexPages.currentPage().getParameters().get('IT');        
        string dateString = ApexPages.currentPage().getParameters().get('DOB');
        if(dateString != '' && dateString != null){            
            StartDate.tst_Date_Field__c = date.parse(dateString);
            dateOfBirth = StartDate.tst_Date_Field__c;
        }
        memberId    = ApexPages.currentPage().getParameters().get('MID');
        zipcode     = ApexPages.currentPage().getParameters().get('zip');
        LastName    = ApexPages.currentPage().getParameters().get('LN');
        firstName   = ApexPages.currentPage().getParameters().get('FN');
        State       = ApexPages.currentPage().getParameters().get('ST');
        PhoneNumber = ApexPages.currentPage().getParameters().get('PH');
        EmployerName = ApexPages.currentPage().getParameters().get('EN');
        GroupNumber    = ApexPages.currentPage().getParameters().get('GN');
        
       /* system.debug(LoggingLevel.INFO, 'InteractionType: ' + InteractionType + ', ContactName: ' + ContactName + ', LastName: ' + LastName + ', FirstName: ' + FirstName);
        system.debug(LoggingLevel.INFO, ', TaxId: ' + TaxId + ', Npi: ' + Npi  + ', phoneNumber: ' + phoneNumber);*/
    }
    
    public PageReference RedirectFromMemberNotFound() {
        PageReference pageRef ;
        // logic for lastname + Phone number to be addded
        try {                        
            system.debug('all parameter : ' + InteractionType+memberId+zipcode+LastName+firstName+State+PhoneNumber+EmployerName+GroupNumber);   
            system.debug('------IN Pageref---->');
            String InteractionId = ApexPages.currentPage().getParameters().get('InteractionId');        
            string addInfo = ApexPages.currentPage().getParameters().get('additionalInfo');
            system.debug('!!!@@@addInfo'+addInfo);
            
            system.debug('!!!! Interaction'+InteractionId);  
            if(InteractionId == '' )
            {   
                system.debug('interaction !!!');
                Interaction =  ACETMemberQueryUtil.queryInteraction(InteractionType, Label.ACETProviderNotFoundOriginatorType,EmployerName, LastName, firstName, phoneNumber,StartDate.tst_Date_Field__c,state,zipcode,groupnumber,NotFoundFLowName);
                insert Interaction;
                system.debug('interaction !!!@@@'+Interaction);
            }
            else
           {
                Interaction = ACETMemberQueryUtil.queryInteractionMemInFocus(interactionId,InteractionType,Label.ACETProviderNotFoundOriginatorType,EmployerName, LastName, firstName, phoneNumber,StartDate.tst_Date_Field__c,state,zipcode,groupnumber,NotFoundFLowName);
           }
           
            //system.debug('------Pageref-Interaction--->'+ StartDate.tst_Date_Field__c);
            //system.debug(LoggingLevel.INFO, 'Interaction for Manual Member Created : ' + Interaction);            
            //string urlstr = '/apex/acetmemberdetail?lastName='+ Interaction.originator__r.Lastname + '&firstName=' + Interaction.originator__r.firstname + '&SRK=' + '&subjectdob=' +  Interaction.originator__r.birthdate + '&sourceOriginator= '+ Interaction.Originator_Type__c+ '&InteractionId='+ Interaction.Id +'&mnf=1&core.apexpages.devmode.url=1' ;
            //
            //pageRef = new PageReference(urlstr);
    
            pageRef = page.acetmemberdetail;
            pageRef.getParameters().put('mnf','1');
            pageRef.getParameters().put('mnfEmployerName',EmployerName);
            pageRef.getParameters().put('mnfzipcode',zipcode);
            pageRef.getParameters().put('mnfLastName',LastName);
            pageRef.getParameters().put('mnffirstName',firstName);
            pageRef.getParameters().put('mnfState',State);
            pageRef.getParameters().put('mnfPhoneNumber',PhoneNumber);
            pageRef.getParameters().put('mnfGroupNumber',GroupNumber);
            pageRef.getParameters().put('mnfDOB',String.valueOf(StartDate.tst_Date_Field__c));
            pageRef.getParameters().put('mnfMemberId', MemberId);
            pageRef.getParameters().put('additionalInfo',addInfo);
            pageRef.getParameters().put('InteractionId',Interaction.Id);
            system.debug('------Pageref---->'+ pageRef);
            //pageRef.getParameters().put('lastName',Interaction.originator__r.Lastname);
            //pageRef.getParameters().put('firstName',Interaction.originator__r.firstname);
            //pageRef.getParameters().put('subjectdob',date.valueOf(Interaction.originator__r.birthdate));
            
            //+'&IT='+InteractionType+'&LN='+lastName+'&FN='+firstName+'&PH='+phoneNumber+'&MID='+memberId+'&DOB='+dateOfBirth);
            pageRef.setRedirect(True);
        }
        catch (Exception ex) {
            system.debug(LoggingLevel.INFO, 'Error creating Interaction. Details: ' + ex.getMessage());
            pageRef=null;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, system.Label.ACETUnexpectedErrorMessage));
        }
       
        return pageRef;
    }
}