src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <description>This field is the Business Unit selected for this case for ETS-BE.</description>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CSS_SRT__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Business_Unit</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ISL_Webservice_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store ISL Webservice configuration values</description>
    <label>ISL Webservice Config</label>
</CustomObject>

src/objects/Material_Forms__c.object
<CustomObject>
    <description>This object is used to store blank forms for Material Request UI.</description>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member</fullName>
                    <default>true</default>
                    <label>Member</label>
                </value>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Category</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Document_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Document URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MRE__c</fullName>
        <description>Unique identifier for documents</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MRE#</label>
        <length>228</length>
        <type>Text</type>
    </fields>
    <label>Material Forms</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Materials Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FormHistoryControllerTest.cls
@istest
public class FormHistoryControllerTest {
	 static testMethod void ACETFormHistoryControllerTest1() {
        Map<String, String> TestISLWSConfigs = new Map<String, String>(); 
        TestISLWSConfigs.put('ISLConAccessToken', 'dfb379c2-06b7-46c4-8c6f-bbc390d1b854');
        TestISLWSConfigs.put('ISLOAuthContentType', 'application/x-www-form-urlencoded');
        TestISLWSConfigs.put('ISLOAuthGrantType', 'client_credentials');
        TestISLWSConfigs.put('OILHttpHeaderAccept', 'application/json;charset=UTF-8');
        TestISLWSConfigs.put('OILHttpHeaderActor', 'ACET');
        TestISLWSConfigs.put('OILHttpHeaderScope', 'read');
        TestISLWSConfigs.put('OILTimeout', '3000');
        TestISLWSConfigs.put('dev_ISLOAuthEndpoint', 'https://api-stg.optum.com:8443');
        TestISLWSConfigs.put('dev_findMedicalProviderAdapterEndpoint', '/api/alpha/eisl/fulfillment/order/v2.0/processFulfillment');
        List<ISL_Webservice_Config__c> lstISLWSConfigs = ACETTestDataUtility.CreateISLWebserviceConfigurations(TestISLWSConfigs);
        insert lstISLWSConfigs;
        
        StaticResource ResponseJSONSR = [SELECT Body FROM StaticResource WHERE Name = 'ACETProcessFulFillmentWebservice'];
        String ResponseJSON = ResponseJSONSR.Body.toString(); 
        system.debug(LoggingLevel.INFO, 'Response JSON: ' + ResponseJSON);
        
        Account oAccount = ACETTestDataUtility.CreateAccount('Test Account', 'TstTaxID1', 'TestEID1');
        insert oAccount;
        Contact oContact = ACETTestDataUtility.CreateContact(oAccount.Id, 'Test Contact LN', 'Test Contact FN', 'TstTaxID1', 'TestEID1', 'TestNPI1');
        insert oContact;
        Interaction__c oInteraction = ACETTestDataUtility.CreateInteraction(oContact.Id, 'Phone', 'Member', oContact.LastName);
        insert oInteraction;
        
        Material_Forms__c matform = new Material_Forms__c();
        matform.Document_Title__c = 'Test';
        matform.Document_URL__c = 'TESTURL';
        matform.Category__c = 'TEST FORMS';
        matform.MRE__c = '10700';
        matform.Business_Unit__c = 'Member';
        Insert matform;
        
        
        ACETHighlightsPanelAdditionalInfo AdditionalInfo = new ACETHighlightsPanelAdditionalInfo();
        AdditionalInfo.PolicyNumber = 'TestPolicyNumber';
        
        MockHttpCalloutResponseGenerator.MockHttpResponse OILTestResponse = new MockHttpCalloutResponseGenerator.MockHttpResponse(200, 'OK', ResponseJSON);
        OILTestResponse.TokenExpired = false;
        
        Test.startTest();
        
        
        
        PageReference pgRef = Page.ACETFormsHistory;
        Test.setCurrentPageReference (pgRef);
        
        ACETFormsHistoryController objCont = new ACETFormsHistoryController();
        
        
        
        objCont.BusinessUnit = 'Member';
        objCont.selectAddress = 'AddressOnFile';
        objCont.recepientId = '69688001800';
        objCont.idQualifier = 'MemberId';
        objCont.recipientType = 'Member';
        objCont.AddOnFilePersonWrap = new ACETFormsHistoryController.personWrapper();
        objCont.AddOnFilePersonWrap.personAddOne = 'Test 123';
        objCont.AddOnFilePersonWrap.personCity = 'HFD';
        objCont.AddOnFilePersonWrap.personState = 'CT';
        objCont.AddOnFilePersonWrap.personZipCode = '06484';
        objCont.AddOnFilePersonWrap.personFirstName = 'Test';
        objCont.AddOnFilePersonWrap.PersonLastName = 'Kelly';
        objCont.getMaterialForms();
        System.debug('test---->'+objCont.vListMaterialsForms);
        
        
        MockHttpCalloutResponseGenerator MockHttpResponse = new MockHttpCalloutResponseGenerator(null, OILTestResponse);
        Test.setMock(HttpCalloutMock.class, MockHttpResponse);
        
        //ApexPages.currentPage().getParameters().put('docId',JSON.serialize(new List<String>{'test123','test1234'}));
       // objCont.showbulkResend();
        objCont.btnSubmit();
        Test.Stoptest();
    
    }
    
}