src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Contact Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Admin_Type__c</fullName>
        <description>Customer admin type, based on the originator selected on the Explore page.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Admin Type</label>
        <length>90</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Event Type selected for the BEO case - US2580332</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Evt_Recvd_Dt_Time__c</fullName>
        <description>Event Received Date/Time, captured from the Explore page.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Received Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Interaction_Type__c</fullName>
        <description>Interaction Type, as captured on the Explore page.</description>
        <label>Interaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Portal</fullName>
                </value>
                <value>
                    <fullName>Proactive Initiative</fullName>
                </value>
                <value>
                    <fullName>Walk-In</fullName>
                </value>
                <value>
                    <fullName>Inbound Correspondence</fullName>
                </value>
                <value>
                    <fullName>Research Only</fullName>
                </value>
                <value>
                    <fullName>Outbound Call</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>SRS Resource Inquiry</fullName>
                </value>
                <value>
                    <fullName>SRS Escalated Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Originator_Email__c</fullName>
        <description>Originator Email, from the Explore page.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Originator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Originator_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Originator Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Originator_Type__c</fullName>
        <label>Originator Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provider</fullName>
                </value>
                <value>
                    <fullName>Member</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Group/Employer</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>UHG</fullName>
                </value>
                <value>
                    <fullName>Internal UHG Employee</fullName>
                </value>
                <value>
                    <fullName>Producer</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Agency/Broker</fullName>
                </value>
                <value>
                    <fullName>Group Contact</fullName>
                </value>
                <value>
                    <fullName>Other Originator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Admin_Type__c</fullName>
        <label>Other Admin Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Other_Admin_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Other_Admin_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Attorney</fullName>
    </customValue>
    <customValue>
        <fullName>Caregiver</fullName>
    </customValue>
    <customValue>
        <fullName>Collection Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Family/Friend/Spouse</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance Carrier</fullName>
    </customValue>
    <customValue>
        <fullName>Interpreter for Member</fullName>
    </customValue>
    <customValue>
        <fullName>Parent/Guardian/Custody Holder</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Representative</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Prospective Member</fullName>
    </customValue>
    <customValue>
        <fullName>Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Reporter</fullName>
    </customValue>
    <customValue>
        <fullName>State Regulatory Agent/Government Agency</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Options for Other Customer Admin Types for ETSBE</description>
    <masterLabel>Other Admin Type</masterLabel>
</GlobalValueSet>

src/classes/ETSBE_CaseAgeControllerTest.cls
@isTest
public class ETSBE_CaseAgeControllerTest {
    
    static testMethod void validateCaseAge() {        
        
        List<Case> caseList = new List<Case>();
        
        Case caseObj = new Case();
        caseObj.Event_Type__c = 'Standard';
        caseList.add(caseObj);
        
        Interaction__c interactObj = new Interaction__c();
        
        interactObj.Interaction_Type__c = 'Phone Call';
        interactObj.Evt_Recvd_Dt_Time__c = DateTime.newInstance(2020, 03, 26, 06, 00, 00);
        interactObj.Other_Admin_Type__c = 'Attorney';
        interactObj.Originator_Type__c = 'Other Admin';
        interactObj.Contact_Name__c = 'Willow Best';
        interactObj.Originator_Name__c = 'Willow Best';
        interactObj.Customer_Admin_Type__c = 'Other Admin';
        interactObj.Originator_Email__c = 'willow@uhc.com';
            
        insert interactObj;
        
        Case caseObj1 = new Case();
        caseObj1.Event_Type__c = 'Standard';
        caseObj1.Interaction__c = interactObj.Id;
        caseObj1.Is_Cloned__c = true;
        caseList.add(caseObj1);
        
        Case caseObj2 = new Case();
        caseObj2.Event_Type__c = 'Standard';
        caseObj2.Status = 'Closed';
        caseList.add(caseObj2);
        
        insert caseList;
        
        ETSBE_CaseAgeController.calculateCaseAge(caseObj.Id);
        ETSBE_CaseAgeController.calculateCaseAge(caseObj1.Id);
        ETSBE_CaseAgeController.calculateCaseAge(caseObj2.Id);
    }

}