src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Group_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Third_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Party</label>
        <referenceTo>Third_Party__c</referenceTo>
        <relationshipLabel>Interactions (Third Party)</relationshipLabel>
        <relationshipName>Interactions1_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <recordTypes>
        <fullName>Phone</fullName>
        <active>true</active>
        <label>Phone</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__mdt.object
<CustomObject>
    <label>State</label>
    <pluralLabel>States</pluralLabel>
</CustomObject>

src/objects/Third_Party__c.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>First Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Group Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <description>Last name for 80</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Last Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_PostalCode__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Mailing PostalCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mailing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Phone Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Third Party</label>
    <nameField>
        <displayFormat>TP #-{0000000000}</displayFormat>
        <label>Third Party #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Motion_AddIndividualController.cls
public class Motion_AddIndividualController {
    public Motion_AddIndividualController() {

    }
    public class MotionIndividualPickLists {
        @AuraEnabled public List<State> lstStatusValues{get;set;}
    }
    public class State implements Comparable{
        @AuraEnabled public String label{get;set;}
        @AuraEnabled public String value{get;set;}
 
        public State(String sLabel, String sValue){
            label = sLabel;
            value = sValue;
        }
        public Integer compareTo(Object objToCompare){
            return label.CompareTo(((State)objToCompare).label);
        }
    }    
    @AuraEnabled
    public static MotionIndividualPickLists motionAddIndividualPickListValues(){
        MotionIndividualPickLists mbrSearchLovs = new MotionIndividualPickLists();
        
        mbrSearchLovs.lstStatusValues = getStateValues();       
        return mbrSearchLovs;
    }
    public static List<State> getStateValues(){
        List<State> lstStatevalues = new List<State>();
        State objsts;
        for(State__mdt sts : [Select Id, MasterLabel,DeveloperName from State__mdt ORDER BY Masterlabel]){
            objsts = new State(sts.MasterLabel, sts.DeveloperName);
            lstStatevalues.add(objsts);
        }
        return lstStatevalues;    
    }
    /*@AuraEnabled 
    public static Interaction__c createThirdPartyRecord(String firstName, String lastName, string emailaddress, string phone, String groupname, string groupnumber, string dob, String state, string zip, string inttype){
        system.debug('$#$#$#'+dob);
        Interaction__c interaction;
            String fmtDOB = ACETLGT_CreateConstituents.formatDatewithslash(dob);

        //system.debug('fmtDOB'+fmtDOB);
        Third_Party__c thirdaccount = new Third_Party__c();
         thirdaccount = new Third_Party__c(
            LastName__c = lastName,
            First_Name__c   = firstName,
            Email__c = emailaddress,
            Phone_Number__c = phone,
            Group_Name__c = groupname,
            DOB__c = (fmtDOB != null?Date.valueOf(fmtDOB):null),
            Group_Number__c = groupnumber,
            Mailing_State__c = state,
            Mailing_PostalCode__c=zip
            
        );
        
        try{ 
        
                Database.insert(thirdaccount);
                
                if(thirdaccount.Id != null ){
                    interaction = MOTION_CreatePersonAccountInteractions.createInteraction(inttype, 'Other', null, thirdaccount.id);
                    
                    if(interaction.Id != null){
                        interaction= MOTION_CreatePersonAccountInteractions.queryInteraction(interaction.Id);
                        System.debug('Interaction record created successfully: '+ interaction.Id);
                    }
                }
           }catch(Exception ex){
                System.debug(ex.getMessage());
           }
  
        return interaction;
    }*/
}