src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Id_ANI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Caller Phone Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <description>This field will have the caller type</description>
        <label>Caller Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Assistant Controller</fullName>
                </value>
                <value>
                    <fullName>Chief Executive Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Financial Officer</fullName>
                </value>
                <value>
                    <fullName>Chief Operating Officer</fullName>
                </value>
                <value>
                    <fullName>Controller</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>General Agent</fullName>
                </value>
                <value>
                    <fullName>Member Note</fullName>
                </value>
                <value>
                    <fullName>Owner</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Primary Benefits Administrator</fullName>
                </value>
                <value>
                    <fullName>Primary Billing Administrator</fullName>
                </value>
                <value>
                    <fullName>Third Party</fullName>
                </value>
                <value>
                    <fullName>UHC Employee</fullName>
                </value>
                <value>
                    <fullName>Unlisted Contact</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Claim_Authorization_Referral_Number__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Claim/Authorization/Referral  Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_ID__c</fullName>
        <description>This field stores Group ID when originator is Producer/Group, and subject is Member.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Group ID</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Date_of_Birth__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Member Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Member ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TFN_Toll_Free_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TFN (Toll Free Number)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Tax_Id__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Provider Tax ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETVCCDUtility.cls
public class ACETVCCDUtility{
     public static Interaction__c populateVCCDInfo(Interaction__c intraction){
        String vccdParams = ApexPages.currentPage().getParameters().get('vccdParams');
        system.debug('vccdParams in VCCD utility '+vccdParams);
        if(vccdParams != null && vccdParams != ''){
            ACETVCCDInteractionInfo vccdInfo = (ACETVCCDInteractionInfo)JSON.deserialize(vccdParams,ACETVCCDInteractionInfo.class);
            system.debug('vccdInfo >>>> '+vccdInfo);
            if(vccdInfo.callerANI != null){
                intraction.Caller_Id_ANI__c = vccdInfo.callerANI;
            }
                
            intraction.Question_Type__c = vccdInfo.callTopic;
            intraction.TFN_Toll_Free_Number__c = vccdInfo.TFN;
            
            if(vccdInfo.CallerType == 'Member')
                intraction.id__c = vccdInfo.MemberID;
            else if(vccdInfo.CallerType == 'Provider' && vccdinfo.npi != '' && vccdinfo.npi != null )
                intraction.id__c = vccdInfo.MemberID;
            else if(vccdInfo.CallerType == 'Provider' && vccdinfo.TaxID != '' && vccdinfo.TaxID != null)
                intraction.id__c = vccdinfo.TaxID;
            else if(vccdInfo.CallerType == 'Group')
                intraction.id__c = vccdinfo.groupId;
            else if(vccdInfo.CallerType == 'Producer')
                intraction.id__c = vccdInfo.producerId;
                
            intraction.Caller_Type__c = vccdInfo.CallerType;
            if(vccdinfo.CallerID != null){
                intraction.Caller_Id_ANI__c = vccdinfo.CallerID;
            }

            if(vccdinfo.dob != null && vccdinfo.dob != '')
                intraction.Member_Date_of_Birth__c = Date.parse(vccdinfo.dob);//Date.valueof(vccdinfo.MemberDOB);
            intraction.Tax_Id__c = vccdinfo.TaxID;
            intraction.NPI__c = vccdinfo.npi;
            intraction.Member_Id__c = vccdinfo.MemberID;
            intraction.Caller_Type__c = vccdinfo.callerType;
            
            if(!String.isEmpty(vccdinfo.groupId)){
                 intraction.Group_ID__c = vccdinfo.groupId;
            }
            
            if(!String.isEmpty(vccdinfo.ReferralNumber)){
                 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.ReferralNumber;
            }
            if(!String.isEmpty(vccdinfo.AuthorizationNumber)){
                 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.AuthorizationNumber;
            }            
            if(!String.isEmpty(vccdinfo.ClaimID)){
                 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.ClaimID;
            }            
            
            
            
        }
        return intraction;
    }
    
    public static Interaction__c populateVCCDInfo(Interaction__c intraction, String vccdParams){
        system.debug('vccdParams in VCCD utility '+vccdParams);
        if(vccdParams != null && vccdParams != ''){
            ACETVCCDInteractionInfo vccdInfo = (ACETVCCDInteractionInfo)JSON.deserialize(vccdParams,ACETVCCDInteractionInfo.class);
            system.debug('vccdInfo >>>> '+vccdInfo);
            if(vccdInfo.callerANI != null){
                intraction.Caller_Id_ANI__c = vccdInfo.callerANI;
            }
                
            intraction.Question_Type__c = vccdInfo.callTopic;
            intraction.TFN_Toll_Free_Number__c = vccdInfo.TFN;
            
            if(vccdInfo.CallerType == 'Member')
                intraction.id__c = vccdInfo.MemberID;
            else if(vccdInfo.CallerType == 'Provider' && vccdinfo.npi != '' && vccdinfo.npi != null )
                intraction.id__c = vccdInfo.MemberID;
            else if(vccdInfo.CallerType == 'Provider' && vccdinfo.TaxID != '' && vccdinfo.TaxID != null)
                intraction.id__c = vccdinfo.TaxID;
            else if(vccdInfo.CallerType == 'Group')
                intraction.id__c = vccdinfo.groupId;
            else if(vccdInfo.CallerType == 'Producer')
                intraction.id__c = vccdInfo.producerId;
                
            intraction.Caller_Type__c = vccdInfo.CallerType;
            if(vccdinfo.CallerID != null){
                intraction.Caller_Id_ANI__c = vccdinfo.CallerID;
            }

            if(vccdinfo.dob != null && vccdinfo.dob != '')
                intraction.Member_Date_of_Birth__c = Date.parse(vccdinfo.dob);//Date.valueof(vccdinfo.MemberDOB);
            intraction.Tax_Id__c = vccdinfo.TaxID;
            intraction.NPI__c = vccdinfo.npi;
            intraction.Member_Id__c = vccdinfo.MemberID;
            intraction.Caller_Type__c = vccdinfo.callerType;
            
            if(!String.isEmpty(vccdinfo.groupId)){
                 intraction.Group_ID__c = vccdinfo.groupId;
            }
            
            if(!String.isEmpty(vccdinfo.ReferralNumber)){
                 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.ReferralNumber;
            }
            if(!String.isEmpty(vccdinfo.AuthorizationNumber)){
                 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.AuthorizationNumber;
            }            
            if(!String.isEmpty(vccdinfo.ClaimID)){
                 intraction.Claim_Authorization_Referral_Number__c = vccdinfo.ClaimID;
            }            
            
            
            
        }
        if(intraction != null)
        update intraction;
        
        return intraction;
    }
}