src/objects/Interaction__c.object
<CustomObject>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>NPI</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Interaction</label>
    <nameField>
        <displayFormat>INT-{0}</displayFormat>
        <label>Interaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/VCCD_Response__c.object
<CustomObject>
    <description>The Purpose of this object is to store incoming VCCD Request Details</description>
    <fields>
        <fullName>Ani__c</fullName>
        <description>The Purpose of this field is to Capture Contact Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Ani</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ClaimId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>MemberId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NPI</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ProductType</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>QuestionType</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubjectDOB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SubjectDOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TFN__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TFN</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TaxId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>VCCD Response</label>
    <nameField>
        <displayFormat>VCCD-{0000000000}</displayFormat>
        <label>VCCD Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VCCD Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_InteractionOverviewCtrl_Test.cls
@isTest
private class ACET_InteractionOverviewCtrl_Test {
    
    @isTest static void createInteraction_Test() {
        
        Test.startTest();
        ACET_ExplorePageCtrl.FlowDetails fd = new ACET_ExplorePageCtrl.FlowDetails();
        fd.contactExt = '123';
        fd.contactName = 'cfn cln';
        fd.contactNumber = '1234567890';
        fd.interactionType = 'Email';
        fd.isGenesys = false;
        fd.IVRInfo = null;
        fd.GeneysysQuestionType = '';

        ACET_ProviderSearchCtrl.ProviderDetails pd = new ACET_ProviderSearchCtrl.ProviderDetails();
        pd.isAdvancedSearch = true;
        pd.isValidProvider = false;
        pd.isProviderNotFound = false;
        pd.isNoProviderToSearch = true;
        pd.isOther = false;
        pd.isPysician = true;
        pd.practicingStatus = 'Active';
        pd.taxId = '';
        pd.npi = '1234567891';
        pd.firstName = 'pfn';
        pd.lastName = 'pln ';
        pd.filterType = 'Facility';
        pd.state = 'TX';
        pd.zip = 'NY';
        pd.state = '100001';
        pd.interactionType = 'Email';
        pd.providerUniqueId = '12345';
        pd.providerId = '12345';
        pd.phoneNumber = '1234567890';
        pd.contactType = '';

        ACET_MemberSearchCtrl.ExplorePageMemberDetailsResponse md = new ACET_MemberSearchCtrl.ExplorePageMemberDetailsResponse();
        md.dob = '01/01/1999';
        md.firstName = 'mfn';
        md.lastName = 'mln';
        md.groupNumber = '1234';
        md.isAdvancedSearch = true;
        md.isFindIndividualSearch = false;
        md.isMemberNotFound = false;
        md.isNoMemberToSearch = false;
        md.isValidMember = true;
        md.memberId = '12345';
        md.memberUniqueId = '12345';
        md.payerId = '123456';
        md.phoneNumber = '1234567890';
        md.searchOption = 'MemberIdDOB';
        md.state = 'TX';
        md.zip = '100001';
        
        VCCD_Response__c VCCDRecord = new VCCD_Response__c();
        VCCDRecord.TaxId__c = '';
        VCCDRecord.ProductType__c = '';
        VCCDRecord.TFN__c = '';
        VCCDRecord.Ani__c = '';
        VCCDRecord.MemberId__c = '';
        VCCDRecord.NPI__c = '';
        VCCDRecord.QuestionType__c = '';
        VCCDRecord.ClaimId__c = '';
        VCCDRecord.SubjectDOB__c = System.today();
        Insert VCCDRecord;
        
        Interaction__c interactionRecord = TestDataFactory.createInteraction();
        
        ACET_InteractionOverviewCtrl.getHippaGuideLinesUrl();
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, false, VCCDRecord.Id);
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, true, VCCDRecord.Id);
        ACET_InteractionOverviewCtrl.updateInteraction(fd, pd, interactionRecord.Id, true, VCCDRecord.Id);
        
        md.isValidMember = false;
        md.isMemberNotFound = true;
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, true, VCCDRecord.Id);
        ACET_InteractionOverviewCtrl.updateInteraction(fd, pd, interactionRecord.Id, true, VCCDRecord.Id);
        
        pd.isNoProviderToSearch = false;
        pd.isValidProvider = true;
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, true, VCCDRecord.Id);
        ACET_InteractionOverviewCtrl.updateInteraction(fd, pd, interactionRecord.Id, true, VCCDRecord.Id);
        
        pd.isValidProvider = false;
        pd.isProviderNotFound = true;
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, true, VCCDRecord.Id);
        ACET_InteractionOverviewCtrl.updateInteraction(fd, pd, interactionRecord.Id, true, VCCDRecord.Id);
        
        pd.isProviderNotFound = false;
        pd.isOther = true;
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, true, VCCDRecord.Id);
        ACET_InteractionOverviewCtrl.updateInteraction(fd, pd, interactionRecord.Id, true, VCCDRecord.Id);
        //US2903847
        fd.isGenesys = true;
        Map<String,Object> IVRInfoMap = new Map<string,Object>{'QuestionType__c'=>'C1','SubjectDOB__c'=>'19660116'};
        fd.IVRinfo = IVRInfoMap;
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, false,'');
        Map<String,Object> IVRInfoMap2 = new Map<string,Object>{'QuestionType__c'=>'C1','SubjectDOB__c'=>'1966-01-16'};
        fd.IVRinfo = IVRInfoMap2;
        ACET_InteractionOverviewCtrl.createInteraction(fd, pd, md, false,'');

        Test.stopTest();
    }

}