src/objects/ISL_Webservice_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store ISL Webservice configuration values</description>
    <fields>
        <fullName>ACET_Common_Name__c</fullName>
        <description>Name of record without org prefix</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Example for QA record qa_getDocument, &quot;getDocument&quot; would be the ACET Common Name</inlineHelpText>
        <label>ACET Common Name</label>
        <length>34</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ISL Webservice Config</label>
</CustomObject>

src/classes/ACETGetSNIApiAccessTokenBatchTest.cls
@isTest
public class ACETGetSNIApiAccessTokenBatchTest {
    @isTest
    
    public static void testMethod1(){
       
         Test.setMock(HttpCalloutMock.class, new MockHttpTokenResponseGenerator('empty'));
        Database.executeBatch(new ACETGetSNIApiAccessTokenBatch());
    }
     @isTest
    public static void testMethod2(){
          ISL_Webservice_Config__c newCustomSetting = new ISL_Webservice_Config__c();
            newCustomSetting.Name = 'SNIAPIAccessToken';
            newCustomSetting.Value__c = '';
			newCustomSetting.ACET_Common_Name__c = 'SNIApiEndpoint';
        insert newCustomSetting;
          Test.setMock(HttpCalloutMock.class, new MockHttpTokenResponseGenerator('response'));
        Database.executeBatch(new ACETGetSNIApiAccessTokenBatch());
       
    }
     @isTest
    public static void testMethod3(){
       ACETGetSNIAPIAccessTokenScheduler obj = new ACETGetSNIAPIAccessTokenScheduler();
        SchedulableContext sc;
        obj.execute(sc);
    }
    @isTest
    public static void testMethod4(){
          ISL_Webservice_Config__c newCustomSetting = new ISL_Webservice_Config__c();
            newCustomSetting.Name = 'SNIAPIAccessToken';
            newCustomSetting.Value__c = '';
			newCustomSetting.ACET_Common_Name__c = 'SNIApiEndpoint';
        insert newCustomSetting;
          Test.setMock(HttpCalloutMock.class, new MockHttpTokenResponseGenerator('expiry'));
        Database.executeBatch(new ACETGetSNIApiAccessTokenBatch());
       
    }
    
}