src/objects/Milestone_Performance__c.object
<CustomObject>
    <description>This object&apos;s records allow reporting to track performance. The records of this object will be attached to a case and case owners</description>
    <fields>
        <fullName>ActualMilestoneCompletionDateTime__c</fullName>
        <description>Actual milestone completion date (in date/time format)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ActualMilestoneMinutestoComplete__c</fullName>
        <description>Current milestone&apos;s completion date - previous milestone&apos;s completion date</description>
        <label>Completion Minutes</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completion_Time_DDD_HH_MM__c</fullName>
        <description>Completion time is convert to Business day hours and minutes</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Completion Time (DDD:HH:MM)</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MilestoneStartDateTime__c</fullName>
        <description>Milestone&apos;s Start date and time</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PlannedMilestoneMinutestoComplete__c</fullName>
        <description>Current Milestone&apos;s minutes to complete - previous milestone&apos;s minutes to complete</description>
        <label>Target Minutes</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Time_DDD_HH_MM__c</fullName>
        <description>Calculate Business days hours and minutes for target time</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Target Time (DDD:HH:MM)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variance_Time_DDD_HH_MM__c</fullName>
        <description>Variance is calculated difference between target date and completion date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Variance Time (DDD:HH:MM)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Milestone Performance</label>
    <nameField>
        <displayFormat>MPN - {00000000}</displayFormat>
        <label>Milestone Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ECMBusinessHoursUtilTest.cls
@isTest
private class ECMBusinessHoursUtilTest{

    /*
    Assumption Memeber call center is avliable in org.And timzone is ET
    Sunday  No Hours
    Monday  8:00 AM to  6:00 PM
    Tuesday 8:00 AM to  6:00 PM
    Wednesday   8:00 AM to  6:00 PM
    Thursday    8:00 AM to  6:00 PM
    Friday  8:00 AM to  6:00 PM
    Saturday    No Hours

    */
    private static BusinessHours getBusinessHours() {
          List<BusinessHours> bhs=[select id from BusinessHours where name = 'Member Call Center'];
       //System.assert(bhs.size()==1);
       return bhs[0];
    }
    

    @isTest
    static void testTargetDatePopulation() {
        Milestone_Performance__c msp = null;
        BusinessHours bs = getBusinessHours();
        
        ECMBusinessHoursUtil.setBusinessCalculation(bs.id,msp);
         msp = new Milestone_Performance__c ();
        msp.MilestoneStartDateTime__c = Datetime.newInstance(2017, 5, 4, 10, 32, 13);
        msp.PlannedMilestoneMinutestoComplete__c = 661;
        ECMBusinessHoursUtil.setBusinessCalculation(bs.id,msp);
    
        //System.assertEquals('1 Day : 1 Hour : 1 Minute',msp.Target_Time_DDD_HH_MM__c);
    }

    @isTest
    static void tesCompletionDatePopulation() {
        BusinessHours bs = getBusinessHours();
        Milestone_Performance__c msp = new Milestone_Performance__c ();
        msp.MilestoneStartDateTime__c = Datetime.newInstance(2017, 5, 4, 10, 32, 13);
        msp.ActualMilestoneCompletionDateTime__c = Datetime.newInstance(2017, 5, 4, 10, 32, 13);
        msp.PlannedMilestoneMinutestoComplete__c = 1400;
        ECMBusinessHoursUtil.setBusinessCalculation(bs.id,msp);
        //System.assertEquals('0 Day :  0 Hour : 0 Minute',msp.Completion_Time_DDD_HH_MM__c);
        msp.ActualMilestoneMinutestoComplete__c  = 1395;
        ECMBusinessHoursUtil.setBusinessCalculation(bs.id,msp);
        //System.debug(msp);
        //System.assertEquals('2 Days : 3 Hours : 15 Minutes',msp.Completion_Time_DDD_HH_MM__c);
        //System.assertEquals('- 0 Day :  0 Hour : 5 Minutes',msp.Variance_Time_DDD_HH_MM__c);
        
    }

    @isTest
    static void tesVarianceDatePopulation() {
        BusinessHours bs = getBusinessHours();
        Milestone_Performance__c msp = new Milestone_Performance__c ();
        msp.MilestoneStartDateTime__c = Datetime.newInstance(2017, 5, 4, 6, 32, 13);
        msp.ActualMilestoneCompletionDateTime__c = Datetime.newInstance(2017, 5, 4, 10, 32, 13);
        msp.PlannedMilestoneMinutestoComplete__c = 1400;
        ECMBusinessHoursUtil.setBusinessCalculation(bs.id,msp);
        msp.ActualMilestoneMinutestoComplete__c  = 1405;
        ECMBusinessHoursUtil.setBusinessCalculation(bs.id,msp);
        //System.assertEquals('0 Day :  0 Hour : 5 Minutes',msp.Variance_Time_DDD_HH_MM__c);
    }
}