src/objects/Mock_Response_Details__c.object
<CustomObject>
    <fields>
        <fullName>FileName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>File Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchParameter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Search Parameter</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebserviceConfigurations__c</fullName>
        <label>Webservice Configurations</label>
        <referenceTo>WebserviceConfigurations__c</referenceTo>
        <relationshipName>Mock_Response_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Mock Response Details</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Mock Response Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock Response Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Organization_Properties__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Organization Properties</label>
</CustomObject>

src/objects/OrgSpecificConfigurations__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnableMock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Mock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EndpointDomain__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebserviceConfigurations__c</fullName>
        <label>Webservice Configurations</label>
        <referenceTo>WebserviceConfigurations__c</referenceTo>
        <relationshipLabel>Org Specific Configurations</relationshipLabel>
        <relationshipName>OrgSpecificConfigurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Org Specific Configurations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Specific Configurations</pluralLabel>
    <recordTypes>
        <fullName>ServiceAPI</fullName>
        <active>true</active>
        <label>Service API</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WebserviceConfigurations__c.object
<CustomObject>
    <fields>
        <fullName>AuthorizationToken__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Authorization Token</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GrantType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Grant Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Headers__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Headers</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Webservice Configurations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Webservice Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webservice Configurations</pluralLabel>
    <recordTypes>
        <fullName>Service_API</fullName>
        <active>true</active>
        <label>Service API</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_ContractExceptionsController_Test.cls
@isTest
public class ACET_ContractExceptionsController_Test {
    @testSetup static void setupCS(){
        Organization_Properties__c orgProps = Organization_Properties__c.getOrgDefaults();
        orgProps.OrganizationName__c = 'slayerdev';
        Upsert orgProps;
        
        WebserviceConfigurations__c  webConRelatedDocuments = new WebserviceConfigurations__c ();
        webConRelatedDocuments.GrantType__c  = 'client_credentials';
        webConRelatedDocuments.Headers__c  = '[{"key":"Authorization","value":"Bearer <:AUTH_TOKEN:>"},{"key":"Content-Type","value":"application/json"},{"key":"actor","value":"ACET"}]';
        webConRelatedDocuments.AuthorizationToken__c  = 'SELECT AuthorizationToken__c FROM WebserviceConfigurations__c WHERE Name = \'LinkServiceTokenAPIToken\'';
        webConRelatedDocuments.Method__c  = 'GET';
        webConRelatedDocuments.Name  = 'LinkFacilityContractExceptions';
        webConRelatedDocuments.Timeout__c = 10000;
        RecordType recTypeWebExtendedServiceAPI = [SELECT Id FROM RecordType WHERE DeveloperName = 'Service_API' and SObjectType = 'WebserviceConfigurations__c'];
        webConRelatedDocuments.RecordTypeId  = recTypeWebExtendedServiceAPI.id;
          
        insert webConRelatedDocuments;
        
        OrgSpecificConfigurations__c orgSpecServicenAPI = new OrgSpecificConfigurations__c();
        RecordType recTypeOrgServiceAPI = [SELECT Id FROM RecordType WHERE DeveloperName = 'ServiceAPI' and SObjectType = 'OrgSpecificConfigurations__c'];
        orgSpecServicenAPI.RecordTypeId  = recTypeOrgServiceAPI.Id;
        orgSpecServicenAPI.EndpointDomain__c = 'https://gateway-stage.optum.com/elink-extended/api/networkStatus/v3.';
        orgSpecServicenAPI.ClientId__c = 'test';
        orgSpecServicenAPI.ClientSecret__c = 'a723ef27-493b-4afa-2d43-43542cc87rf3';
        orgSpecServicenAPI.EnableMock__c=true;
        orgSpecServicenAPI.Name='slayerdev';
        orgSpecServicenAPI.WebserviceConfigurations__c = webConRelatedDocuments.Id;
        insert orgSpecServicenAPI; 
        
        List<Mock_Response_Details__c> mockResponseRecList = new List<Mock_Response_Details__c>();
        Mock_Response_Details__c mockResponseRec=new Mock_Response_Details__c();
        mockResponseRec.Status_Code__c='200';
        mockResponseRec.FileName__c='ContractExceptions';
        mockResponseRec.SearchParameter__c='ContractExceptions';
        mockResponseRec.WebserviceConfigurations__c = webConRelatedDocuments.id;
        mockResponseRecList.add(mockResponseRec);
        
        //insert mockResponseRecList;
    }
    static testMethod void testParse() {
        Test.startTest();
        String requestBody='{}';
        ACET_ContractExceptions_Json2Apex.parse(requestBody);
        Test.stopTest();
    }
    static testMethod void testgetContractExceptions() {
        ACET_ContractExceptionsController a = new ACET_ContractExceptionsController();
        ACET_ContractExceptionsController.getContractExceptions('000287049','351611050','134565534');
    }
}