src/objects/Organization_Properties__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>OrganizationName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Organization Properties</label>
</CustomObject>

src/objects/OrgSpecificConfigurations__c.object
<CustomObject>
    <fields>
        <fullName>EndpointDomain__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Endpoint Domain</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeText__c</fullName>
        <description>Source of truth for Record Type to be applied to the record. This field is a migratable version of Record Type that is used by ACET_OrgSpecificConfigsTrigger to update the actual records&apos; Record Type based on the value of this field.</description>
        <inlineHelpText>Source of truth for Record Type to be applied to the record. This field is a migratable version of Record Type that is used by ACET_OrgSpecificConfigsTrigger to update the actual records&apos; Record Type based on the value of this field.</inlineHelpText>
        <label>RecordTypeText</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ServiceAPI</fullName>
                </value>
                <value>
                    <fullName>TokenAPI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WebserviceConfigurations__c</fullName>
        <label>Webservice Configurations</label>
        <referenceTo>WebserviceConfigurations__c</referenceTo>
        <relationshipLabel>Org Specific Configurations</relationshipLabel>
        <relationshipName>OrgSpecificConfigurations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Org Specific Configurations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Org Specific Configurations</pluralLabel>
    <recordTypes>
        <fullName>TokenAPI</fullName>
        <active>true</active>
        <label>Token API</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WebserviceConfigurations__c.object
<CustomObject>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GET</fullName>
                </value>
                <value>
                    <fullName>POST</fullName>
                </value>
                <value>
                    <fullName>PUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecordTypeText__c</fullName>
        <description>Source of truth for Record Type to be applied to the record. This field is a migratable version of Record Type that is used by ACET_WebserviceConfigTrigger to update the actual records&apos; Record Type based on the value of this field.</description>
        <inlineHelpText>Source of truth for Record Type to be applied to the record. This field is a migratable version of Record Type that is used by ACET_WebserviceConfigTrigger to update the actual records&apos; Record Type based on the value of this field.</inlineHelpText>
        <label>RecordTypeText</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Service_API</fullName>
                </value>
                <value>
                    <fullName>Token_API</fullName>
                </value>
                <value>
                    <fullName>Authorization_Token</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Webservice Configurations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Webservice Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webservice Configurations</pluralLabel>
    <recordTypes>
        <fullName>Token_API</fullName>
        <active>true</active>
        <label>Token API</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ADBMedicalClaimsDetailControllerTest.cls
@isTest
public class ADBMedicalClaimsDetailControllerTest {
    @testSetup static void setup() {
        Test.startTest();
        List<WebserviceConfigurations__c> configs = new List<WebserviceConfigurations__c>{
            new WebserviceConfigurations__c(Name = 'ADBMedicalClaimsEndpoint',recordtypeText__c = 'Token_API', Method__c = 'POST', Timeout__c = 10000)
                };
                    insert configs;
        
        List<OrgSpecificConfigurations__c> orgConfigs = new List<OrgSpecificConfigurations__c>{
            new OrgSpecificConfigurations__c(WebserviceConfigurations__c = configs[0].Id,recordtypeText__c = 'TokenAPI',Name = 'QA',EndpointDomain__c = 'https://gateway-stage.optum.com')
                };
                    insert orgConfigs;
        
        Organization_Properties__c property = new Organization_Properties__c(OrganizationName__c = 'QA');
        insert property;
        Test.stopTest();
    }
    @isTest static void testMedicalClaims (){
        String userId = 'pchinnol'; 
        String memberId = 'S994061057'; 
        String policy = '0701648';
        String firstName  = 'RAJIV'; 
        String relationship = 'RR';
        String consumerApplication = 'Acet';
        test.startTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('ADBMedicalClaimsMockResponse');
        mock.setStatusCode(200);
        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);
        ADBMedicalClaimsDetailController.getMedicalClaims(userId, memberId, policy, firstName, relationship, consumerApplication);
        
        test.stopTest(); 
    }
        
    @isTest static void testMedicalClaimsError (){
        String userId = 'pchinnol'; 
        String memberId = 'S994061057'; 
        String policy = '0701648';
        String firstName  = 'RAJIV'; 
        String relationship = 'RR';
        String consumerApplication = 'Acet';
        test.startTest();
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('ADBMedicalErrorResponse');
        mock.setStatusCode(200);
        // Set the mock callout mode
        Test.setMock(HttpCalloutMock.class, mock);
        ADBMedicalClaimsDetailController.getMedicalClaims(userId, memberId, policy, firstName, relationship, consumerApplication);
        test.stopTest(); 
    }
    
    @isTest static void  testADBMedicalClaimResponseWrapper(){
        test.startTest();
       	String val = '{"searchResult": { "searchOutput": { "claims": [{ "firstServiceDate": "2021-01-13", "lastServiceDate": "2021-01-13", "claimType": "PHYSICIAN", "providerTaxId": "390806261", "providerName": "KERI S CHANEY", "providerTier": "I", "totalPatientResponsibility": "255.72", "providerSpecialty": "D" } ] } } } }';
        ADBMedicalClaimResponseWrapper.parse(val);
    	test.stopTest();
    }
}