src/objects/PC_CustomException__mdt.object
<CustomObject>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PC_CustomException</label>
    <pluralLabel>PC_CustomExceptions</pluralLabel>
</CustomObject>

src/classes/GenericException.cls
/**
 * @name         :  GenericException
 * @description  :  This is a Generic custom base Exception class. 
 * 					This will give proper error messages and code for any custom exception which extends this class.
 * @author       :  Bhanu Jain
 * @createddate  :  9/17/2018
 **/
public with sharing  virtual class GenericException extends Exception{

	public override String getMessage() {
		PC_CustomException__mdt ge = [Select message__c, error_code__c from PC_CustomException__mdt where developername = :getTypeName() OR developername = :'GenericException'  limit 1];
		return ge.message__c ;
	}

}