src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SNI_FL_Care_Team_Member__c.object
<CustomObject>
    <description>This Object is created for SNI Family Link Portal to save the care team members</description>
    <fields>
        <fullName>SNI_FL_Added_Date__c</fullName>
        <description>This field holds the date of the member added to the Family Link Portal</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Added Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Family__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the family account related to care team member</description>
        <label>Family</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Care Team</relationshipLabel>
        <relationshipName>SNI_FL_CareTeam_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Invited_Date__c</fullName>
        <description>This field holds the family Member Invited Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Invited Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field holds the person Account related to the care team member</description>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Care Team(Member)</relationshipLabel>
        <relationshipName>SNI_FL_CareTeam_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Non_Policy_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This fields holds the value whether the member is from the policy or not</description>
        <label>Non-Policy Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Not_Visible_in_Familylink__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This fields gets checked when a member is to be removed from the care team and not visible in the family link</description>
        <label>Not Visible in Care Advisor Connect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Primary_Caregiver__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field holds the value whether the member is the Primary Caregiver(Family Link Account Owner)</description>
        <label>Family Account Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Registered_Date__c</fullName>
        <description>This field holds the registered date of the care team member</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Registered Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SNI_FL_Status__c</fullName>
        <description>This hold the status of the care team member</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Added</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Registered</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SNI FL Care Team Member</label>
    <nameField>
        <displayFormat>CT - {00000}</displayFormat>
        <label>CareTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SNI_FL_AddFamilyMemController.cls
public without sharing class SNI_FL_AddFamilyMemController {
    @AuraEnabled
    public static void getCareTeamMembers(string firstName,string lastName,date dateOfBirth,string famId,string memId){
        system.debug('getCareTeamMembers------');
        system.debug('getCareTeamMembers---memId-----'+memId);
        try{
		    list<account> lstAcc;
            if(famId != null ){
                lstAcc = [select id,ownerid from account where id =: famId ];
            }
            if(memId == null || memId == ''){
                Id personAccRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Individual').getRecordTypeId();
                Account personAccount = new Account();
                personAccount.PersonBirthdate = date.valueOf(dateOfBirth);
                personAccount.firstName = firstName;
                personAccount.lastName = lastName;
                personAccount.RecordTypeId = personAccRecordTypeId;
				if(lstAcc != null && lstAcc.size()>0){
                   personAccount.OwnerId = lstAcc[0].ownerid;
                }
                insert personAccount;
                system.debug('getCareTeamMembers----personAccount--'+personAccount.id);
                if(personAccount.id != null){
                    SNI_FL_Care_Team_Member__c careTeam = new SNI_FL_Care_Team_Member__c();
                    careTeam.SNI_FL_Family__c = famId;
                    careTeam.SNI_FL_Member__c=personAccount.id;
                    careTeam.SNI_FL_Status__c='Added';
                    careTeam.SNI_FL_Added_Date__c=System.today();
                    //careTeam.SNI_FL_Invited_Date__c=System.today()-1;
                    //careTeam.SNI_FL_Registered_Date__c=System.today();
                    careTeam.SNI_FL_Primary_Caregiver__c=false;
                    careTeam.SNI_FL_Non_Policy_Member__c=true;
                    careTeam.SNI_FL_Not_Visible_in_Familylink__c = false;
                    insert careTeam;
                    system.debug('getCareTeamMembers----careTeam--'+careTeam.id);
                }
            }
            else{
                Account personAccount = new Account();
                personAccount.id = memId;
                personAccount.PersonBirthdate = date.valueOf(dateOfBirth);
                personAccount.firstName = firstName;
                personAccount.lastName = lastName;
				if(lstAcc != null && lstAcc.size()>0){
                   personAccount.OwnerId = lstAcc[0].ownerid;
                }
                update personAccount;
            }
        }
        Catch(Exception e){
        }
    }
}