src/objects/PHI_Access_Log__c.object
<CustomObject>
    <description>PHI Access Log on detail pages</description>
    <fields>
        <fullName>Access_Location__c</fullName>
        <label>Access Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Producer Detail</fullName>
                </value>
                <value>
                    <fullName>Member Detail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>EID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSN__c</fullName>
        <description>Capture the SSN value from masking,unmasking and copy future.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SSN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SSN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PHI Access Log</label>
    <nameField>
        <displayFormat>PHI-{0000}</displayFormat>
        <label>PHI Access Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PHI Access Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACETLGT_MaskSSNController.cls
public class ACETLGT_MaskSSNController {
	
    @AuraEnabled
    public static PHI_Access_Log__c insertEventLog(String constituentType, String category, String memId, String SSNValue){
        string coverages;
        PHI_Access_Log__c  PHIlog = new PHI_Access_Log__c ();  
        PHIlog.Access_Location__c  = constituentType;
        PHIlog.Type__c  = category;
        PHIlog.EID__c  = memId;
        PHIlog.SSN__c  = SSNValue;
        insert PHIlog;
        return PHIlog;
    }
}