src/objects/PIR_Resolution_Partner__c.object
<CustomObject>
    <description>It is used to store Resolution Partner information related to PIR (FAST/PIP) cases.</description>
    <fields>
        <fullName>Resolution_Partner_Outcome__c</fullName>
        <description>#US2853220
Indicate whether the issue has been resolved by the resolution partner, or is still unresolved and must be sent back.</description>
        <label>Resolution Partner Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incorrect Route</fullName>
                </value>
                <value>
                    <fullName>Must Resend</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PIR Resolution Partner</label>
    <nameField>
        <displayFormat>PRP-{000000000}</displayFormat>
        <label>PIR Resolution Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_HomePage_RPCtrlTest.cls
/*************************************************************************************************************
 * @name      ACET_FAST_HomePage_RPCtrlTest
 * @author      kvalakon <karthik@optum.com>
 * @created      11 / 09 / 2020
 * @description    Test class for ACET_FAST_HomePage_RPCtrl.
 *
 * Changes (version)
 * -----------------------------------------------------------------------------------------------------------
 *         No.    Date              Author          Description
 *         ----  ------------  --------------------  ----------------------------------------------
 * @version    1.0    2020-09-11    kvalakon        Initial
 *
**************************************************************************************************************/
@isTest
public class ACET_FAST_HomePage_RPCtrlTest {
    @testSetup
    public static void testData()
    {
       
        case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
        insert caseRec;
        PIR_Resolution_Partner__c rpRec = ACET_Fast_TestDataFactory.getPIRRPRec(caseRec.id);
        rpRec.Resolution_Partner_Outcome__c = 'Open';
        insert rpRec;
       
        case caseRec1 = ACET_Fast_TestDataFactory.getCaseRecord('Proactive_Action','Open');
        insert caseRec1;
        PIR_Resolution_Partner__c rpRec1 = ACET_Fast_TestDataFactory.getPIRRPRec(caseRec1.id);
        rpRec1.Resolution_Partner_Outcome__c = 'Open';
        insert rpRec1;
    }
	
    static testMethod void getData(){
        testData();
         
        ACET_FAST_HomePage_RPCtrl.resolutionData();
        ACET_FAST_HomePage_RPCtrl.getProactiveRPRec();
        ACET_FAST_HomePage_RPCtrl.getUserDetails();
    }
}