src/objects/PIR_Resolution_Partner__c.object
<CustomObject>
    <description>It is used to store Resolution Partner information related to PIR (FAST/PIP) cases.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold Case record - #US2853220</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>PIR Resolution Partners</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Matrix_Reactive__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>look up to Provider Matrix record</description>
        <label>Resolution Partners Name</label>
        <referenceTo>Provider_Matrix__c</referenceTo>
        <relationshipLabel>PIR Reactive RP</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PIR Resolution Partner</label>
    <nameField>
        <displayFormat>PRP-{000000000}</displayFormat>
        <label>PIR Resolution Partner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PIR_Resolution_Partners_Reference__c.object
<CustomObject>
    <description>It is used to store Reference number associated to the PIR Resolution Partners.</description>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Store the status of the Reference</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PIR_Resolution_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#US2853220 - Look up to RP record.</description>
        <label>PIR Resolution Partner</label>
        <referenceTo>PIR_Resolution_Partner__c</referenceTo>
        <relationshipLabel>PIR Resolution Partners References</relationshipLabel>
        <relationshipName>PIR_Resolution_Partners_References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Store the PR or Benefit OPS #</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Reference #</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>PIR Resolution Partners Reference</label>
    <nameField>
        <displayFormat>PRPR-{000000000}</displayFormat>
        <label>PIR Resolution Partners Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PIR Resolution Partners References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Provider_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Resolution_Partner_SLA__c</fullName>
        <label>Resolution Partner SLA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Provider Matrix</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_RPRefInlineEditCtrlTest.cls
/*****************************************************************************************************
ACET_FAST_RPRefInlineEditCtrlTest
Testing Class Name:  ACET_FAST_RPRefInlineEditCtrl
Author: Shaik Mohammad Yaseen
Date: 31/03/2021
Description: This is test class and used to get test coverage for ACET_FAST_RPRefInlineEditCtrl. 
Initial: Shaik Mohammad Yaseen
******************************************************************************************************/
@isTest
public class ACET_FAST_RPRefInlineEditCtrlTest {
    public static testMethod void inlineEditTestMethod(){
        Profile sysAdminPrf = ACET_Fast_TestDataFactory.getSysAdminPrf();
        user sysAdminUser = ACET_Fast_TestDataFactory.getUserRecord(sysAdminPrf.id);
        insert sysAdminUser;
        System.runAs(sysAdminUser){
            case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
            insert caseRec;              
            
            Provider_Matrix__c pmRec = new Provider_Matrix__c();
            pmRec.Name = 'Test RP';
            pmRec.Resolution_Partner_SLA__c = 20;
            insert pmRec;
            
            PIR_Resolution_Partner__c rp = new PIR_Resolution_Partner__c();
            rp.Case__c = caseRec.id;
            rp.Provider_Matrix_Reactive__c = pmRec.Id;
            insert rp;
            
            List<PIR_Resolution_Partners_Reference__c> rpRefListToInsert = new List<PIR_Resolution_Partners_Reference__c>();
            
            PIR_Resolution_Partners_Reference__c rpRef1 = new PIR_Resolution_Partners_Reference__c();
            rpRef1.PIR_Resolution_Partner__c = rp.id;
            rpRef1.Reference__c = 'qwerty';
            rpRef1.Completed__c = true;
            rpRefListToInsert.add(rpRef1);
            
            PIR_Resolution_Partners_Reference__c rpRef2 = new PIR_Resolution_Partners_Reference__c();
            rpRef2.PIR_Resolution_Partner__c = rp.id;
            rpRef2.Reference__c = 'qwerty';
            rpRef2.Completed__c = true;
            rpRefListToInsert.add(rpRef2);
            
            insert rpRefListToInsert;
            
            ACET_FAST_RPRefInlineEditCtrl.fWrapper fWrap = ACET_FAST_RPRefInlineEditCtrl.getReferences(rp.Id);
            fWrap.pRefWrapList[0].selectedCheckBox= true;
            ACET_FAST_RPRefInlineEditCtrl.completeSelected(fWrap.pRefWrapList,rp.Id);
            ACET_FAST_RPRefInlineEditCtrl.deleteSelected(fWrap.pRefWrapList,rp.Id);
        }
    }
}