src/objects/Provider_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>LOB__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appeals and Grievances</fullName>
                </value>
                <value>
                    <fullName>Appeals Issues</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Authorizations</fullName>
                </value>
                <value>
                    <fullName>BCCI</fullName>
                </value>
                <value>
                    <fullName>BCO (Benefit Configuration Operations)</fullName>
                </value>
                <value>
                    <fullName>Bridge</fullName>
                </value>
                <value>
                    <fullName>Check/TRACR</fullName>
                </value>
                <value>
                    <fullName>Claim Operations</fullName>
                </value>
                <value>
                    <fullName>Claims Resolution</fullName>
                </value>
                <value>
                    <fullName>Claims Resolution Oxford</fullName>
                </value>
                <value>
                    <fullName>Clinical</fullName>
                </value>
                <value>
                    <fullName>COB</fullName>
                </value>
                <value>
                    <fullName>COB/Eligibility</fullName>
                </value>
                <value>
                    <fullName>Contracting and Pricing</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
                <value>
                    <fullName>CRT</fullName>
                </value>
                <value>
                    <fullName>CSP DROID Macro</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Data Entry</fullName>
                </value>
                <value>
                    <fullName>Dedicated Accounts</fullName>
                </value>
                <value>
                    <fullName>EDI</fullName>
                </value>
                <value>
                    <fullName>Eligibility</fullName>
                </value>
                <value>
                    <fullName>Escalated Exceptions</fullName>
                </value>
                <value>
                    <fullName>Exceptions - Provider &amp; Contract</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Genetics</fullName>
                </value>
                <value>
                    <fullName>Health Plan</fullName>
                </value>
                <value>
                    <fullName>High Dollar Claim Review</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CrossWalk_Case_RPI__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CrossWalk Case RPI</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LOB__c</fullName>
        <label>LOB</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C&amp;S</fullName>
                </value>
                <value>
                    <fullName>E&amp;I</fullName>
                </value>
                <value>
                    <fullName>M&amp;R</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>**SME &amp; MANAGER USE ONLY** OptumHealth BH Claims - COSMOS</fullName>
                </value>
                <value>
                    <fullName>1st Level Reconsideration Letters (sent via LetGen)</fullName>
                </value>
                <value>
                    <fullName>692 MARS Review</fullName>
                </value>
                <value>
                    <fullName>835 EDI Issues - Electronic Data Interchage (EDI)</fullName>
                </value>
                <value>
                    <fullName>AARP Medicare Supplemental on UCPS platform (Ovations GPS)</fullName>
                </value>
                <value>
                    <fullName>Accountable Mail</fullName>
                </value>
                <value>
                    <fullName>Advocate</fullName>
                </value>
                <value>
                    <fullName>Advocate Health Delegated Plans COSMOS</fullName>
                </value>
                <value>
                    <fullName>All Savers Insurance Company / American Medical Security (AMS) Claim issues</fullName>
                </value>
                <value>
                    <fullName>AP Help Tool- Issued to Providers without EOB/Remittance Information</fullName>
                </value>
                <value>
                    <fullName>Appeals - C&amp;S</fullName>
                </value>
                <value>
                    <fullName>Appeals E &amp; I (ONE Escalations)</fullName>
                </value>
                <value>
                    <fullName>BCCI for member benefit issues in system</fullName>
                </value>
                <value>
                    <fullName>BCO</fullName>
                </value>
                <value>
                    <fullName>BCU - CEAP</fullName>
                </value>
                <value>
                    <fullName>BCU - New Day Claim Holds</fullName>
                </value>
                <value>
                    <fullName>BCU Documentation</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health- New Mexico DSNP</fullName>
                </value>
                <value>
                    <fullName>Benefit (member deductible) - Individual Conversion Unit</fullName>
                </value>
                <value>
                    <fullName>Benefit Exceptions</fullName>
                </value>
                <value>
                    <fullName>Bridge</fullName>
                </value>
                <value>
                    <fullName>C&amp;S Automation</fullName>
                </value>
                <value>
                    <fullName>C&amp;S COSMOS reviews</fullName>
                </value>
                <value>
                    <fullName>C&amp;S CSP Review</fullName>
                </value>
                <value>
                    <fullName>CALL RECORDINGS / Member Services Call recordings</fullName>
                </value>
                <value>
                    <fullName>CALL RECORDINGS / Provider Call Ops</fullName>
                </value>
                <value>
                    <fullName>CAT Cases</fullName>
                </value>
                <value>
                    <fullName>CBRM  Non-par HCFA provider setup</fullName>
                </value>
                <value>
                    <fullName>CE Pending Signature</fullName>
                </value>
                <value>
                    <fullName>Check Returns - Recovery Refund Dept(TRACR2)</fullName>
                </value>
                <value>
                    <fullName>CPM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Provider Matrix</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Provider Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_FAST_ProviderMatrixCtrlTest.cls
/*****************************************************************************************************
ACET_FAST_ProviderMatrixCtrlTest
Testing Class Name:  ACET_FAST_ProviderMatrixCtrl
Author: Shaik Mohammad Yaseen
Date: 26/02/2021
Description: This is test class and used to get test coverage for ACET_FAST_ProviderMatrixCtrl. 
Initial: Shaik Mohammad Yaseen
******************************************************************************************************/
@isTest
public without sharing class ACET_FAST_ProviderMatrixCtrlTest {
    
    public static testMethod void fastCheck(){
        Profile sysAdminPrf = ACET_Fast_TestDataFactory.getSysAdminPrf();
        user sysAdminUser = ACET_Fast_TestDataFactory.getUserRecord(sysAdminPrf.id);
        insert sysAdminUser;
        System.runAs(sysAdminUser){
            case caseRec = ACET_Fast_TestDataFactory.getCaseRecord('Reactive_Resolution','Open');
            insert caseRec;
            Provider_Matrix__c pmatrix = new Provider_Matrix__c(name='test', LOB__c='C&S',Category__c='CPM', Sub_Category__c='CPM',CrossWalk_Case_RPI__c='test' );
            insert pmatrix;
            ACET_FAST_ProviderMatrixCtrl.getLobValues(caseRec.id);
            ACET_FAST_ProviderMatrixCtrl.getCategoryValues('C&S');
            ACET_FAST_ProviderMatrixCtrl.getSubCategoryValues('CPM');
            ACET_FAST_ProviderMatrixCtrl.getProverMatrixRecs('', '','', 'test',true );
            ACET_FAST_ProviderMatrixCtrl.getProverMatrixRecs('C&S', 'CPM','CPM', 'test',true );
            ACET_FAST_ProviderMatrixCtrl.getRPId(pmatrix.id);
        }
    }
}