src/objects/Routing_Configuration__c.object
<CustomObject>
    <description>Object to store routing configuration records for system auto routing cases to queues</description>
    <fields>
        <fullName>Priority_Routing__c</fullName>
        <label>Priority Routing</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceLevel__c</fullName>
        <description>Used to route to more urgent queues.  Example:  Platinum Providers have their cases routed to special queues.  Platinum Providers will have a code which is populated on the case at case creation.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Level</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type</valueSetName>
        </valueSet>
    </fields>
    <label>Routing Configuration</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Routing Configuration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Subtype.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1099sa Reprint Request</fullName>
    </customValue>
    <customValue>
        <fullName>1st Level Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>1st Level Balanced Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Level, Over $300</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Level Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party bill pay/verify fnds</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Fee Waiver</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Fee Waiver WEX</fullName>
    </customValue>
    <customValue>
        <fullName>5498sa Reprint Request</fullName>
    </customValue>
    <customValue>
        <fullName>5500 Requests</fullName>
    </customValue>
    <customValue>
        <fullName>A&amp;G Determination</fullName>
    </customValue>
    <customValue>
        <fullName>Account Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Account Number Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Account Offering Change</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Rebuild</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulators</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Bill Pay</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Bill Pay WEX</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Return</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Return WEX</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal Fraud</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal WEX</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisitions</fullName>
    </customValue>
    <customValue>
        <fullName>Activation/PIN setup</fullName>
    </customValue>
    <customValue>
        <fullName>Activation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Active License(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete/Update</fullName>
    </customValue>
    <masterLabel>Subtype</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Closure</fullName>
    </customValue>
    <customValue>
        <fullName>Account Maintenance/Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Account set up/Enrollment</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Rebuild</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Review</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Newborn (paper file only)</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information Needed</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>After Call Work- Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Alt Address</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative Medicine Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary Contracting</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Pre Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Status</fullName>
    </customValue>
    <customValue>
        <fullName>Apple</fullName>
    </customValue>
    <customValue>
        <fullName>Authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Behavioral Health</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Discrepancies</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Limitation Review</fullName>
    </customValue>
    <customValue>
        <fullName>BH Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Inquiry - Awaiting Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Issue</fullName>
    </customValue>
    <customValue>
        <fullName>C&amp;S Cosmos</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

src/classes/ECMRouteLogJobTest.cls
/***************************************************************************
 * @@Author: Pavan Kumar Annaldas
 * @@Description: Test class for "ECMRouteLogJob"
 * **************************************************************************/
@isTest
private class ECMRouteLogJobTest {
    
       @testsetup static void createTestQueues(){
          //create Test queue  
          Group  testQueue = new Group(Type = 'Queue' , Name= 'ECMTestQueue');
          insert testQueue ;
      
          QueuesObject q1 = new QueueSObject(QueueID = testQueue.id, SobjectType = 'Case');
          insert q1;           
    	}
    
   
    static void prepareData(){
        List<Case> caseLst = new list<Case>();
        caseLst.addAll(ECMTestDataUtil.createCase('Open',userInfo.getUserId(),5, true));
       
       Id groupId = [Select ID , Name from Group where Name= 'ECMTestQueue' Limit 1].Id;
       Id queueId = [Select Id,queue.id , queueID From QueueSobject where queueID = :groupID limit 1].queue.id;       
        caseLst.addAll(ECMTestDataUtil.createCase('Open',queueId,5, true));
        list<Routing_Configuration__c> configLst = new list<Routing_Configuration__c>();
        
        configLst.addAll(ECMTestDataUtil.createRoutingConfiguration('ECMTestQueue', 2, 15, true));
    }
    
    static testMethod void testSuccessAndFailureLogsCreation(){
		prepareData();
        list<Routing_Configuration__c> configLst = new list<Routing_Configuration__c>([select id from Routing_Configuration__c]);
        List<Case> caseLst = new list<Case>([Select Id, Priority, Subtype__c, Type__c, Priority_Routing__c, 
        Status, Topic__c, OwnerId , ServiceLevel__c from Case]);
        
        map<id,Routing_Configuration__c> successMap = new map<id, Routing_Configuration__c>();
        for(Case c: caseLst){
            for(Routing_Configuration__c r : configLst){
                successMap.put(c.id, r);
            }
        }
        
        test.startTest();
        System.enqueueJob(new ECMRouteLogJob(successMap,caseLst));
        test.stopTest();
    }
    
    
}