src/objects/Route_Log__c.object
<CustomObject>
    <description>Stores case routing attempt records with their outcomes (errors and successes)</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Route Logs</relationshipLabel>
        <relationshipName>Route_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CurrentQueue__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Queue</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Expedited</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProfileName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueueName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Queue Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoutingConfiguration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Routing Configuration #</label>
        <referenceTo>Routing_Configuration__c</referenceTo>
        <relationshipLabel>Route Logs</relationshipLabel>
        <relationshipName>Route_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RoutingPriority__c</fullName>
        <label>Priority Routing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceLevel__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Level</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic1__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Topic</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type</valueSetName>
        </valueSet>
    </fields>
    <label>Route Log</label>
    <nameField>
        <displayFormat>RL-{0000000000}</displayFormat>
        <label>RL #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Routing_Configuration__c.object
<CustomObject>
    <description>Object to store routing configuration records for system auto routing cases to queues</description>
    <fields>
        <fullName>CurrentQueue__c</fullName>
        <description>Describes the current value of the queue, so that the system can pick the correct queue for routing</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Queue</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority_Routing__c</fullName>
        <label>Priority Routing</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                    <isActive>false</isActive>
                    <label>Escalated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProfileName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>Used to capture queue name case will be routed to</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Queue Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoleName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceLevel__c</fullName>
        <description>Used to route to more urgent queues.  Example:  Platinum Providers have their cases routed to special queues.  Platinum Providers will have a code which is populated on the case at case creation.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Service Level</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Reopen</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Subtype</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Topic1__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Topic</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type</valueSetName>
        </valueSet>
    </fields>
    <label>Routing Configuration</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Routing Configuration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routing Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Subtype.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1099sa Reprint Request</fullName>
    </customValue>
    <customValue>
        <fullName>1st Level Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>1st Level Balanced Billing</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Level, Over $300</fullName>
    </customValue>
    <customValue>
        <fullName>2nd Level Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party bill pay/verify fnds</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Fee Waiver</fullName>
    </customValue>
    <customValue>
        <fullName>3rd Party Fee Waiver WEX</fullName>
    </customValue>
    <customValue>
        <fullName>5498sa Reprint Request</fullName>
    </customValue>
    <customValue>
        <fullName>5500 Requests</fullName>
    </customValue>
    <customValue>
        <fullName>A&amp;G Determination</fullName>
    </customValue>
    <customValue>
        <fullName>Account Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Account Number Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Account Offering Change</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Rebuild</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulators</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Bill Pay</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Bill Pay WEX</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Dispute</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Return</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Return WEX</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal Fraud</fullName>
    </customValue>
    <customValue>
        <fullName>ACH Withdrawal WEX</fullName>
    </customValue>
    <customValue>
        <fullName>Acquisitions</fullName>
    </customValue>
    <customValue>
        <fullName>Activation/PIN setup</fullName>
    </customValue>
    <customValue>
        <fullName>Activation Request</fullName>
    </customValue>
    <customValue>
        <fullName>Active License(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Add</fullName>
    </customValue>
    <customValue>
        <fullName>Add/Delete/Update</fullName>
    </customValue>
    <masterLabel>Subtype</masterLabel>
</GlobalValueSet>

src/globalValueSets/Topic.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ACC</fullName>
    </customValue>
    <customValue>
        <fullName>Accounts Receivable</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals &amp; Grievances</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Post Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Pre Service</fullName>
    </customValue>
    <customValue>
        <fullName>Balance Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Benefits and Eligibility</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>CI</fullName>
    </customValue>
    <customValue>
        <fullName>Claims</fullName>
    </customValue>
    <customValue>
        <fullName>Coaching</fullName>
    </customValue>
    <customValue>
        <fullName>Commissions</fullName>
    </customValue>
    <customValue>
        <fullName>Communications</fullName>
    </customValue>
    <customValue>
        <fullName>Consumer Accounts</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Option(s)</fullName>
    </customValue>
    <customValue>
        <fullName>Coordination of Benefits</fullName>
    </customValue>
    <customValue>
        <fullName>Create Authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Create PCP Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Critical Condition Pre-emptive Outreach</fullName>
    </customValue>
    <customValue>
        <fullName>Debit Cards</fullName>
    </customValue>
    <customValue>
        <fullName>Dental</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Drug Approval Status</fullName>
    </customValue>
    <customValue>
        <fullName>Email issues to be sent to the CSS team for handling/follow up</fullName>
    </customValue>
    <customValue>
        <fullName>Employer/Broker Other Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Enroll Member</fullName>
    </customValue>
    <customValue>
        <fullName>Enroll Subscriber</fullName>
    </customValue>
    <customValue>
        <fullName>Escalated Call Backs</fullName>
    </customValue>
    <masterLabel>Topic</masterLabel>
</GlobalValueSet>

src/globalValueSets/Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Account Closure</fullName>
    </customValue>
    <customValue>
        <fullName>Account Maintenance/Changes</fullName>
    </customValue>
    <customValue>
        <fullName>Account set up/Enrollment</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Rebuild</fullName>
    </customValue>
    <customValue>
        <fullName>Accumulator Review</fullName>
    </customValue>
    <customValue>
        <fullName>Adding Newborn (paper file only)</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Additional Information Needed</fullName>
    </customValue>
    <customValue>
        <fullName>Administrative</fullName>
    </customValue>
    <customValue>
        <fullName>After Call Work- Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Alt Address</fullName>
    </customValue>
    <customValue>
        <fullName>Alternative Medicine Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary Contracting</fullName>
    </customValue>
    <customValue>
        <fullName>Ancillary Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Appeals - Pre Service</fullName>
    </customValue>
    <customValue>
        <fullName>Appeal Status</fullName>
    </customValue>
    <customValue>
        <fullName>Apple</fullName>
    </customValue>
    <customValue>
        <fullName>Authorization</fullName>
    </customValue>
    <customValue>
        <fullName>Behavioral Health</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Discrepancies</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Limitation Review</fullName>
    </customValue>
    <customValue>
        <fullName>BH Appeal</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Inquiry</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Inquiry - Awaiting Documentation</fullName>
    </customValue>
    <customValue>
        <fullName>Billing Issue</fullName>
    </customValue>
    <customValue>
        <fullName>C&amp;S Cosmos</fullName>
    </customValue>
    <masterLabel>Type</masterLabel>
</GlobalValueSet>

src/classes/ECMRouteLogJob.cls
/***************************************************************************
 * @@Author: Pavan Kumar Annaldas
 * @@Description: Creates Success and Failure "Route_Log__c" records
 * **************************************************************************/

public class ECMRouteLogJob implements Queueable {

    public Map<id,Routing_Configuration__c> routeLogMapforSuccess; // Key should be case id, this map indicates case records, which are routed successfully 
    public list<case> caseList; //List case records, which are failed to Route
    
    public ECMRouteLogJob(Map<id,Routing_Configuration__c> routeLogMapforSuccess,list<case> caseList){
        this.routeLogMapforSuccess = routeLogMapforSuccess;
        this.caseList = caseList;
    }
    
    public void execute(QueueableContext context) {
        try{
            list<Route_Log__c> routeLogsToInsert = new list<Route_Log__c>();
            routeLogsToInsert.addAll(prepareSuccessRouteLogs()); 
            routeLogsToInsert.addAll(prepareFailuerRouteLogs());
            if(!routeLogsToInsert.isEmpty()){
              insert routeLogsToInsert;
            }
        }catch(exception ex){
            system.debug(LoggingLevel.Error,'Exception occured while inserting Routing Logs  '+ex.getMessage());
        }
    }
    
    /*Process success records, which are routed 
      and return list<Route_Log__c> records*/
    public list<Route_Log__c> prepareSuccessRouteLogs(){
        list<Route_Log__c> routeLogsToInsert = new list<Route_Log__c>();
        if(routeLogMapforSuccess != null && !routeLogMapforSuccess.isEmpty()){
            set<id> routingConfigurationIds = new set<id>();
            for(Routing_Configuration__c config : routeLogMapforSuccess.values()){
                routingConfigurationIds.add(config.id);
            }
            map<id,Routing_Configuration__c> configMap = new map<id, Routing_Configuration__c>([Select Id, CurrentQueue__c, Priority__c,Queue_Name__c,
                                                                                                ProfileName__c, RoleName__c, Subtype__c, Type__c,  Priority_Routing__c, 
                                                                                                Status__c, Topic1__c , SortOrder__c,  ServiceLevel__c From Routing_Configuration__c where id in:routingConfigurationIds]);
            for(id caseID : routeLogMapforSuccess.keySet()){
                if(routeLogMapforSuccess.get(caseID) != null && configMap.get(routeLogMapforSuccess.get(caseID).id) != null){
                    Routing_Configuration__c routingConfig = configMap.get(routeLogMapforSuccess.get(caseID).id);
                    //create route log
                    Route_Log__c newLog = new Route_Log__c(Case__c = caseID);
                    
                    //updaing route log
                    newLog.QueueName__c = routingConfig.Queue_Name__c;
                    newLog.RoutingConfiguration__c= routingConfig.Id;
                    newLog.CurrentQueue__c = routingConfig.CurrentQueue__c;              
                    newLog.Priority__c = routingConfig.Priority__c;
                    newLog.ProfileName__c = routingConfig.ProfileName__c;
                    newLog.RoleName__c = routingConfig.RoleName__c;
                    newLog.Subtype__c = routingConfig.Subtype__c;
                    newLog.Type__c = routingConfig.Type__c;
                    newLog.RoutingPriority__c = routingConfig.Priority_Routing__c ;
                    newLog.Status__c = routingConfig.Status__c;
                    newLog.Topic1__c = routingConfig.Topic1__c;
                    newLog.SortOrder__c = routingConfig.SortOrder__c;
                    newLog.ServiceLevel__c = routingConfig.ServiceLevel__c;
                    routeLogsToInsert.add(newLog);
                }
            }
        }
        return routeLogsToInsert;
    }
    
    /*Process failure records, which are failed to route 
      and return list<Route_Log__c> records*/
    public list<Route_Log__c> prepareFailuerRouteLogs(){
        list<Route_Log__c> routeLogsToInsert = new list<Route_Log__c>();
        if(caseList != null && !caseList.isEmpty()){
            set<id> queueIds = new set<id>();
            set<id> userIds = new set<id>();
            map<id, QueueSobject> queueMap = new map<id, QueueSobject>();
            map<id, user> userMap = new map<id, user>();
            for(case cs : caseList){
                string ownerId = cs.ownerId;
                if(ownerId.startsWith('005')){
                    userIds.add(ownerId);
                }else{
                    queueIds.add(ownerID); 
                } 
            }
            if(queueIds.size() > 0)
                queueMap = new map<id, QueueSobject>([Select Id, Queue.Name From QueueSobject where SobjectType = 'Case' and QueueId in:queueIds]);
            if(userIds.size() > 0)
                userMap = new map<id, user>([Select UserRole.Name,Profile.Name from User where id in:userIds ]);
            for(case cs : caseList){
                //create route log //
                Route_Log__c newLog = new Route_Log__c(Case__c = cs.id);
                
                //updaing route log
                if(queueMap.get(cs.ownerID) != null){
                    newLog.CurrentQueue__c = queueMap.get(cs.ownerID).queue.Name;
                }else if(userMap.get(cs.ownerID) != null){
                    User owner = userMap.get(cs.ownerID);    
                    newLog.ProfileName__c = owner.Profile.Name;
                    newLog.RoleName__c = owner.UserRole.Name;    
                }  

                newLog.Priority__c = cs.Priority;
                newLog.Subtype__c = cs.Subtype__c ;
                newLog.Type__c = cs.Type__c;
                newLog.RoutingPriority__c = cs.Priority_Routing__c;
                newLog.Status__c = cs.Status;
                newLog.Topic1__c = cs.Topic__c;
                newLog.ServiceLevel__c = cs.ServiceLevel__c;
                routeLogsToInsert.add(newLog);
            }
        }
        return routeLogsToInsert;
    }

  
}