src/objects/Special_Instructions__c.object
<CustomObject>
    <fields>
        <fullName>BusinessDirectionExternalID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>BusinessDirectionExternalID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <label>Special Instruction</label>
    <nameField>
        <displayFormat>SI-{00000000}</displayFormat>
        <label>Special Instruction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Special Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ETSBE_ArchiveSpecialInsBatch.cls
global class ETSBE_ArchiveSpecialInsBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext BC) {
    
        String curr = date.today().addDays(-30).format();
        String month = curr.split('/')[0];
        String day = curr.split('/')[1];
        String year = curr.split('/')[2];
        if(integer.valueof(month) < 10){
            month = '0' + month;
        }
        if(integer.valueof(day) < 10){
            day = '0' + day;
        }
        curr = year + '-' + month + '-' + day;
        
        //Below is to archive termed special instructions
        String query = 'Select Id, BusinessDirectionExternalID__c, End_Date__c FROM Special_Instructions__c Where End_Date__c <= '+ curr;
        return Database.getQueryLocator(query);
    }    
    
    global void execute(Database.BatchableContext BC, List<Special_Instructions__c> scope) {
        if(Special_Instructions__c.sObjectType.getDescribe().isDeletable()){
            delete scope;
        }
    }    
    
    global void finish(Database.BatchableContext BC) {
    }
}