src/objects/Stream_Request_Details__c.object
<CustomObject>
    <description>This object is used to capture request details specific to the request type on ERM cases.</description>
    <fields>
        <fullName>Bypass_Validation_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Validation Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pended_Reason__c</fullName>
        <description>Pended Reason for Pended request in ERM</description>
        <label>Pended Reason</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Billing access not showing under Broker/Employer</fullName>
                </value>
                <value>
                    <fullName>Broker/Employer Address mismatch</fullName>
                </value>
                <value>
                    <fullName>Broker/Employer Agency not found</fullName>
                </value>
                <value>
                    <fullName>Incorrect request form selection</fullName>
                </value>
                <value>
                    <fullName>Invalid policy</fullName>
                </value>
                <value>
                    <fullName>Missing Name</fullName>
                </value>
                <value>
                    <fullName>Missing/Invalid email id</fullName>
                </value>
                <value>
                    <fullName>Policy access level missing</fullName>
                </value>
                <value>
                    <fullName>Policy already associated with another employee for employer request</fullName>
                </value>
                <value>
                    <fullName>Reporting level missing</fullName>
                </value>
                <value>
                    <fullName>System issue (internal error)</fullName>
                </value>
                <value>
                    <fullName>User email provided indicates an internal UHG user</fullName>
                </value>
                <value>
                    <fullName>User not found under Broker/Employer</fullName>
                </value>
                <value>
                    <fullName>AB1401</fullName>
                </value>
                <value>
                    <fullName>ADDRESS</fullName>
                </value>
                <value>
                    <fullName>AUTHORIZATION LETTER FROM DOCTOR</fullName>
                </value>
                <value>
                    <fullName>BILLING REVIEW NEEDED</fullName>
                </value>
                <value>
                    <fullName>CAL COBRA</fullName>
                </value>
                <value>
                    <fullName>CASE INSTALLATION ISSUE</fullName>
                </value>
                <value>
                    <fullName>CLOSED PROVIDER</fullName>
                </value>
                <value>
                    <fullName>COLORADO TERM</fullName>
                </value>
                <value>
                    <fullName>CONFLICTING INFORMATION</fullName>
                </value>
                <value>
                    <fullName>COPY OF MEDICARE CARD REQUIRED</fullName>
                </value>
                <value>
                    <fullName>COURT ORDER</fullName>
                </value>
                <value>
                    <fullName>COVERAGE TYPE (PPO or HMO)</fullName>
                </value>
                <value>
                    <fullName>CUSTOMER PROFILE</fullName>
                </value>
                <value>
                    <fullName>DATE OF HIRE</fullName>
                </value>
                <value>
                    <fullName>DEPENDENT</fullName>
                </value>
                <value>
                    <fullName>DISABLED DEPENDENT</fullName>
                </value>
                <value>
                    <fullName>DOB</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request Details</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Request Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ERM_InboundUpdateService.cls
@RestResource(urlMapping='/ermAPI/*')
global without sharing class ERM_InboundUpdateService {
    
    @HTTPPut
    global static String upsertStatusCaseComment() { 
        
        Case caseRec=new Case();
        List<CaseComment> caseCommentLst=new List<CaseComment>();
        List<Stream_Request_Details__c> reqDetailLst=new List<Stream_Request_Details__c>();
        try{
            RestRequest req = RestContext.request;
            CustomReq commentWrap = (CustomReq)JSON.deserialize(req.requestbody.tostring(),CustomReq.class);
            System.debug('commentWrap=='+commentWrap);
            
            if(!String.isBlank(commentWrap.requestNumber)){
                caseRec=[Select id,External_Reference_ID__c,Status,IsEscalated,(Select id,Pended_Reason__c from Request_Details__r ) from Case where External_Reference_ID__c=:commentWrap.requestNumber LIMIT 1];
                System.Debug('caseRec===='+caseRec);
            }else{
                return 'No Matches found';
            }
            
            if(caseRec!=null){
                caseRec.Status=commentWrap.status;
                caseRec.No_More_Comments__c=true;
                Update caseRec;
            }                        
            List<comment> commentString = commentWrap.commentCase;  
            List<PendedReason> pendedReasonLstString=commentWrap.pendedReason;
            
            for(integer i=0;i<commentString.size();i++){
                CaseComment newComnt = new CaseComment();
                newComnt.CommentBody=commentString[i].Body;
                newComnt.IsPublished = TRUE;
                newComnt.ParentId = caseRec.Id;
                caseCommentLst.add(newComnt);            
            }
            insert caseCommentLst;
            
            if(caseRec.Request_Details__r!=null){
                for(Stream_Request_Details__c reqRec:caseRec.Request_Details__r){
                    
                    List<String> resonStr=new List<String>();                   
                    for(integer i=0;i<pendedReasonLstString.size();i++){
                        resonStr.addall(pendedReasonLstString[i].Reason.split(','));                    
                    }             
                    reqRec.Pended_Reason__c=String.join(resonStr, ';');
                    reqRec.Bypass_Validation_Rule__c=true;
                    reqDetailLst.add(reqRec);
                } 
                  update reqDetailLst;
            }   
            return 'Success';  
        }catch(Exception e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            return +e.getMessage();
        }
        
    }      
    
    global class CustomReq{
        Public String requestNumber;
        Public String status;
        Public List<Comment> commentCase;
        public List<PendedReason> pendedReason;
    }
    
    global class Comment{
        public string Body;
    }
    
    global class PendedReason{
        public string Reason;
    }
}