src/objects/Tool_Tip__c.object
<CustomObject>
    <description>Object to store business enabled contextual tips based on elements on the screen (e.g, guidance on a claim denial by its denial remark code).</description>
    <fields>
        <fullName>SOP_or_Document_Link__c</fullName>
        <description>Holds the URL of the SOP or document</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the URL of the SOP/Document</inlineHelpText>
        <label>SOP or Document Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SOP_or_Document_Name__c</fullName>
        <description>Holds the name of a linked SOP or document</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the name of the SOP/Document</inlineHelpText>
        <label>SOP or Document Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tip__c</fullName>
        <description>Holds the tip for the remark code or status</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the tool tip here</inlineHelpText>
        <label>Tip</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tool_Tip_Type__c</fullName>
        <description>Used to determine what the tool tip relates to</description>
        <label>Tool Tip Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Claim</fullName>
                </value>
                <value>
                    <fullName>Delegated</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <description>Used to hold the code the tool tip applies to</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the remark code or status tool tip applies to here.  Use &apos;*&apos; for the wildcard tool tip.</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Tool Tip</label>
    <nameField>
        <displayFormat>Tool Tip - {000000}</displayFormat>
        <label>Tool Tip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tool Tips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ACET_ClaimServiceLineDetailsController.cls
public class ACET_ClaimServiceLineDetailsController {
   
@AuraEnabled
public static list<Tool_Tip__c> getToolTips( List<String> rcodes)
    {
              
        List<Tool_Tip__c> tips = [Select Tip__c,SOP_or_Document_Link__c,SOP_or_Document_Name__c,Value__c from tool_tip__c where Value__c in :rcodes and Tool_Tip_Type__c = 'Claim' ];    
        List<Tool_Tip__c> tips_appended = new List<Tool_Tip__c>();
        List<Tool_Tip__c> tips_notFoundList = new List<Tool_Tip__c>();

       boolean found = false;
        System.debug('Ketki log  tips size::'+tips.size());
        System.debug('Ketki log  rcodes::'+rcodes);
        System.debug('Ketki log  rcodes size::'+rcodes.size());

        for ( integer i = 0; i< rcodes.size(); i++)
        {
            System.debug('Ketki log  inside rcode for loop');
            found = false;



            for (integer j =0; j< tips.size();j++)
            {
                if(rcodes[i] == tips[j].Value__c)
                {
                    found = true;
                    System.debug('Ketki log is found tips for loop::'+ found);
                    tips_appended.add(tips[j]);
                    break;
                }
            }

            if (found == false)
            {
                System.debug('Ketki log is found  if tip not found::'+ found);
                Tool_Tip__c Tip = new Tool_Tip__c();
                Tip.Value__c = rcodes[i];
                Tip.Tool_Tip_Type__c='Claim';
                tips_notFoundList.add(Tip);
                //insert Tip;
            }

        }
        insert tips_notFoundList;
        tips_appended.addAll(tips_notFoundList);
        
        return tips_appended;
    }
    
}