src/objects/WorkOrder.object
<CustomObject>
    <fields>
        <fullName>HSC_Unique_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HSC ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Host_System_Date_and_Time__c</fullName>
        <description>The date and time the transaction was updated in the host system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Host System Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status_Detail__c</fullName>
        <label>Status Detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prior Authorization Received</fullName>
                </value>
                <value>
                    <fullName>Benefit Coverage Determination</fullName>
                </value>
                <value>
                    <fullName>Clinical Review</fullName>
                </value>
                <value>
                    <fullName>MD Review</fullName>
                </value>
                <value>
                    <fullName>Decision has been made</fullName>
                </value>
                <value>
                    <fullName>Peer to Peer Scheduled</fullName>
                </value>
                <value>
                    <fullName>Requested Missing Information</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Xref_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Xref ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ACETSNIWorkOrderDetailsTest.cls
@isTest
public class ACETSNIWorkOrderDetailsTest {
    @testSetup static void setup() {
        User thisUser = [Select Id From User Where Id =:UserInfo.getUserId()];
        User userObj;
         System.runAs(thisUser){

         userObj =  TestDataFactory.getUser('System Administrator');
        userObj.Username='tUserAuth@testorg.acet';
        userObj.FederationIdentifier='tUser';
        INSERT userObj;        
        workOrder workOrderObj = new workOrder();
        workOrderObj.HSC_Unique_ID__c='156627064';
        workOrderObj.Xref_ID__c='625871210';
        workOrderObj.Status_Detail__c	 = 'Prior Authorization Received';
        workOrderObj.Host_System_Date_and_Time__c = datetime.now();
        INSERT workOrderObj;
         }
    }
    @isTest static void getauthorizeDetailsTest() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpGetAuthResponseGenerator(200,'GetAuthCHSMockResponse'));
        WorkOrder workOrderObj =[select Id,HSC_Unique_ID__c,Xref_ID__c from WorkOrder limit 1].get(0);
        System.debug('workOrderObj'+workOrderObj);
        ACET_GetAuthorizationStatusDetails.AuthDetailsRequest requestObj = new ACET_GetAuthorizationStatusDetails.AuthDetailsRequest();
        requestObj.AUTH_ID = '165591771';
        requestObj.XREF_ID = '962558261';
        ACET_AuthorizationController.SearchResultWrapperAuthStatus response = ACET_AuthorizationController.getAuthorizationStatus(requestObj);
        ACETSNIWorkOrderDetails.getAuthorizeDetails(workOrderObj.Id);
        MockHttpGetAuthResponseGenerator authGen = new MockHttpGetAuthResponseGenerator(200,'GetAuthCHSMockResponse');
        authGen.respond(new HttpRequest());
        Test.stopTest();
    }
}